### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by adiadore** [btcpayserver/btcpayserver-docker#103]
Current Version is BTCPayServer v1.0.3.54
Tried it with Server Settings > Maintenance > Update "The server might restart soon if an update is available..." but version stays the same.
Then via ssh with
sudo su -
btcpay-update.sh

> Updating c02d7c4..52d987a
> error: Your local changes to the following files would be overwritten by merge:
>         Production/nginx.tmpl
>         docker-compose-generator/docker-fragments/bitcoin-clightning.yml
>         docker-compose-generator/docker-fragments/bitcoin-lnd.yml
>         docker-compose-generator/docker-fragments/btcpayserver.yml
>         docker-compose-generator/docker-fragments/groestlcoin-clightning.yml
>         docker-compose-generator/docker-fragments/groestlcoin.yml
>         docker-compose-generator/docker-fragments/litecoin-lnd.yml
> Please commit your changes or stash them before you merge.
> Aborting

How do i commit/stash changes? (what changes are meant by the way?), couldn't find anything in the FAQs.

**Comment by Kukks** [comment]
It looks like you edited some files in the docker folder in some way? 

try running 
`git reset --hard origin/master` then update

**Comment by adiadore** [comment]
thank you! worked for me, although it is strange because never touched the files above. Might be worth adding to the FAQs in case someone has the same problem
