### ISSUE TITLE
Whats the maintenance password?

### ISSUE THREAD

**Issue by Elmit2015** [btcpayserver/btcpayserver-docker#104]
I believe I followed the instructions to setup. I got informed that BTCpayserver got upgraded yesterday and it is easy to do, just go to Server settings / Maintenance and click upgrade. 

It filled in as User btcpayserver and I am puzzled what the password is.
The os does not have a user btcpayserver.

**Comment by NicolasDorier** [comment]
You probably have a old deployement or set it up yourself manually.

To update, you need to connect to SSH to your VM and run `btcpay-update.sh`. Most automatic installs does it for you, as we setup a SSH private key and give it to BTCPay to access the server.

So you need to connect via SSH and root into your machine and run `btcpay-update.sh`

**Comment by Elmit2015** [comment]
Thanks, that worked. I mean the command run flawless. I wonder where I can see the version number it is running.

**Comment by NicolasDorier** [comment]
when you are logged in, in the footer of the site.
If you want to use the maintenance button, follow this https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#btcpay_sshkeyfile-is-not-set-when-running-the-docker-install-or-unable-to-update-through-server-settings-maintenance

**Comment by Elmit2015** [comment]
I want to set an alias name for my node. I have set the environment variable, but how do I get it into docker?

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver-docker#how-can-i-modify-my-environment
