### ISSUE TITLE
Payment request HELP needed

### ISSUE THREAD

**Issue by Elmit2015** [btcpayserver/btcpayserver-docker#105]
I tried to create a payment request and it resulted in a link:

https://btcpay.elmit.comment-requests/hub?id=PmLR05JB8HY8dAS_nvSlWw

It should be something with btcpay.elmit.com/ 
I use Docker, where did it go wrong?

I want to use this payment request in a calendar for online teachers. If the time slot is still free then a student can pay this invoice. If it is already occupied, then the time slot would be already be paid and not anymore available.  How can I "distinguish" on a web page if the invoice is already paid or not? I would use then different images.

**Comment by NicolasDorier** [comment]
We fixed it now. However, I messed up during an update, so if you are unable to update to version .73 from the website, see https://twitter.com/BtcpayServer/status/1100749917591465984
