### ISSUE TITLE
How to update to clightning 0.7?

### ISSUE THREAD

**Issue by Elmit2015** [btcpayserver/btcpayserver-docker#106]
Clightning has a new release (0.7)
I tried to login and run win the directory bitpayserver-docker/ the command btcpay-update.sh
It gives me again the older 0.63 version of clightning.

What do I need to do to get the newer version?

**Comment by NicolasDorier** [comment]
Can you try again? I released the version very recently (in the last hour)
Tried the update, and it worked.

**Comment by NicolasDorier** [comment]
Give me the logs, if it does not update. As well as the output of 
```
docker ps
```

**Comment by Elmit2015** [comment]
Thanks, it updated now. I was too fast, sorry for my impatience ;-)

**Comment by NicolasDorier** [comment]
I advise you to update again, I fixed a bug where you would have been unable to pay an invoice from your c-lightning node.
