### ISSUE TITLE
Port 80 connects to WordPress at root of domain, but not to BTCPayServer at pay.domain

### ISSUE THREAD

**Issue by ch4ot1c** [btcpayserver/btcpayserver-docker#112]
-  Using fragments: `opt-save-storage-xs;opt-add-woocommerce`. On initial run, WP setup appeared, was successful, and WP seems to be useable (at `mydomain.com`).

- However, visiting the route `pay.mydomain.com`, as configured for BTCPayServer, won't load - it fails with `ERR_CONNECTION_TIMED_OUT` on Chrome (This site can’t be reached: pay.mydomain.com took too long to respond.). Same thing with `https://`.

- Both NBXplorer and BTCPayServer are successfully reporting 'New Block' events. Also, bitcoind seems to be fully syncd (progress 1.0, correct height).

- Running for BTC only on a DigitalOcean one-click instance, per this guide: https://medium.com/@molthoff/running-btcpay-on-digital-ocean-for-10-month-how-to-add-other-coins-7a497339fb2f. Disk usage is at 64%, Memory usage is at 54%.

- The nginx configuration seems to contain the right url: `pay.mydomain.com`

- I have run `./btcpayserver-restart.sh`, and even `./changedomain.sh pay.mydomain.com`

- Upon inspecting `letsencrypt-nginx-proxy-companion`:
```
2019/03/17 20:05:24 Received event start for container 2cba9a1be126
2019/03/17 20:05:26 Received event die for container 2cba9a1be126
2019/03/17 20:05:41 Debounce minTimer fired
2019/03/17 20:05:41 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2019/03/17 20:06:26 Received event start for container 2cba9a1be126
2019/03/17 20:06:28 Received event die for container 2cba9a1be126
2019/03/17 20:06:43 Debounce minTimer fired
2019/03/17 20:06:43 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
```

Seems to be stuck in this loop, continuously restarting the LND image. There is nothing in `logs/lnd.log`

Also just saw this message from nginx:

```
x.x.x.x - - [17/Mar/2019:20:01:13 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 166 "-" "-"
2019/03/17 20:11:32 [warn] 8#8: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/mydomain.com.crt"
```

Any ideas?

**Comment by ch4ot1c** [comment]
Note - I put in the wrong hostname the first time I ran `./btcpay-setup.sh` - this must have caused the misconfiguration.

I then changed it to the appropriate value in my environment, and re-ran setup, but nothing changed.

**Comment by NicolasDorier** [comment]
Can you `btcpay-update.sh` again? i may have fixed it.

**Comment by ch4ot1c** [comment]
Updated and ran changedomain and restarted. Similar results, still not working (`lnd` restarting nonstop): 

- nginx-gen:
```
2019/03/19 21:05:39 Received event start for container 4e5923cd3fd4
2019/03/19 21:05:39 Received event die for container 4e5923cd3fd4
2019/03/19 21:05:44 Debounce minTimer fired
2019/03/19 21:05:44 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification '
2019/03/19 21:06:40 Received event start for container 4e5923cd3fd4
2019/03/19 21:06:40 Received event die for container 4e5923cd3fd4
2019/03/19 21:06:45 Debounce minTimer fired
2019/03/19 21:06:45 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
```

- letsencrypt-nginx-proxy-companion:
```
2019/03/19 21:04:47 Received event start for container 4e5923cd3fd4
2019/03/19 21:04:47 Received event die for container 4e5923cd3fd4
2019/03/19 21:05:02 Debounce minTimer fired
2019/03/19 21:05:02 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2019/03/19 21:05:39 Received event start for container 4e5923cd3fd4
2019/03/19 21:05:39 Received event die for container 4e5923cd3fd4
2019/03/19 21:05:54 Debounce minTimer fired
2019/03/19 21:05:54 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
```

- ` letsencrypt_service_data`:
```
LETSENCRYPT_CONTAINERS=( '4bc77ce77efd'  '29c200add265' )
LETSENCRYPT_4bc77ce77efd_HOST=( 'pay.x.dev' )
LETSENCRYPT_4bc77ce77efd_EMAIL="<no value>"
LETSENCRYPT_4bc77ce77efd_KEYSIZE="<no value>"
LETSENCRYPT_4bc77ce77efd_TEST="<no value>"
LETSENCRYPT_4bc77ce77efd_ACCOUNT_ALIAS="<no value>"
LETSENCRYPT_29c200add265_HOST=( 'x.dev' )
LETSENCRYPT_29c200add265_EMAIL="<no value>"
LETSENCRYPT_29c200add265_KEYSIZE="<no value>"
LETSENCRYPT_29c200add265_TEST="<no value>"
LETSENCRYPT_29c200add265_ACCOUNT_ALIAS="<no value>"
```

- `default.conf`:
The only problem I see with this file is the `proxy_pass` prefix being set to `http://btcpay` instead of `http://pay` as specified in my environment, but maybe that is a non-issue. The same is true for `default.conf` in the `nginx:stable` docker image itself. How do I make this change apply to `nginx:stable` and restart it (it doesn't have `vi`)?

Maybe the problem is an invalid key/crt/pem - is there a way to refresh/delete all letsencrypt keys & create fresh nginx-related containers? Maybe `force_renew`?

Btw - I am using a `.dev` top-level domain.

Thanks

**Comment by NicolasDorier** [comment]
If you do `docker logs nginx -f` and try to browse pay.domain.com, you should see logs appearing about an incoming request.

If this is not the case, it means something is blocking your request before it reach nginx  (firewall?)

**Comment by NicolasDorier** [comment]
I think your certificate has been generated. You can see your nginx configuration if it is the case.

**Comment by ch4ot1c** [comment]
Oh wow - I had forgotten to add the `A` record for `pay.x.dev`! Once added, the Chrome error became 'Your connection is not secure' and a mention of HSTS and HTTPS. I then just used Shift+F5 to refresh my cache and BTCPayServer was visible at `https://pay.x.dev`. Hooray!

Thanks for the help; hopefully this helps someone troubleshoot.

**Comment by NicolasDorier** [comment]
hey @astupidmoose can you add a small note about firewall need port 443 and 80 open to your article?

**Comment by astupidmoose** [comment]
Added :D
