### ISSUE TITLE
Calling webdocket (ledger) routes from a different origin 

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver-docker#115]
I have BTCPay deployed and I am trying to call the ledger route
 
 `[Route("{walletId}/send/ledger/ws")]` 

from a different origin (another web app with different domain). It works fine when I run BTCPay with RegTest profile on my machine but when I deploy it using btcpay-setup.sh for some reason the request always times out and there is no trace of it in nginx logs. 

Is this by design? Should I have different config for my nginx?

**Comment by NicolasDorier** [comment]
closed?

**Comment by sigHash** [comment]
I wasn't really sure if there was an issue with my CI/CD or the nginx conf here. 

 Here's what I experienced:

I tried to deploy BTCPay on a PC (running ubuntu) behind a router and websocket routes stopped working. I checked the nginx logs and there is no trace of GET request for ledger routes. it simply times out.

I should mention that I am making cross origin calls to those routes from a React web app, but i have enabled Cors.

  I still can not make it work on-prem, but it works fine on azure without making any changes. (same docker images)

**Comment by NicolasDorier** [comment]
where it does not work, you are using a reverse proxy somewhere ?

**Comment by sigHash** [comment]
No, it's a bare metal machine, behind a router. I started BTCPAY with nginx as reverse proxy as mentioned here:

[Hardware Deployment](https://docs.btcpayserver.org/deployment/hardwaredeployment)

**Comment by NicolasDorier** [comment]
Can you make an invoice and check in the Console logs if it manage or not to connect websocket?
