### ISSUE TITLE
Bitcoin Core Version

### ISSUE THREAD

**Issue by larry-beck** [btcpayserver/btcpayserver-docker#118]
I have btcpayserver-docker installed and running just fine, however, when I view the version of Bitcoin Core installed via the bitcoind --version or bitcoin-cli.sh getnetworkinfo, the install of btcpayserver is only installing v.0.17.0 and not v.0.17.1 which is the latest version of Bitcoin Core. Is there a way to upgrade this as I had a BC full node running before installing btcpayserver and it still shows from the bitcoind program that it is the latest version of v.0.17.1 which is the code base I would prefer for my node to be running. Or is there no way to install an upgrade to Bitcoin Core while running btcpayserver on the same hardware?

**Comment by NicolasDorier** [comment]
It is not worth it to support 0.17.1 now because 0.18.0 will release very soon (in a week or so)

I will update when it releases.

**Comment by larry-beck** [comment]
I understand that point, but I am more asking about future, is there a way to get new BC releases into the product immediately and allow an upgrade mechanism for not only BC, but what about Lightning and RTL, especially with the major changes upcoming for LND? Just thinking ahead to keep underlying core software pieces at the most current release, that is the whole point of decentralized software such as BC in the first place, being able to choose our consensus. Otherwise, I want to say thank you for this software, very freeing from the processor standpoint and I will be donating very soon with some funds.

**Comment by NicolasDorier** [comment]
In general I try to keep up to date. But I can't guarantee it.
For this reason, if you need better control I advise you to for the btcpayserver-docker repository. All our wizard allow you to point on your own repo instead of ours. But to know about how to do it you have to understand the architecture.

Take a look at this video where I explain it:

https://vimeo.com/316630434

**Comment by NicolasDorier** [comment]
The fork way is how https://btcpayjungle.com/ did. They have their own version of btcpayserver, and merge upstream time to time manually. But they control their own stack.
