### ISSUE TITLE
BTCPay Tor Support Issues

### ISSUE THREAD

**Issue by larry-beck** [btcpayserver/btcpayserver-docker#119]
So I added Tor as follows, but I have a quick question, how would I remove Tor if I wanted to?

export BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-tor"
. btcpay-setup.sh -i

**Comment by larry-beck** [comment]
BTW, the reason for asking this is that since I deployed Tor support in BTCPay on Docker on my Raspi, I get the following errors when trying to install or update basic applications. This did not happen before installing BTCPay Tor option and nothing else has changed as this is a production system.

1. Router Behind Router Detected when trying to simply use wget and download a page from my public website.
2. sudo apt-get update
Hit:1 https://download.docker.com/linux/raspbian stretch InRelease                                                                           
Hit:2 https://deb.torproject.org/torproject.org stretch InRelease                                                                                                       
Get:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease                                                                                                        
Err:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease                         
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:4 http://archive.raspberrypi.org/debian stretch InRelease                            
Err:4 http://archive.raspberrypi.org/debian stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Fetched 5,184 B in 9s (524 B/s)
Reading package lists... Done
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Failed to fetch http://archive.raspberrypi.org/debian/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by NicolasDorier** [comment]
@larry-beck just remove opt-add-tor from your `BTCPAYGEN_ADDITIONAL_FRAGMENTS` environment variable.

**Comment by NicolasDorier** [comment]
For the error during update, I doubt it has anything to do with Tor

**Comment by larry-beck** [comment]
seems very strange that it all started after Tor install, the rest of the network is working fine, meaning my laptop can get out through same router to Internet with no issues, etc. I will remove and see if that resolves these issues and report back here just in case either way.

**Comment by larry-beck** [comment]
resolved, no issues with BTCPay as you said, something weird with AT&T, resolved now. thanks!

**Comment by NicolasDorier** [comment]
Explanation: They saw you use Tor and decided to wiretap you, but fucked up. :p
