### ISSUE TITLE
Wallet balance 0 after update

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver-docker#120]
I ran  `btcpay-update.sh` command and now my wallet balance is 0! 

Channels and channelbalance seems unaffected. 

* version of `lnd`

"version": "0.5.2-beta commit=basedon-v0.5.2-beta-3-dirty",

* which operating system (`uname -a` on *Nix)

Linux BTCPayServerVM 4.15.0-1019-azure #19-Ubuntu SMP Thu Jul 26 19:54:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

I use https://github.com/btcpayserver/btcpayserver-docker

And just ran the update command,  `btcpay-update.sh`

**Comment by NicolasDorier** [comment]
hey, can you get some logs of LND?

**Comment by NicolasDorier** [comment]
I know that LND between 0.5.0 and 0.5.1 decided that it was a good idea to do a full rescan.
But because BTCPay does not keep all the blocks, this may effectively mean it rescans and your balance go to zero.

We wrote a blog post long ago on it.

https://medium.com/@BtcpayServer/warning-about-update-to-lnd-0-5-1-f15a58dd1c0e

You can recover it, but it will be hackish and likely require a resync of your bitcoin node.

I need to know the logs of LND

**Comment by hakonamatata** [comment]
> 
> 
> hey, can you get some logs of LND?

I can give you all the logs, but not sure how I find and copy the log files from docker to my home directory?

**Comment by NicolasDorier** [comment]
hey @hakonamatata can you send that to the LND repository?

If they give you a solution which involve a full resync and that requires a full node, come back here I will guide you to do this in BTCPay. (Please reopen this issue if that's the case)

**Comment by NicolasDorier** [comment]
Also, please link this issue to the issue you post on the LND repo so I can follow what is going on.

**Comment by hakonamatata** [comment]
> hey @hakonamatata can you send that to the LND repository? (https://github.com/lightningnetwork/lnd)
> 
> If they give you a solution which involve a full resync and that requires a full node, come back here I will guide you to do this in BTCPay. (Please reopen this issue if that's the case)

I already created an issue in the lnd repo, they told me to post it here and closed the issue...

**Comment by NicolasDorier** [comment]
Please can you ask them what we must do? Because I have no idea.

**Comment by NicolasDorier** [comment]
@hakonamatata I reopened issue on https://github.com/lightningnetwork/lnd/issues/2912

**Comment by NicolasDorier** [comment]
@hakonamatata you got it back?

**Comment by hakonamatata** [comment]
> 
> 
> @hakonamatata you got it back?

After some days my balance went back to not zero. Not sure what happened.
