### ISSUE TITLE
Provide pregenerated docker-compose

### ISSUE THREAD

**Issue by Spass1966** [btcpayserver/btcpayserver-docker#128]
Synology NAS users can't make use of the setup script plus there are some quirks that are best left for the Synology's own stack to deploy, like a letsencrypt cert.

Is there an example available of a self-contained docker-compose we can populate with environment variables and deploy ourselves?

**Comment by NicolasDorier** [comment]
Setup the `BTCPAYGEN_` variables, run `build.sh` and copy/paste/customize the resulting `.env` and `docker-compose.generated.yml` file. Though you will lose the Update button feature.

I advise you against letting Synology using its own stack if you don't need it, this is needless pain.

**Comment by NicolasDorier** [comment]
BTCPayServer NGinx is doing way more than just let's encrypt, it also route requests to LND or other plugins. If you want your own nginx, you will  have to configure it yourself, and it is not easy.

**Comment by Spass1966** [comment]
Closing this as solved, since it requires just a few lines altered for a copy/paste solution. Thank you!
