### ISSUE TITLE
customize the generated docker-compose file outside prune mode

### ISSUE THREAD

**Issue by nsollazzo** [btcpayserver/btcpayserver-docker#133]
hi everyone, I'm setting up my btcpayserver on a new vps but I have a two containers, nextcloud and a website, on another vps that I want to move to the new server in order to close the old one.
My question is: is there a way to integrate this two services into the docker-compose file? 

I saw the section [how-can-i-customize-the-generated-docker-compose-file](https://github.com/btcpayserver/btcpayserver-docker#how-can-i-customize-the-generated-docker-compose-file) but I saw only prune option for btc and the other cryptos, can i use that to add and modify services?

thank you everyone

**Comment by NicolasDorier** [comment]
@nsollazzo yes you can add services. Just follow the example of the other fragments we use in the btcpay server project.

**Comment by nsollazzo** [comment]
AWESOME! thank you very much, you guys are the best!
