### ISSUE TITLE
[LND] recover wallet from seed and channels.backup

### ISSUE THREAD

**Issue by nsollazzo** [btcpayserver/btcpayserver-docker#138]
### Background

I was not able to recover the funds from seed + channels.backup

### Your environment

* version of `lnd` Version: **0.6.1-beta commit=basedon-v0.6.1-beta-dirty**
* which operating system (`uname -a` on *Nix): **Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**
* version of `btcd`, `bitcoind`, or other backend: **Bitcoin Core 0.18.0**
* any other relevant environment details: **running btcpay server with docker containers**

### Steps to reproduce

I followed the [recovering-using-scbs](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#recovering-using-scbs) guide

### Expected behaviour

recover the wallet with the channels and the funds

### Actual behaviour
`[lncli] Wallet is already unlocked`

reference : [cannot recover wallet through channels.backup](https://github.com/lightningnetwork/lnd/issues/3102#issue-446588673)

**Comment by NicolasDorier** [comment]
I think channel backup require the seed backup, which BTCPay does not give to the user.

**Comment by nsollazzo** [comment]
I have the seed and the channels.backup file from another node

**Comment by NicolasDorier** [comment]
Sadly, I personally don't know a way to recover your LND channels with the BTCPay Server node which would not break your setup when you will make an update.

I would just restore the backup on a LND node not on BTCPay, close all channel, withdraw all the money, then send the money to the LND node on btcpay.

**Comment by nsollazzo** [comment]
thank you very much, I'll try that

**Comment by bereska** [comment]
@NicolasDorier @nsollazzo I take it that recovering LND channels from other nodes is still NOT possible on BTCPay Server node, right?

**Comment by NicolasDorier** [comment]
It is possible now, but if you have old install you need to close all channels, get back all your money and follow https://blog.btcpayserver.org/btcpay-lnd-migration/

**Comment by bereska** [comment]
the problem is the old install crashed. It was all manual tech stack (bitcoind, lnd, .NET. nbexplorer, btcpayserver, rtl). It was running great and I enjoined learning how all the moving parts worked). It was not a software but a hardware failure (SD card). But I had an automated SCB per Alex Bosworth's guide https://gist.github.com/alexbosworth/2c5e185aedbdac45a03655b709e255a3.
So now all I have is **the latest channel.backup file and seed** from that old manual install without a physical and ssh access meaning it is NOT a migration restore scenario but a **crash restore scenario**.

**Comment by NicolasDorier** [comment]
@bereska I see. There is no easy way to restore via BTCPay. I guess your best guess is to restore via a manual install again and just following normal LND procedure.

**Comment by bereska** [comment]
@NicolasDorier ok, thank you, got it
what about BTCPay Server lnd backup plan in case of loss, theft, crash?
I know the seed is created at start up and can/should be backed up immediately and the channel.backup is updated on change in `/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/data/chain/bitcoin/mainnet/channel.backup`.
But is is up to users now to automate channel.backup file backup to a remote storage/server?

**Comment by bereska** [comment]
@NicolasDorier I take it `backup.sh` backs up the the whole `/var/lib/docker/volumes` and must be run by users manually now. It's great for a general restore/migration but it doesn't save latest channels state in case of a sudden loss/crash. Please correct me if I'm missing something here.
I took care of this issue on my other (non-BTCPay docker) lnd nodes by a simple script coping channel.backup _on change_ to a remote server/cloud storage.
Please let me if this might useful for BTCPay Server user implementation.

**Comment by NicolasDorier** [comment]
@bereska yes, it is up to the user to manage his own LND service. Some LND wallets might help. (I never backed up my lightning so I can't really help you)

**Comment by bereska** [comment]
@NicolasDorier oh, no, I don't need help this time). I was actually offering mine).
my custom script is based on inotify, rsync and/or rclone to monitor and copy channel.backup file on change to own remote servers and/or popular cloud storages.
pretty much anyone with some linux command line skills can set it up on his/her BTCPay Server installation but it would be great to have a GUI implementation for ordinary users at least .
In my opinion BTCPay Server users (merchants) are vulnerable to losing their funds in lnd channels in case of crash without this feature.
please let me now if you find this useful

**Comment by NicolasDorier** [comment]
yes, @bereska this can be useful as a tool in the btcpayserver-docker repo!

**Comment by bereska** [comment]
@NicolasDorier ok, great! let me test it on my newly built btcpay4all.duckdns.org and contribute to the btcpayserver-docker repo.
I'm proud to be a part of it)
