### ISSUE TITLE
LND fails to start because of missing address manager namespace

### ISSUE THREAD

**Issue by apotdevin** [btcpayserver/btcpayserver-docker#140]
Have a clean install of btcpayserver-docker and lnd is failing to start. Looking into the logs its showing 'unable to create wallet controller: missing address manager namespace'

![image](https://user-images.githubusercontent.com/31413433/59087717-c9809600-8905-11e9-85a0-b4b136c6b6b0.png)

All other containers seem to be working fine
![image](https://user-images.githubusercontent.com/31413433/59087767-f5038080-8905-11e9-9c0c-bfd967882a39.png)

**Comment by NicolasDorier** [comment]
what fresh hell is this error... Are you restoring a old wallet or something like this?

**Comment by NicolasDorier** [comment]
On mainnet fully synched?

**Comment by apotdevin** [comment]
Nope, nothing. Fresh new install of btcpay-server on digitalocean

**Comment by apotdevin** [comment]
Yes mainnet seems to be fully synced. At least I hope so since it synced for the last 5 days

**Comment by apotdevin** [comment]
Just checked and it is fully synced
![image](https://user-images.githubusercontent.com/31413433/59090559-5ed35880-890d-11e9-9f94-d221087465c4.png)

**Comment by NicolasDorier** [comment]
Ok try to trash lnd:
```bash
btcpay-down.sh
rm -rf /var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data
mkdir /var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data
btcpay-up.sh
```

**Comment by apotdevin** [comment]
Perfect, that seemed to solve it. Thanks
