### ISSUE TITLE
[question] Running with docker on machine where ports 80 and 443 aren’t free (without Tor)

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#141]
I want to run BTCPay server on a machine that already runs a lot of docker containers and where ports 80 and 443 are already in use by an existing Nginx that I want to use to proxy/forward the traffic.

This Nginx forwards the traffic for all docker containers on the system.

How best to proceed?

**Comment by NicolasDorier** [comment]
There is an option to run BTCPay without the NGINX server.

However, I advise you to not do it.

BTCpay need port 80 and 443 with NGINX because Let's encrypt (to get your certificate) require port 80 and 443.
Not only this, the NGINX in BTCPay is used heavily to redirect requests to the services inside the container. (The configuration is dynamic, depending of the services you use)

See https://vimeo.com/316630434 to understand better what it does.

**Comment by woutersamaey** [comment]
I don’t mind using the built-in Nginx and having 2x Nginx. Only thing is mapping it on different ports. 

Let’s encrypt is already handled by my first Nginx and I’m terminating SSL there. 

I have done this in the past with BTC Pay Server and got it to work (the offloading).

So only 1 thing remains, how to change the ports on the built-in Nginx

**Comment by NicolasDorier** [comment]
@woutersamaey the easier I see is that you fork btcpayserver-docker and you change the port mapping in `nginx.tmpl`.

The only downside is that you will need to rebase your changes on top of btcpayserver/btcpayserver-docker when you want to update. (though if you are lazy, you can just hack btcpay-update.sh to do it for your automatically)

**Comment by woutersamaey** [comment]
Okay, I can see where you’re going with this. Any chance the ports can be configured using an environment variable? It would need to be passed from the bash script to the generation of the Nginx confit, but I’m not familiar with the template system to do it myself.

Willing to give it a shot though...

**Comment by NicolasDorier** [comment]
@woutersamaey I think it can be good idea. Can you do a PR?

The template system should not scare you (see https://vimeo.com/316630434), it is actually very dumb.

**Comment by NicolasDorier** [comment]
@woutersamaey note that you don't have to change the `.tmpl` of the nginx in your case. What you want to change is the port mapping in the `nginx.yml` (docker compose file), such that port 80 in container map to some other port on the host. 

This is super easy.

**Comment by woutersamaey** [comment]
@NicolasDorier I've created the PR. Like you said. Super easy.
