### ISSUE TITLE
Refactor `btcpay-setup.sh` and use a single $OS var for installation and setup per OS?

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#153]
Currently `btcpay-setup.sh` does 2 things:
- Installs dependancies like docker
- Configure and create the containers

A big part of the installation is OS dependant and relies on nested IF-conditions that is different for each OS. This code is not commented, so also not good.

As you may know, I'm looking into making this work on Mac OS X and without "root", since Mac OS rarely works this way. Most Mac users don't even have root enabled or don't know how to do it. It's frowned upon.

I can insert all the needed code to setup on Mac, but the OS specific stuff is getting ugly.

So my idea is this:
- Can we create a var `$OS` and base all logic on that? This can get a bit tricky for OS that are similar.
- Can we split `btcpay-setup.sh` in 2 and have a new file `btcpay-install-dependancies.sh`? Root access would only be needed for this new file, or if you run it without root, show manual error steps like: "Docker is not installed, please install it or run `btcpay-install-dependancies.sh` as root to have it installed automatically".

Just an idea I want to discuss before making too many changes...

**Comment by NicolasDorier** [comment]
@woutersamaey I added recently `btcpay-setup.sh --install-only` to only install dependencies and images without starting it. Is it not enough?

**Comment by woutersamaey** [comment]
OK, I must have overlooked that.

What about the $OS variable refactoring? I need to check for Mac OS a couple of times in the code, and prefer not to copy paste this fragment every time...
```
if [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
fi
```
Maybe it isn't so bad, but noticed the other OS dependant code and thought that could also benefit from having a single $OS variable.

Or do you see a downside to this?

**Comment by NicolasDorier** [comment]
I really prefer we don't do huge refactoring. This code is tricky to get right, but quite stable since its inception. Also a bug in this code might lock out someone out of his BTCPay. (guiding noobs on how to SSH into their instance to fix the situation is not fun)

So it depends on how intrusive it it.

**Comment by woutersamaey** [comment]
Good point. Will stick to the minimum and suggest a PR when ready.
