### ISSUE TITLE
[question] Why was PostgreSQL chosen?

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#154]
Why was PostgreSQL chosen over (for example) MySQL?

Is BTCPay Server build in a DB agnostic fashion? Would it allow for different DBs?

Just asking out of curiosity.

**Comment by NicolasDorier** [comment]
No reason. I noticed as well postgresql need less RAM than MySQL. (usefull for raspberri deployment)
Postgres, nobody ever complained.

While we say we support MySQL, we don't test it so there might have bug. (I think there is one actually)

We rely on entity framework which is an ORM which abstract the DB. (We support Posgres, SQlite, Mysql)
As all ORM, there is often some leaky abstraction which mean that even if in theory it should work everywhere, in practice, something will not work.

**Comment by Kukks** [comment]
The entity framework migration features is not the best. SQLite for example is highly restricted and most migration features are not supported and require manual fixes *if* we notice them( they are auto-generated files). MySQL seems to have some different default schemas from postgres which have caused some inconsistencies with table column data (and crashed some installs) in the past.
