### ISSUE TITLE
[suggestion] Installation wizard

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#155]
Can we create an installation wizard that just asks the user a number of questions (interactive) instead of using the environment variables `export XXX=YYY` stuff?

I'm guessing this will make things a LOT easier for newbies.

If anyone wants to help me, I'll focus on this after finishing support for Mac OS (getting close).

**Comment by JeffVandrewJr** [comment]
I believe @kukks has been working on something in this vein.

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver-installer

**Comment by NicolasDorier** [comment]
I want to make it better later with like 
```bash
BTCPAY_INSTALLER=1
. btcpay-setup.sh -i
```

And this would show the installer.

But I need time for that.

**Comment by woutersamaey** [comment]
Honestly I was thinking something much simpler like a bash script that asks a number of questions and uses the answers to fill the env vars on first run. After this, the regular setup script can take if from here.

Shouldn't be too hard and doable in a few hours.

The installer project is a .NET program and much more elaborate, isn't it?

**Comment by Kukks** [comment]
It's very similar to that, except it has a whole UI to it, generates a one-line bash script, ssh into the machine and executes it.  
I'll be picking it up soon again to:
* Make it stable and work well
* Allows you to simply copy the bash script instead of having it require ssh details
* Allow you to edit an existing install
* Allow it to be bootstrapped by the docker installer repo so that a new install just pops up for you

**Comment by Amacruz** [comment]
I started on a bash script to do a basic installation! Keeps failing on me with, "BTCPAYGEN_CRYPTO1 cannot be blank". Reached out to @Kukks too to get something similar done for my project. Not a developer but would love to help in anyway I can!

**Comment by phptek** [comment]
I was thinking something similar, but with the use of a simple JSON file which could be parsed and its values passed to docker-compose.generated.yml (and anywhere else they're needed).

**Comment by britttttk** [comment]
@phptek does this https://docs.btcpayserver.org/Configurator/ work for you?

**Comment by phptek** [comment]
@britttttk oh this looks awesome. I can run this from the CLI too. I'm thinking some more comprehensive docs over and above the existing nginx snippet on the FAQ page - for customization in a Docker context for those of us with a little more Docker experience. I'm happy to start one off and modify the existing FAQ question to eventually point to it.
