### ISSUE TITLE
[question] If I want to use Tor and get an .onion address, do I still need to configure BTCPAY_HOST ?

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#157]
If I want to use Tor and get an .onion address, do I still need to configure BTCPAY_HOST ?

Have no idea how to get an .onion address really.

Just want to get started fast (for testing) and don't want to setup DNS or port forwarding.

**Comment by woutersamaey** [comment]
Never mind. I found the onion link in the header of the site.
Would've loved to see the onion address being printed on screen at the end of `btcpay-setup.sh` or `btcpay-up.sh`.

Something like: You BTCPay Server is now starting. To access it, browse to https://XXX

Any thoughts?

**Comment by Kukks** [comment]
Some users have been setting the host to BtcPay.local for example ( and then you edit the hosts file to resolve it or configure mdns)

I think the main issue this is.not the case is because the hidden services are created once the containers load and start. You actually have onion addresses for your ln node, BtcPay, woocommerce, etc

**Comment by woutersamaey** [comment]
No chance we can add a delay and print the addresses after a few seconds? In that case I’d print all addresses for all containers, so the user gets a complete overview of what just launched. Addresses on Tor and/or regular hostname/ports

**Comment by Kukks** [comment]
@norm posted this on the chat yesterday actually:  `Nevermind, in case anyone else asks. To see what your .onion address if you cannot get to your clear net domain name.  "tail /var/lib/docker/volumes/generated_tor_servicesdir/_data/BTCPayServer/hostname"`

**Comment by woutersamaey** [comment]
Should also put this in the docs if not there yet.

**Comment by pavlenex** [comment]
@woutersamaey Good idea opened an issue in docs repo.
