### ISSUE TITLE
Allow all domains pointing to server to forward to btcpay by default

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-docker#158]
This would allow us to have multiple domains pointing to specific apps without too much configuration on this repo

**Comment by NicolasDorier** [comment]
You can do with `REVERSEPROXY_DEFAULT_HOST`.

Should not do by default, else a bot can manage to easily scan btcpayserver instances on the web.

**Comment by Kukks** [comment]
what do you set `REVERSEPROXY_DEFAULT_HOST`to? 
`btcpay`?

**Comment by NicolasDorier** [comment]
@Kukks no, to the default public domain (either tor or BTCPAY_HOST or WOOCOMMERCE_HOST)

**Comment by woutersamaey** [comment]
Is this feature included in the docs?

**Comment by NicolasDorier** [comment]
They are in the readme on https://github.com/btcpayserver/btcpayserver-docker

**Comment by Kukks** [comment]
Just use `BTCPAY_ADDITIONAL_HOSTS`

**Comment by danielcharrua** [comment]
Hey @Kukks @NicolasDorier @woutersamaey! is there a way to use different domain/subdomain per store?

Or maybe use two domains on the same BTCPay instance and different stores use them?

Thank you.
