### ISSUE TITLE
c-lightning - cant change lightning node alias

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#162]
I changed the server align in the .env file, and it is now:

`LIGHTNING_ALIAS=StippyGcpCLN`

But it still displays even after reboots and upgrades and running `btcpay-setup -i` as node: `02aa167aae`  (the first characters of the public node ID).

I would like to change it, but cannot work out how.  Any advice?

(the LND version, changing the env file worked fine).

**Comment by NicolasDorier** [comment]
can you do 

```
cat $BTCPAY_ENV_FILE
```

**Comment by maltokyo** [comment]
Here we go

**Comment by maltokyo** [comment]
Sorry. Didnt work pasting text on phone. Here it is:
https://imgur.com/gallery/JcCQoiI

**Comment by NicolasDorier** [comment]
@maltokyo did you do exactly this:

```
LIGHTNING_ALIAS=StippyGcpCLN
. btcpay-setup.sh -i
```
and not editing `.env` by hand?

**Comment by maltokyo** [comment]
Yes, I did edit by hand and ran setup, I thought that would be ok, but clearly not.  Anyway, I did as you said above, but with "export" before the alias, and it worked.  Thank you, as always!
