### ISSUE TITLE
How to get Mnemonic seed words for on-chain wallet

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#167]
@NicolasDorier maybe I missed a step, but I don’t think I was ever given opportunity to get a seed mnemonic (24 words etc) for my lnd node on-chain wallet? How can I get this, or how to recover the wallet in case of disaster? Thank you.

**Comment by pavlenex** [comment]
You can't get your seed we use `noseedbackup`
Read [this](https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#where-can-i-find-recovery-seed-backup-for-my-lightning-network-wallet-in-btcpay-server).

**Comment by maltokyo** [comment]
Thank you, if I wanted to change that, and get it for myself, which defaults would I need to change?  I would like to have a backup of my on-chain funds so that at least I could restore these in case of a disaster in another wallet.

**Comment by NicolasDorier** [comment]
@maltokyo you need to try for yourself, but check about the "docker custom fragment" in the README.
Adding one fragment with `noseedbackup=0` should work. But it will requires you to use command line everytimes you restart your server to unlock lnd.

**Comment by maltokyo** [comment]
ok, thank you @NicolasDorier !

**Comment by Roasbeef** [comment]
Related comment: https://github.com/btcpayserver/btcpayserver-docker/issues/179#issuecomment-518430623

`lnd` gives you this information during initialization, but BTCPay for some reason, doesn't want to surface this to the user so they can secure their funds.

**Comment by maltokyo** [comment]
Closing this issue, as the newer thread with workarounds is here:
https://github.com/btcpayserver/btcpayserver-docker/issues/179
