### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by didiandalucia** [btcpayserver/btcpayserver-docker#180]
Dear, 

I get every time an 502 Bad Gateway and a log view via:

docker ps :
    a384b2a4aa4c        nginx:1.16.0                                            "nginx -g 'daemon of…"   30 minutes ago      Up 30 minutes                   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                nginx

docker logs a384b2a4aa4c brings me everytime:

     btcpay.<my-domain> <ip> - - [15/Aug/2019:09:17:04 +0000] "GET / HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362"

The domain btcpay.<my-domain> is correct set to the server and for the server exists a reverse lookup to my domain! 

Can this been, that exist a problem as a 4th level domian? expl. btcpay.subdomain.domain.com?
I get access from the server via ping to all other domains, about the resolvers works via the internal dns-proxy! 

I have test too, to set a variable "RESOLVERS" in the .env file or exported before the setup-script. 
I get the same error equal when I test out from the server with wget and ignore the certificates. 

The btcpayserver-docker runs on an fresh Ubuntu 19.04 - KVM - uname Linux btcpay 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by didiandalucia** [comment]
more information about - I see an error via docker logs "btcpayserver/btcpayserver:1.0.3.127":

info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
fail: Configuration:  sshkeyfilepassword is invalid
fail: Configuration:  Configuration error

I have test to delete the key and pub file in the root/.ssh and have generate as in documentation written include the autorized_keys, but this is the same!

**Comment by didiandalucia** [comment]
I see equal that the "btcpayserver/btcpayserver:1.0.3.127" every time restarting. I cant analyze more inside the docker container! 
I see inside the logs of "btcpayserver/lightning:v0.7.1": 
Waiting /root/.nbxplorer/btc_fully_synched to be created...
network=bitcoin added in /root/.lightning/config
Waiting /root/.nbxplorer/btc_fully_synched to be created...
network=bitcoin added in /root/.lightning/config
Waiting /root/.nbxplorer/btc_fully_synched to be created...

Databases looks nice:

LOG:  database system is shut down
LOG:  database system was shut down at 2019-08-16 05:24:58 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

under bitcoin I see:

2019-08-16T06:10:05Z UpdateTip: new best=00000000000000000026d8c62a8717fbd8123c796a98ae2af0a45472287f58a3 height=567415 version=0x20000000 log2_work=90.44793 tx=392387984 date='2019-03-16T23:47:38Z' progress=0.890024 cache=716.9MiB(5385328txo)

Here I see "DIES" in logs of btcpayserver/docker-gen:0.7.6

2019/08/16 06:10:32 Contents of /usr/local/etc/tor/torrc-2 did not change. Skipping notification ''
2019/08/16 06:11:29 Received event start for container b3c28e965fad
2019/08/16 06:11:31 Received event die for container b3c28e965fad
2019/08/16 06:11:36 Debounce minTimer fired
2019/08/16 06:11:36 Contents of /usr/local/etc/tor/torrc-2 did not change. Skipping notification ''
2019/08/16 06:12:33 Received event start for container b3c28e965fad
2019/08/16 06:12:35 Received event die for container b3c28e965fad

So what is going wrong?

**Comment by NicolasDorier** [comment]
@didiandalucia you use the docker deployement I suppose? 
1. Does browsing to the URL have a valid certificate?
2. Have you set `BTCPAY_HOST=""` to the name of your new domain (and committed via `btcpay-setup.sh -i`)

**Comment by didiandalucia** [comment]
Yes, I cant understand, why the certificate is not correct. This was all set normal via the btcpay-setup- process setted about equal letsencrypt is installed. I will test, that I can certificate new and test it out again. Thanks in first - I come back!

**Comment by didiandalucia** [comment]
Equal btcpay_host is correct set!

<my domain> is set with my domain!

Changing domain from "<my domain>" to "<my domain>"
generated_nbxplorer_1 is up-to-date
generated_lnd_bitcoin_rtl_1 is up-to-date
tor is up-to-date
generated_postgres_1 is up-to-date
btcpayserver_bitcoind is up-to-date
tor-gen is up-to-date
btcpayserver_lnd_bitcoin is up-to-date
generated_btcpayserver_1 is up-to-date
nginx is up-to-date
Starting nginx-gen ... done
letsencrypt-nginx-proxy-companion is up-to-date
When I check again, I get information about wrong certificate and a 2nd test with digicert said, the certificate is not valid:
 
--
Subject | letsencrypt-nginx-proxy-companion
Valid from 14/Aug/2019 to 13/Aug/2020
Issuer | letsencrypt-nginx-proxy-companion

**Comment by didiandalucia** [comment]
I have now change to an other domain, equal I let run the script changedomain.sh and then btcpay-setup -i and a btcpay-restart.sh - Everytime the same: the certificate is not correct!

**Comment by didiandalucia** [comment]
root@btcpay:/opt/btcpayserver-docker# . ./btcpay-setup.sh -i

-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:btcpay.1awww.com
BTCPAY_ADDITIONAL_HOSTS:none.none.com
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:btcpay-tsi.1awww.com
LIBREPATRON_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
BTCPAY_HOST_SSHKEYFILE:/root/.ssh/id_rsa_btcpay
LETSENCRYPT_EMAIL:bracker@1awww.com
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:LND
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-s
BTCPAYGEN_EXCLUDE_FRAGMENTS:
BTCPAY_IMAGE:
ACME_CA_URI:https://acme-v01.api.letsencrypt.org/directory
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/opt/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/opt
BTCPAY_ENV_FILE=/opt/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=/datadir/id_rsa
BTCPAY_SSHTRUSTEDFINGERPRINTS:SHA256:dFaeNDRvCh4cwDrnMoUWzpLZqM6p5uKfKBa5Qh/z3Rk;SHA256:eLkO60ptI4LpdHGp5XAtytNG7amM3jCgnFZ1jTnYrRM;SHA256:uXaboZ9hgqeT74sbIkThLBwRp0SzkNZu+YQ+OI/AuCc;SHA256:X8BAH1vaGvJMjggIMk1+8cAVyAyHfbbsdpF+gd0Yn68;
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:btcpay.1awww.com
----------------------

BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh

BTCPay Server docker-compose parameters saved in /opt/.env

Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:dcb90d09b471417616bc7709e13caebcb40e17be6534253ba8ba08c7adf235e9
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
With fragments:
        nginx-https
        nginx
        btcpayserver-nginx
        btcpayserver
        opt-add-tor
        nbxplorer
        postgres
        bitcoin
        bitcoin-lnd
        opt-save-storage-s
Generated /app/Generated/pull-images.sh
Generated /app/Generated/save-images.sh
Generated /app/Generated/docker-compose.generated.yml

Adding btcpayserver.service to systemd
BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service

BTCPay Server starting... this can take 5 to 10 minutes...
BTCPay Server started
generated_postgres_1 is up-to-date
tor is up-to-date
generated_nbxplorer_1 is up-to-date
generated_lnd_bitcoin_rtl_1 is up-to-date
tor-gen is up-to-date
btcpayserver_bitcoind is up-to-date
btcpayserver_lnd_bitcoin is up-to-date
generated_btcpayserver_1 is up-to-date
nginx is up-to-date
nginx-gen is up-to-date
letsencrypt-nginx-proxy-companion is up-to-date
Copying /datadir/id_rsa to BTCPayServer container
Installed bitcoin-cli.sh to /usr/local/bin: Command line for your Bitcoin instance
Installed bitcoin-lncli.sh to /usr/local/bin: Command line for your Bitcoin LND instance
Installed btcpay-clean.sh to /usr/local/bin: Command line for deleting old unused docker images
Installed btcpay-down.sh to /usr/local/bin: Command line for stopping all services related to BTCPay Server
Installed btcpay-restart.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-setup.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-up.sh to /usr/local/bin: Command line for starting all services related to BTCPay Server
Installed btcpay-update.sh to /usr/local/bin: Command line for updating your BTCPay Server to the latest commit of this repository
Installed changedomain.sh to /usr/local/bin: Command line for changing the external domain of your BTCPay Server
root@btcpay:/opt/btcpayserver-docker#

**Comment by didiandalucia** [comment]
root@btcpay:/opt/btcpayserver-docker# . ./btcpay-setup.sh -i

-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:btcpay.1awww.com
BTCPAY_ADDITIONAL_HOSTS:none.none.com
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:btcpay-tsi.1awww.com
LIBREPATRON_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
BTCPAY_HOST_SSHKEYFILE:/root/.ssh/id_rsa_btcpay
LETSENCRYPT_EMAIL:mail-address deleted
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:LND
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-s
BTCPAYGEN_EXCLUDE_FRAGMENTS:
BTCPAY_IMAGE:
ACME_CA_URI:https://acme-v01.api.letsencrypt.org/directory
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/opt/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/opt
BTCPAY_ENV_FILE=/opt/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=/datadir/id_rsa
BTCPAY_SSHTRUSTEDFINGERPRINTS:SHA256:here deleted !!!
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:btcpay.1awww.com
----------------------

BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh

BTCPay Server docker-compose parameters saved in /opt/.env

Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: here deleted !!!
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
With fragments:
        nginx-https
        nginx
        btcpayserver-nginx
        btcpayserver
        opt-add-tor
        nbxplorer
        postgres
        bitcoin
        bitcoin-lnd
        opt-save-storage-s
Generated /app/Generated/pull-images.sh
Generated /app/Generated/save-images.sh
Generated /app/Generated/docker-compose.generated.yml

Adding btcpayserver.service to systemd
BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service

BTCPay Server starting... this can take 5 to 10 minutes...
BTCPay Server started
generated_postgres_1 is up-to-date
tor is up-to-date
generated_nbxplorer_1 is up-to-date
generated_lnd_bitcoin_rtl_1 is up-to-date
tor-gen is up-to-date
btcpayserver_bitcoind is up-to-date
btcpayserver_lnd_bitcoin is up-to-date
generated_btcpayserver_1 is up-to-date
nginx is up-to-date
nginx-gen is up-to-date
letsencrypt-nginx-proxy-companion is up-to-date
Copying /datadir/id_rsa to BTCPayServer container
Installed bitcoin-cli.sh to /usr/local/bin: Command line for your Bitcoin instance
Installed bitcoin-lncli.sh to /usr/local/bin: Command line for your Bitcoin LND instance
Installed btcpay-clean.sh to /usr/local/bin: Command line for deleting old unused docker images
Installed btcpay-down.sh to /usr/local/bin: Command line for stopping all services related to BTCPay Server
Installed btcpay-restart.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-setup.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-up.sh to /usr/local/bin: Command line for starting all services related to BTCPay Server
Installed btcpay-update.sh to /usr/local/bin: Command line for updating your BTCPay Server to the latest commit of this repository
Installed changedomain.sh to /usr/local/bin: Command line for changing the external domain of your BTCPay Server
root@btcpay:/opt/btcpayserver-docker#

**Comment by didiandalucia** [comment]
So, I have resolved one problem about the settings for more as one domain! When the 2nd domain not exists, the certificate will not been created! So now I have the same error 502 error Bad Gateway! 

Why their is not a nice check script or a good documentation exists?

I will look that I found other problems!

**Comment by didiandalucia** [comment]
in logs for btcpayserver/btcpayerserver: 
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
fail: Configuration:  sshkeyfilepassword is invalid
fail: Configuration:  Configuration error

Where is saved the password for the sshkey? I have not defined a key?!

**Comment by NicolasDorier** [comment]
@didiandalucia your stuff seems correctly configured. (ignore the ssh stuff, this is not important)

your domain `none.none.com` does not seems to be configured to point to your server.

**Comment by NicolasDorier** [comment]
@didiandalucia two problem:

1. The `none.none.com` is not pointing to your server
2. Remove your SSH setting from BTCPay

```bash
BTCPAY_ADDITIONAL_HOSTS=""
BTCPAY_HOST_SSHKEYFILE=""
. btcpay-setup.sh
```

**Comment by didiandalucia** [comment]
Many thanks thats was.

Yesterday I have remove BTCPAY_ADDITIONAL_HOSTS but not BTCPAY_HOST_SSHKEYFILE. Now with the 2 new settings it´s running now perfect!

Many thanks - this issue can been close!
