### ISSUE TITLE
Question: Can I use BTCPay Server's Nginx docker as a reverse proxy for other docker images (wordpress etc)?

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#186]
I know this is unrelated to the actual software, but I didn't know where to ask.  Just delete if this is not appropriate here.

I would like to run a few other docker images (WordPress etc) and want just one port80,443 frontend, which is the role that currently BTCPay Server's Nginx docker plays.

Through docker-fragments etc, would it be possible to use this Nginx docker for all my reverse proxy needs?  Any small hints on how to do that would be appreciated.  I will set up, test and document how it is done if someone guides me in the right direction.

I would propose I document it on https://www.reddit.com/r/btcPayServer

Thank you for your help

**Comment by RobertHosking** [comment]
This is commonly done with a single reverse proxy/web server on the host machine (not in a container). You could use Nginx, Apache, or traefik. Each of your containerized services would have its own port exposed to the host machine and you would configure your reverse proxy to send traffic to that port based on some criteria (usually a subdomain).

Example: 
Run a wordpress container on port 8080 and a btcpayserver container on port 9000.
Configure Apache to reverse proxy wordpress.mydomain.com to port 8080 and btcpay.mydomain.com to port 9000.

This is how I run over a dozen containers on my server. Alas, I cannot get BTCPayServer to comply. See issue #184

**Comment by maltokyo** [comment]
Interesting. I never thought of setting up nginx directly in the host machine. My mind is so dockerized these days it didn’t even occur to me. I’ll watch your issue closely too to see how it gets figured out. Thanks for sharing.

**Comment by ndeet** [comment]
@maltokyo running wordpress on BTCPay via fragment is already there and you could use it as a boilerplate, see here https://docs.btcpayserver.org/integrations/woocommerce#deploying-woocommerce-from-btcpay-server

You can check how WP was done, it also adds a separate domain. If this answers your question please close the ticket.

**Comment by maltokyo** [comment]
Thank you @ndeet !
Will try this.  Closing.
