### ISSUE TITLE
BTCPAYGEN_ADDITIONAL_FRAGMENTS: Custom Fragment Generates Duplicate line in docker-compose.generated.yml

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#192]
Not sure if this is the right behaviour, but would like to check.  In an effort to solve this https://github.com/btcpayserver/btcpayserver-docker/issues/179 with my own custom fragment instead of modifying standard files that would be overwritten in an update, I made an additional custom fragment called `opt-z-bitcoin-lnd.custom.yml`, with content:

```
version: "3"

services:
  lnd_bitcoin:
    environment:
      LND_EXTRA_ARGS: |
        noseedbackup=0
```

Then ran this:
`export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-more-memory;opt-z-bitcoin-lnd.custom;opt-txindex"`

and then ran:
`. ./btcpay-setup.sh --install-only`

The resulting section in Generated/docker-compose.generated.yml now looks like this below, with both `noseedbackup=1` and `noseedbackup=0` both included there.  I guess this is not good.  How can I make the custom fragment overwrite the original line, without duplication?

```
  lnd_bitcoin:
    image: btcpayserver/lnd:v0.7.1-beta
    container_name: btcpayserver_lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_EXTERNALIP: ${BTCPAY_ANNOUNCEABLE_HOST}
      LND_PORT: 9735
      LND_ALIAS: ${LIGHTNING_ALIAS}
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_READY_FILE: /root/.nbxplorer/btc_fully_synched
      LND_EXTRA_ARGS: |-
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpcuser=lnd
        bitcoind.rpcpass=afixedpasswordbecauselndsuckswithcookiefile
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        adminmacaroonpath=/data/admin.macaroon
        invoicemacaroonpath=/data/invoice.macaroon
        readonlymacaroonpath=/data/readonly.macaroon
        noseedbackup=1
        notls=1

        tor.active=1
        tor.socks=tor:9050

        noseedbackup=0
```

**Comment by Kukks** [comment]
Yes, this will be an issue for you however there is a workaround:
* Copy contents of `bitcoin-lnd.yml` to your fragment
* modify to your liking
`export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-more-memory;opt-z-bitcoin-lnd.custom;opt-txindex"`
`export BTCPAYGEN_EXCLUDE_FRAGMENTS="bitcoin-lnd"`

This will basically replace the original LND container setup with your own

**Comment by maltokyo** [comment]
Ah, got it!  Thank you.
