### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-docker#193]
Update Information:
- Time4vps article, it seems we keep getting questions about this guide in mattermost. 
    - Possibly remove it?
- Azure stuff: 
    - We probably should suggest LunaNode for easiest/fastest
    - Azure isn't really 1 click deployment :)
- LunaNode: 
    - Approximate Cost (pruned, Bitcoin-only with lightning network): 10 USD per month. (Need to mention this is the cost for LunaNode not Azure, it's not very clear)
- Docker: 
    - Docker automated build link is to ~/nicolasdorier/btcpayserver not the newer ~/btcpayserver/btcpayserver
- Architecture 
    - Someone made those [btcpay docker YT videos](https://youtu.be/japuwmfg0EM) should we link those in here?

**Comment by philippgille** [comment]
I would add that some environment variable descriptions don't match the ones mentioned in `btcpayserver-setup.sh`. For example, the README contains:

> `BTCPAYGEN_LIGHTNING`: Lightning network implementation to use (eg. `clightning`, `(empty)`)

While the `btcpayserver-setup.sh` contains:

```bash
BTCPAYGEN_LIGHTNING: Lightning network implementation to use (eg. clightning, lnd, none)
```
See https://github.com/btcpayserver/btcpayserver-docker/blob/face6968532ed1bf407046c65138fb6b14c39a4c/btcpay-setup.sh#L94

This might lead to people reading the README to think that they can only use c-lightning and not lnd.
