### ISSUE TITLE
LND Channel Backup Folder shown wrongly in RTL

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#196]
This is for those people using the workaround to turn noseedbackup to "0" as in https://github.com/btcpayserver/btcpayserver-docker/issues/179, so that the channel backup becomes usable.

RTL shows backup folder with this path.  The file is not stored in any path like that, as far as I can tell.   It is in the docker volume with a completely different path, i.e. `/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/data/chain/bitcoin/mainnet`

Wrongly displayed path:
![image](https://user-images.githubusercontent.com/1388507/64472518-04da6d00-d160-11e9-8b7b-89f6a35d1a67.png)

**Comment by Kukks** [comment]
Ah, this is how docker works, RTL cannot show anything differently because for it `/root/backup` is correct.  `/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/data/chain/bitcoin/mainnet` is only on the host machine

**Comment by Kukks** [comment]
I'm afraid it cannot be fixed without some hacky workaround in RTL

**Comment by maltokyo** [comment]
Thank you. That’s fine. Was just leasing it here in case other people find
the info useful.

**Comment by NicolasDorier** [comment]
That said, without the seed, static backup are useless

**Comment by maltokyo** [comment]
Yes as in my first comment. I said it’s only for the people using my
workaround to get the seed first.
