### ISSUE TITLE
How to get monero fragment running?

### ISSUE THREAD

**Issue by wallopthecat** [btcpayserver/btcpayserver-docker#204]
generated_btcpayserver_1 logs
```
fail: Configuration:  Invalid chains "XMR"
fail: Configuration:  Configuration error
```
New to the ecosystem so sorry if I missed something. 

Tried checking the config file referenced but it seems to be all commented
```
.../volumes/generated_btcpay_datadir/_data/TestNet/settings.config
### Global settings ###
#network=mainnet

### Server settings ###
#port=23001
#bind=127.0.0.1
#httpscertificatefilepath=devtest.pfx
#httpscertificatefilepassword=toto
```

EDIT: originally thought this was a testnet problem, but replicated on a mainnet install as well:
- Added monero fragment  `export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage;opt-more-memory;monero;`
- `export BTCPAYGEN_CRYPTO3:xmr`
- `. btcpay-setup.sh -i`
- `fail: Configuration:  Invalid chains "XMR"`

An aside, even after resetting my `BTCPAYGEN_ADDITIONAL_FRAGMENTS` to remove monero, it remained. Had to add `BTCPAYGEN_EXCLUDE_FRAGMENTS="monero"` to revert

**Comment by NicolasDorier** [comment]
Need to release new version of btcpayserver, won't work before we do.

**Comment by jooray** [comment]
There is a new version, is this one new enough?

**Comment by NicolasDorier** [comment]
ping @Kukks

**Comment by Kukks** [comment]
You do not set anything for monero in the additional fragments.

to set up monero you only need to do 
```
export BTCPAYGEN_CRYPTO3=xmr` 
. ./btcpay-setup.sh -i
```

Please note that monero is hardcoded to always run on mainnet, even if you do set the network of btcpay to be testnet.

It also only works on amd64 based hardware(so no raspberry pi) support until someone adds multi-arch to the docker image.

While syncing, the monero node seems to try to use too much CPU and memory than is available and crashes itself internally in the container without killing it. It would be wise to keep an eye out on the progress and to restart the docker container when you see it stuck.

`docker restart btcpayserver_monerod`

**Comment by wallopthecat** [comment]
Even though a fragment is not needed, make sure you don't have monero in excluded fragments (from me testing earlier). `export BTCPAYGEN_EXCLUDE_FRAGMENTS=` to reset it was enough to get going

**Comment by Zaxounette** [comment]
Additional information for setup and deployment, on top of activating the XMR fragment can be found [here](https://github.com/btcpayserver/btcpayserver-doc/issues/815).
