### ISSUE TITLE
AWS - t2.small testing

### ISSUE THREAD

**Issue by ch4ot1c** [btcpayserver/btcpayserver-docker#22]
Hi! I tried to run the server on a t2.small AWS instance (`amzn-ami-hvm-2018.03.0.20180412-x86_64-gp2 (ami-6b8cef13)`), with 200GB of hard drive space.

- The setup worked, even though it wasn't a strictly Ubuntu machine (I had already installed docker, lines like `apt-key` did fail though).
- The logs appeared in `docker logs x` for bitcoind, but were very very slow
- I was able to register and create a store and an app
- The BTCPayServer GUI showed bitcoind to be syncing, with its progress as far as 3%
- But, periodically, bitcoind seems to restart, without even saving block DL progress (because it is crashing instead of being `bitcoin-cli stop`ped. I cannot get into the docker logs to view the cause of failure, but it seems to be making the download process go in circles.
- The cache does sucessfully fill to >200mb, so that doesn't seem to be the problem.

I will try it on an instance with more CPUs maybe?

**Comment by NicolasDorier** [comment]
bitcoind crash has always been happening for me because of RAM issues.

You should prune if you only have 200 GB. You should be able to have the logs

```
docker logs --tail 100 -f btcpayserver_bitcoind
```

**Comment by ch4ot1c** [comment]
Closing; switched my configuration to LunaNode
