### ISSUE TITLE
Service 'btcpayserver' has a link to service 'postgres' which is undefined

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#221]
Upgraded and ran `. ./btcpay-setup.sh -i` today, and get this for the first time.  I didn't change either of these services.

`Service 'btcpayserver' has a link to service 'postgres' which is undefined`

I guess it is because of these lines you added to the fragments docker compose is not working
```
exclusive:
  - pruning
```

```
Generating /app/Generated/docker-compose.generated.yml
The fragments opt-more-memory, opt-txindex can't be used simultaneously (group 'pruning')
Building the fragment failed

.
.
.

BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service

BTCPay Server starting... this can take 5 to 10 minutes...
BTCPay Server started
ERROR: Service 'btcpayserver' has a link to service 'postgres' which is undefined.
```

**Comment by axelaxek** [comment]
yep I can reproduce it too
I guess it's because of the last change added change
[**change**](https://github.com/btcpayserver/btcpayserver-docker/commit/9d4bbcb0f3f661a123c44778c46fb2192243eb36#diff-5e2b13144f8a15980646575fa4ac2963R15) which excludes `postgres` while [this other line](https://github.com/btcpayserver/btcpayserver-docker/commit/9d4bbcb0f3f661a123c44778c46fb2192243eb36#diff-57b23e8390ffb962d319585889caae3dR32) enforces it

**Comment by NicolasDorier** [comment]
Sorry, it was my fault

**Comment by NicolasDorier** [comment]
> Service 'btcpayserver' has a link to service 'postgres' which is undefined

I fixed this bug.

> yep I can reproduce it too
I guess it's because of the last added change which excludes postgres while this other line enforces it.

Can you try again? should not happen. I updated the docker compose builder, so normally this should not happen.

> is there any way to force a previous docker image with the scripts in this repo ?

No but great suggestion.

**Comment by NicolasDorier** [comment]
> No but great suggestion.

Actually you should be able, you just have to checkout the commit before running btcpay-update.

**Comment by NicolasDorier** [comment]
please if it continues, can you comment on https://github.com/btcpayserver/btcpayserver-docker/issues/222

**Comment by NicolasDorier** [comment]
@axelaxek try to remove your hack on with `BTCPAYGEN_ADDITIONAL_FRAGMENTS` and run btcpay-setup again.
