### ISSUE TITLE
Error when running setup

### ISSUE THREAD

**Issue by wendellmva** [btcpayserver/btcpayserver-docker#222]
I ran . ./btcpay-setup.sh -i  
It did a pull of the generator after that I ran into the following issue.

ERROR: Service 'btcpayserver' has a link to service 'postgres' which is undefined
ERROR: Named volume "nbxplorer_datadir:/root/.nbxplorer:rw" is used in service "btcpayserver" but no declaration was found in the volumes section.

I checked postgres service was indeed missing from the generated docker-compose file and so was the nbxplorer service.

I fixed both by adding both services an opt-temp.yml fragment which resolved the issue for now. I am just posting this in case you guys missed something and other folks run into the same problems.

**Comment by NicolasDorier** [comment]
I will check that other people reported it.

**Comment by NicolasDorier** [comment]
can you try `btcpay-update.sh` before ?

**Comment by NicolasDorier** [comment]
And please, share your logs.

**Comment by wendellmva** [comment]
running btcpay-update.sh fixes the problem the errors dissapear.
