### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#224]
In here:
https://github.com/btcpayserver/btcpayserver-docker#generated-docker-compose-

The link to `opt-add-electrumx` fragment is broken.  Error 404.  Maybe it was my fault.  But seems stupid to fix it with PR.  Please, could someone with access fix.

**Comment by Kukks** [comment]
A pr is never stupid, no matter how small it is. I would have accepted and merged if this was a PR by now :)

**Comment by maltokyo** [comment]
OK, here is PR ;) Thank you.

https://github.com/btcpayserver/btcpayserver-docker/pull/225
