### ISSUE TITLE
How to stop BTCPay server starting at boot time? (temporarily)

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#226]
I couldn't find any options.  Any ideas?  (I want to be able to stop the whole thing from starting up temporarily when I am doing maintenance of other stuff on the server).

(In my case, on ubuntu 18.04)

**Comment by NicolasDorier** [comment]
`btcpay-down.sh`

**Comment by maltokyo** [comment]
Ah thanks. I didn’t realize this prevented it loading it again at boot
time. Great.

**Comment by NicolasDorier** [comment]
@maltokyo actually I am not sure. If that does nto work, try

`systemctl stop btcpayserver`

as well.

**Comment by nickyeoman** [comment]
For those that are not familiar with systemctl, here is the correct procedure as root (add sudo as necessary): 

1. (In the correct directory:) :>     ```bash btcpay-down.sh ```
2. (Stop the service) :>                ```systemctl stop btcpayserver```
3. (Remove the service) :>          ```1systemctl disable btcpayserver```

btcpay will no longer start at boot time.
