### ISSUE TITLE
how to keep btcpayserver from crashing my server?

### ISSUE THREAD

**Issue by chovy** [btcpayserver/btcpayserver-docker#228]
After 24 hours load gets up to 198 and server locks up.

I need a way to just have it use like 10% of resources for cpu and ram.

something called `runc init` is destroying the server.

**Comment by NicolasDorier** [comment]
`runc init`? I have no idea what it is.

You can check with `docker stats` what is taking your resources.

**Comment by chovy** [comment]
`docker-compose -f $BTCPAY_DOCKER_COMPOSE ps -q | xargs docker update --cpus ".1"`

This does the job

**Comment by NicolasDorier** [comment]
mmh this seems a hack that will not work when the server restart. You should find out why the CPU takes so much.
