### ISSUE TITLE
Where are the ssl certificates stored?

### ISSUE THREAD

**Issue by PsychedelicHell** [btcpayserver/btcpayserver-docker#239]
I am setting a Nginx reverse proxy on a seperate VM and need the path of the SSL certificates that BTCPay Server generates via lets encrypt during the docker set-up.

Eagerly awaiting your response, cheers!

**Comment by Kukks** [comment]
/var/lib/docker/volumes/generated_nginx_certs/_data

**Comment by PsychedelicHell** [comment]
Got them and copied them to my Nginx VM, thank you. All connected and working!

Happy to say I now have HTTPS on THREE individual machines with TWO different domain names on the ONE public IP!

VM running WordPress/WooCommerce

VM running a WordPress personal blog with BTCPay Server running on the btcpay subdomain.

All self-hosted on a PC in the cupboard.

Thanks for your help.
