### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by BooB2019-glitch** [btcpayserver/btcpayserver-docker#243]
Hi so  I have done everything by the book and still doesn't work for me all look good still can't access using domain if use server's IP I get 503 error in ssl checker I am getting 

nnserver.website resolves to 192.64.119.50
--

  | Server Type: nginx

  | No SSL certificates were found on nnserver.website. Make sure that the name resolves to the correct server and that the SSL port (default is 443) is open on your server's firewall.

have no idea why it is resolving to a different IP ???
I am no expert just trying to learn so am leaving it to experts please advise what am I doing wrong reinstalled VPS many times started from scratch all by the book u can say and no success 

BTCPAY_HOST_SSHAUTHORIZEDKEYS=/root/.ssh/authorized_keys
XDG_SESSION_ID=3
NBITCOIN_NETWORK=mainnet
WOOCOMMERCE_HOST=
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=185.92.25.24 62340 22
BTCPAYGEN_ADDITIONAL_FRAGMENTS=opt-save-storage-xs
BTCPAY_CRYPTOS=btc
BTCPAYGEN_LIGHTNING=lnd
BTCPAY_ADDITIONAL_HOSTS=
OLDPWD=/root/btcpayserver-docker
BTCPAY_SSHKEYFILE=/datadir/host_id_rsa
REVERSEPROXY_DEFAULT_HOST=none
SSH_TTY=/dev/pts/0
REVERSEPROXY_HTTP_PORT=80
USER=root
ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
LIBREPATRON_HOST=
BTCPAY_PROTOCOL=https
BTCPAY_DOCKER_COMPOSE=/root/btcpayserver-docker/Generated/docker-compose.generated.yml
COMPOSE_HTTP_TIMEOUT=180
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
TOR_RELAY_EMAIL=
BTCPAYGEN_OLD_PREGEN=false
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
BTCPAY_ANNOUNCEABLE_HOST=nnserver.website
BTCPAYGEN_EXCLUDE_FRAGMENTS=
PWD=/root/btcpayserver-docker
BTCPAY_SSHTRUSTEDFINGERPRINTS=
LANG=en_US
TOR_RELAY_NICKNAME=
BTCPAY_HOST_SSHKEYFILE=
BTCPAYGEN_REVERSEPROXY=nginx
LIGHTNING_ALIAS=
LETSENCRYPT_EMAIL=
SHLVL=1
HOME=/root
LANGUAGE=en_US:
BTCPAY_BASE_DIRECTORY=/root
BTCPAYGEN_CRYPTO5=
BTCPAYGEN_CRYPTO4=
BTCPAYGEN_CRYPTO7=
BTCPAYGEN_CRYPTO6=
LOGNAME=root
BTCPAYGEN_CRYPTO1=btc
BTCTRANSMUTER_HOST=
SSH_CONNECTION=185.92.25.24 62340 199.188.206.196 22
BTCPAYGEN_CRYPTO3=
BTCPAY_IMAGE=
BTCPAYGEN_CRYPTO2=
BTCPAY_ENV_FILE=/root/.env
XDG_RUNTIME_DIR=/run/user/0
BTCPAYGEN_CRYPTO9=
BTCPAYGEN_CRYPTO8=
BTCPAY_HOST=nnserver.website
BTCPAY_ENABLE_SSH=true
REVERSEPROXY_HTTPS_PORT=443
_=/usr/bin/env

[12:26] [server1.nnserver.website btcpayserver-docker] # btcpay-restart.sh
Restarting letsencrypt-nginx-proxy-companion ... done
Restarting nginx-gen                         ... done
Restarting generated_btcpayserver_1          ... done
Restarting nginx                             ... done
Restarting btcpayserver_lnd_bitcoin          ... done
Restarting btcpayserver_bitcoind             ... done
Restarting tor-gen                           ... done
Restarting tor                               ... done
Restarting generated_nbxplorer_1             ... done
Restarting generated_postgres_1              ... done
Restarting generated_lnd_bitcoin_rtl_1       ... done

**Comment by pavlenex** [comment]
When posting an issue, please **do not ignore the issue template**. You have not provided information about your deployment environment. What kind of deployment is this? What's your actual domain? Are there any logs in `letsencrypt-nginx-proxy-companion` when you do `docker logs letsencrypt-nginx-proxy-companion`

> BTCPAY_HOST_SSHAUTHORIZEDKEYS=/root/.ssh/authorized_keys

This does not say much, please tell us what you're exactly are you using for your btcpay_host

BTCPAY_HOST needs to be an actual domain, not an IP address. If you're using an IP, let's encrypt cannot issue a valid SSL certificate for an IP, and hence the 503.

Get a domain name, put the IP of your server as an a-record and use that domain name as btcpay_host.

**Comment by BooB2019-glitch** [comment]
Hi thanks for the reply pavlenex so it is the below vps  I have SSL active on this domain just haven't installed any certs  yet you think that might be an issue as SSL was already issued for the domain ? yes there is a domain mate ? It is VPS with the domain there's whois guard and premium DNS what else do you need ? just starting to learn so no pro here :) decided to install BTCpay server using docker as that seems to be  the easiest way  don't really know how to help you to help me please guide me 

Status | Online
-- | --
IPv4 Address | 1
IP Address | 199.188.206.196
Virtualization Type | (KVM)
Hostname | server1.nnserver.website
Node | kvmnode13

Operating System | Ubuntu 16.04 LAMP (64-bit)
-- | --
IPv6 Address | 0
Disk Space | 40 GB
Bandwidth | 1000 GB
Memory | 2 GB
Swap | -
 docker logs letsencrypt-nginx-proxy-companion
Info: Rewriting ACME_CA_URI from https://acme-staging.api.letsencrypt.org/directory to https://acme-staging-v02.api.letsencrypt.org/directory
Generating a RSA private key
............++++
..........................................................................................................................................................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one
is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container nginx)...
2019/12/06 12:22:43 Generated '/app/letsencrypt_service_data' from 11 containers
2019/12/06 12:22:43 Running '/app/signal_le_service'
2019/12/06 12:22:43 Watching docker events
2019/12/06 12:22:43 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
/etc/nginx/certs/_test_ /app
Creating/renewal  certificates... ()
You must set at least one -d/--vhost

Debugging tips: -v improves output verbosity. Help is available under --help.
/app
Sleep for 3600s
This is going to take a long time
Info: Diffie-Hellman group creation complete, reloading nginx.
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container nginx)...
2019/12/06 12:26:20 Received signal: terminated
2019/12/06 12:26:20 Received signal: terminated
Info: Rewriting ACME_CA_URI from https://acme-staging.api.letsencrypt.org/directory to https://acme-staging-v02.api.letsencrypt.org/directory
Info: Custom Diffie-Hellman group found, generation skipped.
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container nginx)...
2019/12/06 12:26:32 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2019/12/06 12:26:32 Watching docker events
2019/12/06 12:26:32 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2019/12/06 12:26:33 Received event die for container 4afbf7e17149
/etc/nginx/certs/_test_ /app
Creating/renewal  certificates... ()
2019/12/06 12:26:33 Received event stop for container 4afbf7e17149
2019/12/06 12:26:34 Received event start for container 4afbf7e17149
You must set at least one -d/--vhost

Debugging tips: -v improves output verbosity. Help is available under --help.
/app
Sleep for 3600s
2019/12/06 12:26:49 Debounce minTimer fired
2019/12/06 12:26:49 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'

**Comment by BooB2019-glitch** [comment]
OK lads just took free domain somewhere else and  created A record pointing to my VPS IP and worked fine might be an issue with SSL already issued to the not  successful domain ???
