### ISSUE TITLE
Question: Complete uninstall - what files to clean up outside of docker

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#245]
Apart from pruning the various docker components etc, is the only other file to cleanup for a FULL "purge" of BTCPay Server from a system just this one?

`/etc/systemd/system/btcpayserver.service`

Any other files created?  This would be good to know, after migration from one server to another, for example.

**Comment by NicolasDorier** [comment]
yes @pavlenex  might be good for doc here it is:

**Comment by NicolasDorier** [comment]
The volumes created in `/var/lib/docker/volumes/`.

You can delete them with

```bash
cd "$(dirname "$BTCPAY_ENV_FILE")"
docker-compose -f $BTCPAY_DOCKER_COMPOSE down --v
``

Then you have this file `$BTCPAY_ENV_FILE`, `/etc/systemd/system/btcpayserver.service` and `/etc/profile.d/btcpay-env.sh`

**Comment by maltokyo** [comment]
What about the scripts for btcpay-up.sh etc? And symlinks for everything.

**Comment by maltokyo** [comment]
I don't mind to add the documentation in case you could just list them all
here.

**Comment by NicolasDorier** [comment]
the scripts are in the docker folder you cloned. The symlinks are listed here https://github.com/btcpayserver/btcpayserver-docker/blob/master/helpers.sh#L3

**Comment by maltokyo** [comment]
Added PR @pavlenex @NicolasDorier 
https://github.com/btcpayserver/btcpayserver-doc/pull/403
