### ISSUE TITLE
Error 503 Service Temporarily Unavailable nginx

### ISSUE THREAD

**Issue by vitormilagres1992** [btcpayserver/btcpayserver-docker#247]
Hi everyone, I have followed all these steps over and over on a freshly installed Ubuntu 18.04 Virtual Machine, by following the btcpayserver-docker manual.

I believe it's running well, the /var/lib/docker/volumes/generated_bitcoin_datadir directory is increasing in side to dozens of GB, so I believe the blockchain is being downloaded correctly. The issue I have is when I try to connect to my server, under the following circumstances:

**1 - When I connect via LAN over port 80:** _Error 503 Service Temporarily Unavailable nginx_
**2 - When I connect via WAN over port 80:** _I see the BTCPayServer page, but I can't login over an unsecure network_
**3 - When I connect via LAN over port 443:** _400 Bad Request Error_
**4 - When I connect via WAN over port 443:** _Page does not exist_

iptables is setup to allow all connections, as I am still testing the software for the first time. I'll close unused ports later on once I get this to work.

Port forwarding in my router also setup correctly.

I have been getting this over and over, I have tried to install it 4 times on my Virtual Machine and the results are always the same.

These are the initial variables I have used in the setup, xxxxx is replaced by my own server domain:
export BTCPAY_HOST="xxxxxxx.com"
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_CRYPTO2="ltc"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="clightning"
export BTCPAY_ENABLE_SSH=true

How can I connect to the server?
Thanks for your help!

**Comment by NicolasDorier** [comment]
@vitormilagres1992 so this is probably normal. To prevent bots from finding your scanning your server, by default we requires you to access your server via the `BTCPAY_HOST` domain.

The bad thing is that there is very often problem when a lan try to send a request to a domain point to itself. So over lan, you should add a hosts entry with your BTCPAY_HOST which resolve to the internal IP.

Over WAN, you should use the domain name, not the IP address.

**Comment by NicolasDorier** [comment]
you can try to do 

```
export REVERSEPROXY_DEFAULT_HOST="$BTCPAY_HOST"
. btcpay-setup.sh -i
```

This will allow you to access your btcpayserver without the right domain name (via IP on lan for example)

**Comment by vitormilagres1992** [comment]
Beautiful! Thanks a lot for your help, now it's working for me!

**Comment by NicolasDorier** [comment]
@vitormilagres1992 another possibility, BTCpayServer consider domain name ending by ".local" to be "safe". So if you want to use your local network, you can configure your local dns to resolve `btcpay.local` for example.
