### ISSUE TITLE
How to store block files on a different server (over internet)

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#248]
My VPS is quite small, and costly, so I want to reduce space and move to another smaller one.

How can I set up some share over the internet from web storage or from a drive on home server, and keep main application running with full node on VPS?  any ideas?

I tried this: 
https://github.com/astrada/google-drive-ocamlfuse
It is really cool, and I could mount my Google drive onto the VPS filesystem.  But Bitcoin Core is really fussy it seems about the type of filesystem it uses, and when blocks were stored in the Google drive with a symlink to the docker volume, it would give this error and shutdown (and I am sure the file was readable, with chmod 777 applied)

> 2019-12-26T17:54:00Z Checking all blk files are present...
> : Error loading block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> 2019-12-26T17:54:00Z Unable to open file /home/bitcoin/.bitcoin/blocks/blk00001.dat
> 2019-12-26T17:54:00Z : Error loading block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> 2019-12-26T17:54:00Z Aborted block database rebuild. Exiting.
> 2019-12-26T17:54:00Z Shutdown: In progress...

Thanks!

**Comment by NicolasDorier** [comment]
Most VPS provide external, cheap storage. You should use that.
Synching Bitcoin Core over internet will just not work. Too much IO latency.
