### ISSUE TITLE
Back up account, config files and keep all settings

### ISSUE THREAD

**Issue by vitormilagres1992** [btcpayserver/btcpayserver-docker#249]
Hi, I have installed BTCPayServer using the docker-compose manual guide on Linux Ubuntu 18.04.

Let's say I now want to back up the whole server and move it to another computer.
What folders would I need to back up so I would keep my account and all the settings?

/var/lib/docker/volumes (which is quite large)
/etc/docker
$BTCPAY_ENV_FILE
$BTCPAY_DOCKER_COMPOSE
/etc/profile.d/btcpay-env.sh

Anything else I am missing?

**Comment by NicolasDorier** [comment]
`/var/lib/docker/volumes` is containing the whole bitcoin folder, which you can prune so it get smaller or completely leave out and resync on the other machine.

`/etc/docker` do not need to be saved.

You don't have to backup `$BTCPAY_DOCKER_COMPOSE` this is automatically generated by the btcpayserver-docker repo/branch you are installing from.

**Comment by vitormilagres1992** [comment]
So I assume the other two I mentioned would still need to be backed up, right?

$BTCPAY_ENV_FILE
/etc/profile.d/btcpay-env.sh

**Comment by NicolasDorier** [comment]
yes
