### ISSUE TITLE
Doge and Dash aren't syncing...

### ISSUE THREAD

**Issue by chovy** [btcpayserver/btcpayserver-docker#253]
I enabled these two coins, and they appear in the popup but they are both at 0 height after a week.

Something isn't working properly, does anyone know how to get these nodes to start syncing?

**Comment by pavlenex** [comment]
Duplicate of #904 so I'll close it. Try solutions suggested there. We're focused on Bitcoin and not really able to help with troubleshooting alts as those are maintained by their respective communities.
