### ISSUE TITLE
Incorrect Transmuter external service link

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver-docker#255]
Even though the `BTCPAY_EXTERNALSERVICES` for the BTC Transmuter seems to be set correctly, the link in the "Server settings: Services" admin area does not reflect that value.

I've configured the `BTCTRANSMUTER_HOST` (i.e. `mytransmuter.com`), but the link leads to the BTCPay Server host postfixed with `/btctransmuter` (i.e. `mybtcpayserver.com/btctransmuter`).

**Comment by pavlenex** [comment]
afaik host for transmuter is no longer needed, @Kukks should know more. 

We should transfer this one to transmuter repo probably.

**Comment by Kukks** [comment]
Yes, this is deliberate. You should consider `BTCTRANSMUTER_HOST ` as legacy

**Comment by dennisreimann** [comment]
Thanks for the clarification, @Kukks!
