### ISSUE TITLE
RTL not showing menu after upgrade

### ISSUE THREAD

**Issue by sendbitcoin** [btcpayserver/btcpayserver-docker#257]
upgrading btcpayserver upgraded my RTL to 0.6.1 but also broke it. Menubar isn't visible anymore with the new design. upgrade process needs to modify RTL.conf

related to RTL issue: https://github.com/Ride-The-Lightning/RTL/issues/223

> 
> master has major release updates and will need some configurations to be changed first. Please check release notes from v0.6.0 as it suggests:
> 
> “The RTL config file RTL.conf, has been updated to include new config options for the UI. These config options must be configured to work with the new UI. The best approach is to rename the sample conf file and update per your config options.
> 
> You can also modify the existing config file.
> Following options must be added:
> 
> userPersona=OPERATOR
> themeMode=DAY
> themeColor=PURPLE
> currencyUnit=USD
> The following config options are now redundant and must be deleted from the config file:
> 
> flgSidenavOpened
> flgSidenavPinned
> menu
> menuType
> satsToBTC
> theme”

**Comment by Kukks** [comment]
update to the latest release, we downgraded back to 0.5.4 for lnd

**Comment by NicolasDorier** [comment]
+1 Update to the latest release to downgrade.

**Comment by sendbitcoin** [comment]
upgrading did indeed downgrade RTL and fixed the issue

thx
