### ISSUE TITLE
Problem setting btcpayserver and caddy

### ISSUE THREAD

**Issue by eltNEG** [btcpayserver/btcpayserver-docker#264]
I just got started with btcpayserver and caddy (which I just got started with also). I have caddy listening on `PORT 80` and `PORT 443`. This means that I already have https. I set up btcpayserver using the readme and [this doc](https://docs.btcpayserver.org/deployment/raspberrypideployment/rpi3).

**Issues:**

- The website always redirects from `https://btcpay.coinp.co/` to `https://btcpay.coinp.co/Account/Register`. I expect to see the landing page when I visit the base path.
- `curl http://0.0.0.0:<REVERSE_PROXY_PORT>` on the server instance returns `>503 Service Temporarily Unavailable` 
- I got this error (`You cannot login over an insecure connection. Please use HTTPS or Tor.`) on the register and login page. I don't expect to see this since I have `x-forwarded-proto: https` set in the header as suggested in the doc.
- Lastly, `docker ps` shows that `clightning_bitcoin_spark` and `c-lightning-rest` are always failing.

**Config**

BTCPAY_PROTOCOL:http (`I have also tried https`)
BTCPAY_HOST:btcpay.coinp.co
BTCPAY_ADDITIONAL_HOSTS:
REVERSEPROXY_HTTP_PORT:<REVERSEPROXY_HTTP_PORT>
REVERSEPROXY_HTTPS_PORT:<REVERSEPROXY_HTTPS_PORT>
REVERSEPROXY_DEFAULT_HOST:none
LIBREPATRON_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
BTCPAY_ENABLE_SSH:false
BTCPAY_HOST_SSHKEYFILE:
LETSENCRYPT_EMAIL:
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:<ALIAS>
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:clightning
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-xs;opt-save-memory
BTCPAYGEN_EXCLUDE_FRAGMENTS:nginx-https;opt-add-tor
BTCPAY_IMAGE:
ACME_CA_URI:production
TOR_RELAY_NICKNAME: 
TOR_RELAY_EMAIL: 

Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/<basePath>/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/<basePath>/BTCPayServer
BTCPAY_ENV_FILE=/<basePath>/BTCPayServer/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS:/root/.ssh/authorized_keys
BTCPAY_SSHTRUSTEDFINGERPRINTS:
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:btcpay.coinp.co

**QUESTION**

I looked into using [production no reverse proxy](https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production-NoReverseProxy/README.md) but caddy is already listening on port 80. Is this PORT configurable?

**Comment by eltNEG** [comment]
Based on[ this reply](https://github.com/btcpayserver/btcpayserver-docker/issues/263#issuecomment-581472247), I think I understand why `curl http://0.0.0.0:<REVERSE_PROXY_PORT>` returns `503`

**Comment by eltNEG** [comment]
I checked my logs again and discovered that I set `x-forwarded-proto` on the response and not the `request` header.  🤦‍♂️

**Comment by maltokyo** [comment]
Hi @eltNEG I also use caddy, and some of the services dont show at all..  like rtl gives a 404 error.  Could you please share your caddyfile with me?  What do I miss..
