### ISSUE TITLE
Help please: BTCPay Server with letsencrypt-nginx-proxy-companion

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#267]
I have VPS with 32GB RAM and trying to run everything on it with "pure" docker and docker-compose.
  
For the Nginx reverse proxy (RP) I use my own one (not the one in BTCPay), and it runs 20-30 web apps and services without any issues (WordPress sites, nextcloud etc), and gets them all their own LetsEncrypt certs etc and serves them all on port 443, it is like a dream compared to my pre-docker life.  Here is what I use to automate all of the above for Nginx:
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

I am trying to add BTCPay Server Docker into this mix so I can run it also in the same environment, using the reverse proxy from the stack mentioned above (I cannot use BTCPay Nginx, as they will clash on the same machine, both using port 443).

Once I get it all set up, I am willing to write a tutorial on how to do it, for those who want to run BTCPay as part of a stack of many other web apps behind Nginx,

But, I have some issues, and I would like some help to get it up and running.

My setup so far is as follows, note that I am trying to change stanard setup to NOT run the BTCPay nginx or https servers by using `BTCPAY_PROTOCOL` to only run btcpayserver on http, and use `BTCPAYGEN_EXCLUDE_FRAGMENTS="nginx;nginx-https",` because my Nginx RP should do all of this as it does for all my other services.

1. DNS for pay.mydomain.com pointing correctly to my VPS public IP

2. Run this
`export BTCPAY_PROTOCOL="http" && export LETSENCRYPT_EMAIL="maltokyo@mydomain.com" && export BTCPAY_HOST="pay.mydomain.com" && export BTCPAY_ENABLE_SSH=true && export NBITCOIN_NETWORK="mainnet" && export BTCPAYGEN_CRYPTO1="btc" && export BTCPAYGEN_EXCLUDE_FRAGMENTS="nginx;nginx-https" && export BTCPAYGEN_ADDITIONAL_FRAGMENTS="z_btcpayserver-nginx.custom,opt-more-memory;opt-save-storage"`

3. Resulting in Env file:

> BTCPAY_PROTOCOL=http
> BTCPAY_HOST=pay.mydomain.com
> BTCPAY_ADDITIONAL_HOSTS=
> BTCPAY_ANNOUNCEABLE_HOST=pay.mydomain.com
> REVERSEPROXY_HTTP_PORT=80
> REVERSEPROXY_HTTPS_PORT=443
> REVERSEPROXY_DEFAULT_HOST=none
> BTCPAY_IMAGE=
> ACME_CA_URI=production
> NBITCOIN_NETWORK=mainnet
> LETSENCRYPT_EMAIL=maltokyo@mydomain.com
> LIGHTNING_ALIAS=
> BTCPAY_SSHTRUSTEDFINGERPRINTS=
> BTCPAY_SSHKEYFILE=/datadir/host_id_rsa
> BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
> BTCPAY_HOST_SSHAUTHORIZEDKEYS=/root/.ssh/authorized_keys
> LIBREPATRON_HOST=
> BTCTRANSMUTER_HOST=
> BTCPAY_CRYPTOS=btc
> WOOCOMMERCE_HOST=
> TOR_RELAY_NICKNAME=
> TOR_RELAY_EMAIL=

4. I have then added a customer docker-fragment called z_btcpayserver-nginx.custom.yml for BTCPay, and enabled it, with the below content.

```
version: "3"

services:

  btcpayserver:
    environment:
      # NGINX settings
      VIRTUAL_NETWORK: webproxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern

      # Let's encrypt settings
      LETSENCRYPT_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
```

4. After this runs, I check `docker logs nginx-letsencrypt` and it shows that the LetsExcrypt certs for btcpayserver are not being generated (and they are for all of my other services).  It shows error:

> /etc/nginx/certs/pay.mydomain.com /app
> Creating/renewal pay.mydomain.com certificates... (pay.mydomain.com)
> 2020-02-14 11:47:57,014:INFO:simp_le:1414: Generating new certificate private key
> 2020-02-14 11:47:59,923:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2812654331
> Challenge validation has failed, see error log.

Help Needed 1: Main question/concern is that I need to make BTCPay Server containers all run on the same docker network as the Nginx RP.  That network name is `webproxy` so I have it in the  docker-compose custom fragment as`VIRTUAL_NETWORK: webproxy`  -  Is there any other place I need to check, to ensure that the entire BTCPay suite runs on the same network?  How can I change it all from the defauly docker network, to the one that I run on?

Help Needed 2: Can anyone see any other issues that could cause this not to work?  I have been scratching my head for weeks.

Thank you

**Comment by maltokyo** [comment]
I got this working, but it is really hacky...  is there a more elegant way to achieve this?

Here is what I needed to do:

Did this
```
export BTCPAY_PROTOCOL="http"
export BTCPAY_HOST="pay.mydomain.com"
export BTCPAYGEN_REVERSEPROXY="none"
./build.sh
```


Then in the generated "Generated/docker-compose.generated.yml" I modified these lines, commented out some and hard coded others (not sure what actually was actually effective here, would anyone know?):
```
      #VIRTUAL_NETWORK: webproxy
      #VIRTUAL_PORT: 49392
      #VIRTUAL_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      #VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern
      #LETSENCRYPT_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      #LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      VIRTUAL_HOST: "pay.mydomain.com"
      VIRTUAL_PORT: 49392
      LETSENCRYPT_HOST: "pay.mydomain.com"
      LETSENCRYPT_EMAIL: "maltokyo@mydomain.com"
```

Replace networks line at bottom of "Generated/docker-compose.generated.yml" to force BTCPay to use my own docker network that the rest of my apps use, called "webproxy":
```
networks:
  default:
    external:
      name: webproxy

```
Run
```
docker-compose -f "Generated/docker-compose.generated.yml" up --remove-orphans -d
docker-compose -f "Generated/docker-compose.generated.yml" down
```

I guess the main point is to get BTCPay on the right docker network, but I could not find how to do it and had to hardcode it.

**Comment by NicolasDorier** [comment]
Read https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

**Comment by maltokyo** [comment]
Just this didn't work @NicolasDorier 
I of course read this.. but was getting nowhere. I had to start hacking. When I work out exactly what's needed I'll update the docs

**Comment by maltokyo** [comment]
@NicolasDorier do you know where the last line in docker-compose.generated.yml, stating `networks: {}` is generated?  I am looking for a way to make my own fragment to control this, and put BTCPay Server on my own previously existing network, which my Nginx reverse proxy is already on.
Thanks!

**Comment by NicolasDorier** [comment]
I am merging all the networks sections of fragments in `DockerComposeDefintion.cs`.
I guess if no networks is found in any fragments, then it generate an empty node, which is `networks: {}`

If you put your own network somewhere in your fragments, I think it will put this one instead.

**Comment by maltokyo** [comment]
Will give it a go. Thanks!

**Comment by maltokyo** [comment]
it worked well, thanks!
