### ISSUE TITLE
Replace export BTCPAYGEN_CRYPTO2="ltc" with export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage"

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-docker#274]
I've noticed that people simply copy-paste instructions provided in docker readme and forget to add pruning. I think it's far more useful to mention pruning in [Full installation (for technical users)](https://github.com/btcpayserver/btcpayserver-docker#full-installation-for-technical-users) at least as an option than LTC.

People often forget this step, I myself forgot it a couple of times.

**Comment by Kukks** [comment]
ack

**Comment by pavlenex** [comment]
Especially since we tell people that min requirements are cca 80GB, I probably need to explain better the min requirements part. Since it can be much lower and need to add SSD since we don't mention SSD is preferred.

**Comment by pavlenex** [comment]
ping @NicolasDorier noticed a lot of people forget pruning and almost nobody has space by default so it may be useful to add it and remove ltc

**Comment by NicolasDorier** [comment]
ack
