### ISSUE TITLE
Specify nginx web ports to allow apache/other reverse proxying

### ISSUE THREAD

**Issue by vswee** [btcpayserver/btcpayserver-docker#29]
I want to use btcpay behind my existing apache installation. Any way to specify alternatives for nginx other than 80,443?

**Comment by NicolasDorier** [comment]
Ping @boblechinois, @Kukks having a way to change the port has been askign to be several time. I think the env variable with default is the good solution, but did not had chance to do it.

**Comment by jarole** [comment]
Hello, I used env variable `BTCPAY_PORT="443" ` as Kukks pointed in #30 , but the nginx container still starts using 443. Is there a way how to change the port or disable nginx proxy? I would set up reverse proxy with apache.
