### ISSUE TITLE
Already have full BTC blockchain synced, how to have BTCPay use it?

### ISSUE THREAD

**Issue by 78bash** [btcpayserver/btcpayserver-docker#292]
Btcpayserver-docker successfully installed and is running. Yet I have a fully downloaded BTC blockchain already being synced into a folder on the same machine. How can we have btcpayserver-docker sync into the already synced blockchain?

**Comment by Kukks** [comment]
https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#how-to-deploy-btcpay-server-alongside-existing-bitcoin-node

**Comment by 78bash** [comment]
Thanks for the quick response.
I did as advised in the link, I seem to be receiving this error msg now and can't connect to the web portal through the browser anymore:
`ERROR: Service 'clightning_bitcoin' has a link to service 'bitcoind' which is undefined.`
How to solve?
