### ISSUE TITLE
Expose grpc for liquid node (Tor?)

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver-docker#294]
## ℹ️ Information
I want to expose the `grpc` endpoint to connect to my liquid node hosted in my btcpay server instance. I have already updated the `btcpayserver-docker/docker-compose-generator/docker-fragments/liquid.yml` to add some environment variables to allow server connections from the liquid node (Eg: `server=1`, `rpcuser=*******`,  `rpcpassword=*******`), generated the new `docker-compose` file and deployed the new updated service. I replaced `rpcauth` for `rpcuser` & `rpcpassword`

As an example, this is how my current `elements.conf` looks like:

```
chain=liquidv1
[liquidv1]
walletdir=/walletdata/liquidv1

printtoconsole=1
rpcallowip=::/0
rpcport=43782
rpcbind=0.0.0.0:43782
rpcuser=**********
rpcpassword=**********************
port=39338
server=1
whitelist=0.0.0.0/0
validatepegin=0
prune=5000
fallbackfee=0.000001
```

Adding @rbensberg from Blockstream (liquid) to the thread.
## 🔗 References
I have inspected the way `grpc` connections are exposed through Tor. @NicolasDorier would I have to replicate **the same hidden-service** to access my liquid node hosted in btcpay server globally as referenced below? Or How what other alternatives do I have?

#### Similar approach:
https://github.com/btcpayserver/btcpayserver-docker/blob/1ae425ebc901d251a94b6990de9b72cdb428ec1b/docker-compose-generator/docker-fragments/opt-add-tor.yml#L44

#### Client connection:
```
const Client = require('bitcoin-core')  
const client = new Client({
    ssl: {
      enabled: true,
      strict: false
    },
    host,
    port,
    username,
    password
  })
```

**Comment by Kukks** [comment]
> `rpcuser`

Please don't use `rpcuser` & `rpcpassword` and use `rpcauth` instead. If you use the former, any additional rpcauth config is ignored.

**Comment by Kukks** [comment]
There is no `grpc` api, I think you're referring to `json-rpc `

**Comment by Kukks** [comment]
Do not update liquid.yml directly, as you would not be able to pull updates otherwise. Please follow https://github.com/btcpayserver/btcpayserver-docker#how-can-i-customize-the-generated-docker-compose-file instead (create a new yml file and include it with additional fragments setting).

**Comment by Kukks** [comment]
If you still do need to edit the existing liquid.yml, copy it to liquid.custom.yml, exclude the original fragment with `BTCPAYGEN_EXCLUDE_FRAGMENTS` (`BTCPAYGEN_EXCLUDE_FRAGMENTS="liquid"`) and include the new one `BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;liquid.custom"`

**Comment by whiteyhat** [comment]
> There is no `grpc` api, I think you're referring to `json-rpc `

Yes that is correct. The ports exposing through liquid must be different to the ones used in bitcoins, right?

Also, what would the procedure be to allow external json-rpc connections using the tor relay? It is basically copying and pasting the bitcoind service from https://github.com/btcpayserver/btcpayserver-docker/blob/1ae425ebc901d251a94b6990de9b72cdb428ec1b/docker-compose-generator/docker-fragments/opt-add-tor.yml#L44 change the ports and modify some custom settings?

**Comment by whiteyhat** [comment]
@Kukks I made it work using the previous example from `bitcoind`
<img width="676" alt="Captura de pantalla 2020-04-22 a las 20 45 29" src="https://user-images.githubusercontent.com/31220861/80021492-e0f34e00-84da-11ea-8c59-fe7d9d32d90c.png">

Can you recommend me any library to query through json-rpc that supports/resolves this tor connection?

**Comment by Kukks** [comment]
You need to start tor and use its socks5 proxy to connect to the rpc.

**Comment by whiteyhat** [comment]
@Kukks I do not understand much how tor works... I want to interact with `json-rpc` using a client (https://github.com/ruimarinho/bitcoin-core). However, it is not resolving any .onion domain...

Do I need to set-up a tor proxy (https://www.npmjs.com/package/tor-request) and then what? Using the socks5 how I connect to the instance in btcpay?

**Comment by whiteyhat** [comment]
I am afraid I will have to go the unsafe way by exposing the ports because TOR & RPC does not seem to be very friendly with each other 😃

I will use this as a reference to do it: https://github.com/btcpayserver/btcpayserver-docker/blob/1ae425ebc901d251a94b6990de9b72cdb428ec1b/docker-compose-generator/docker-fragments/opt-expose-unsafe.yml

**Comment by Kukks** [comment]
It's your choice but I warned you. You are using the node as a hot wallet
and exposing the rpc publicly enlarges the risk of hacks and attacks even
more, especially against an officially insecure rpc where everyone knows
the rpc url

**Comment by whiteyhat** [comment]
A code snippet to validate that the tor connection via rpc is valid from the internet or in local would be ideal to have it in the services section of the btcpay instance. 

At this point, I still have issues trying to figure it out how to connect to and tor `hidden-service` using rpc with a tor proxy and the socks 5 type without any rpc libs.

In the worst case scenario I will have to go the unsafe way... But If I find out a way to connect it via rpc under tor I would love to do it 😺

**Comment by whiteyhat** [comment]
I made it work without exposing the port and connecting via tor proxy with socks 5 🥳
