### ISSUE TITLE
502 Bad Gateway on New Install (Docker) (was working)

### ISSUE THREAD

**Issue by digimbyte** [btcpayserver/btcpayserver-docker#295]
Fresh install of BTCPay
Web portal worked
Shutdown btcpay
updated with freeSync
Started btcpay
Web portal results in 502 Bad Gateway
connecting to server ip manually results in 503
tried restart, tried reinstall per online suggestions

> I'm concerned if FreeSync was interupted and its the cause of this.

Do we have a script to debug/report status of web portal?

Additional: error on btcpay-setup.sh
```
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:40866->[::1]:53: read: connection refused
``` 
Following some debug advice, curl the local host
```
/BTCPayServer/btcpayserver-docker# curl -v http://127.0.0.1:9001/
* Expire in 0 ms for 6 (transfer 0x55ec1e40cf50)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55ec1e40cf50)
* connect to 127.0.0.1 port 9001 failed: Connection refused
* Failed to connect to 127.0.0.1 port 9001: Connection refused
* Closing connection 0
````

Tried looking at the bitcoin-cli.sh
returned the following
```
Error response from daemon: Container 81bc57......514 is restarting, wait until the container is running
```

looks like some containers are restarting?
```
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS                         PORTS                                      NAMES
57969ad5e6e2        btcpayserver/letsencrypt-nginx-proxy-companion:1.12.2   "/bin/bash /app/entr…"   14 hours ago        Up 14 hours                                                               letsencrypt-nginx-proxy-companion
64312476349f        btcpayserver/btcpayserver:1.0.4.1                       "/app/docker-entrypo…"   14 hours ago        Up 4 seconds                   49392/tcp                                  generated_btcpayserver_1
a00735325ce5        saubyk/c-lightning-rest:0.2.2                           "./docker-entrypoint…"   14 hours ago        Up Less than a second          3001/tcp, 4001/tcp                         generated_clightning_bitcoin_rest_1
1e6f0448af5a        shesek/lightning-charge:0.4.16-standalone               "bin/docker-entrypoi…"   14 hours ago        Up 14 hours                    9112/tcp, 9735/tcp                         generated_clightning_bitcoin_charge_1
9a3ee74427f5        shesek/spark-wallet:0.2.9-standalone                    "tini -g -- scripts/…"   14 hours ago        Up 14 hours                    9735/tcp, 9737/tcp                         generated_clightning_bitcoin_spark_1
287fdd5211b6        btcpayserver/lightning:v0.8.0                           "/usr/bin/tini -g --…"   14 hours ago        Up 14 hours                    0.0.0.0:9735->9735/tcp, 9835/tcp           btcpayserver_clightning_bitcoin
81bc576dae72        btcpayserver/bitcoin:0.19.0.1                           "/entrypoint.sh bitc…"   14 hours ago        Restarting (1) 7 seconds ago                                              btcpayserver_bitcoind
23a1067fe920        btcpayserver/docker-gen:0.7.7                           "/usr/local/bin/dock…"   14 hours ago        Up 14 hours                                                               tor-gen
d11afb8170f2        shahanafarooqui/rtl:0.6.8                               "/sbin/tini -g -- no…"   14 hours ago        Up 14 hours                    3000/tcp                                   generated_bitcoin_rtl_1
0e238525d486        nginx:1.16.0                                            "nginx -g 'daemon of…"   14 hours ago        Up 14 hours                    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
a28b20357344        nicolasdorier/nbxplorer:2.1.24                          "dotnet NBXplorer.dll"   14 hours ago        Up 14 hours                    32838/tcp                                  generated_nbxplorer_1
6911c0007a99        postgres:9.6.5                                          "docker-entrypoint.s…"   14 hours ago        Restarting (1) 7 seconds ago                                              generated_postgres_1
```

**Comment by digimbyte** [comment]
docker-compose.yml config
`version: "3"
services:
  nginx:
    restart: unless-stopped
    image: nginx:1.16.0
    container_name: nginx
    ports:
    - "${REVERSEPROXY_HTTP_PORT:-80}:80"
    - "${REVERSEPROXY_HTTPS_PORT:-443}:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
  nginx-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.7
    container_name: nginx-gen
    environment:
      DEFAULT_HOST: ${REVERSEPROXY_DEFAULT_HOST:-none}
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - btcpayserver
    - nginx
  btcpayserver:
    restart: unless-stopped
    image: ${BTCPAY_IMAGE:-btcpayserver/btcpayserver:1.0.4.1}
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc"
      BTCPAY_BTCEXTERNALSPARK: "server=/spark/btc/;cookiefile=/etc/clightning_bitcoin_spark/.cookie"
      BTCPAY_BTCEXTERNALCHARGE: "server=/lightning-charge/btc/;cookiefilepath=/etc/clightning_bitcoin_charge/.cookie"
      BTCPAY_BTCEXTERNALRTL: "server=/rtl/api/authenticate/cookie;cookiefile=/etc/clightning_bitcoin_rtl/.cookie"
      BTCPAY_BTCEXTERNALCLIGHTNINGREST: "server=/clightning-rest/btc;macaroonfilepath=/etc/clightning_bitcoin_rest/certs/access.macaroon;macaroondirectorypath=/etc/clightning_bitcoin_rest/certs"
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      HIDDENSERVICE_NAME: BTCPayServer
      HIDDENSERVICE_REVERSEPROXY: nginx
      BTCPAY_TORRCFILE: /usr/local/etc/tor/torrc-2
      BTCPAY_SOCKSENDPOINT: tor:9050
    links:
    - postgres
    - clightning_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "/root/.ssh/authorized_keys:${BTCPAY_SSHAUTHORIZEDKEYS}"
    - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"
    - "clightning_bitcoin_spark:/etc/clightning_bitcoin_spark"
    - "clightning_bitcoin_charge:/etc/clightning_bitcoin_charge"
    - "clightning_bitcoin_rtl_datadir:/etc/clightning_bitcoin_rtl"
    - "clightning_bitcoin_rest_datadir:/etc/clightning_bitcoin_rest"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
    - "tor_torrcdir:/usr/local/etc/tor/"
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:0.19.0.1
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BITCOIN_WALLETDIR: "/walletdata"
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        port=39388
        whitelist=0.0.0.0/0

        prune=50000
        dbcache=50
        maxmempool=50

        onion=tor:9050
        # rpcuser=btcrpc
        # rpcpassword=btcpayserver4ever
        # We need to use rpcauth because we also need cookieauth. rpcpassword disabled cookie file auth.
        # Be careful if you copy the line below from the docker-compose.yml! A dollar sign is escaped.
        rpcauth=btcrpc:a6a5d29a3f44f02e4cd8cabb5b10a234$$ab6152915515f6a9cca806d2ab5f0e2794c346ba74f812c61e48241d523778b8
      HIDDENSERVICE_NAME: BTC-P2P,BTC-RPC
      BTC-P2P_HIDDENSERVICE_VIRTUAL_PORT: 8333
      BTC-P2P_HIDDENSERVICE_PORT: 39388
      BTC-RPC_HIDDENSERVICE_VIRTUAL_PORT: 8332
      BTC-RPC_HIDDENSERVICE_PORT: 43782
    expose:
    - "43782"
    - "39388"
    volumes:
    - "bitcoin_datadir:/data"
    - "bitcoin_wallet_datadir:/walletdata"
    - "tor_datadir:/home/tor/.tor"
    links:
    - tor
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.1.24
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "bitcoin_datadir:/root/.bitcoin"
  clightning_bitcoin:
    image: btcpayserver/lightning:v0.8.0
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_ALIAS: ${LIGHTNING_ALIAS}
      LIGHTNINGD_ANNOUNCEADDR: ${BTCPAY_ANNOUNCEABLE_HOST}
      LIGHTNINGD_PORT: 9735
      LIGHTNINGD_READY_FILE: /root/.nbxplorer/btc_fully_synched
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind

        proxy=tor:9050
      HIDDENSERVICE_NAME: c-lightning
      HIDDENSERVICE_PORT: 9735
      LIGHTNINGD_HIDDENSERVICE_HOSTNAME_FILE: /var/lib/tor/hidden_services/c-lightning/hostname
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
    ports:
    - "9735:9735"
    links:
    - bitcoind
    - tor
  clightning_bitcoin_charge:
    image: shesek/lightning-charge:0.4.16-standalone
    restart: unless-stopped
    stop_signal: SIGKILL
    environment:
      NETWORK: ${NBITCOIN_NETWORK:-regtest}
      COOKIE_FILE: /data/.cookie
      URL: ${BTCPAY_ROOTPATH:-/}lightning-charge/btc/
    volumes:
    - "clightning_bitcoin_datadir:/etc/lightning"
    - "clightning_bitcoin_charge:/data"
    expose:
    - "9112"
    links:
    - clightning_bitcoin
  clightning_bitcoin_spark:
    image: shesek/spark-wallet:0.2.9-standalone
    restart: unless-stopped
    environment:
      NETWORK: ${NBITCOIN_NETWORK:-regtest}
      SPARK_OPT: --no-tls -C /data/.cookie
    volumes:
    - "clightning_bitcoin_datadir:/etc/lightning"
    - "clightning_bitcoin_spark:/data"
    links:
    - clightning_bitcoin
    expose:
    - "9737"
  clightning_bitcoin_rest:
    image: saubyk/c-lightning-rest:0.2.2
    restart: unless-stopped
    environment:
      PROTOCOL: "http"
      NODE: clightning_bitcoin:9835
    links:
    - clightning_bitcoin
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    - "clightning_bitcoin_rest_datadir:/usr/src/app"
    expose:
    - "3001"
  bitcoin_rtl:
    image: shahanafarooqui/rtl:0.6.8
    restart: unless-stopped
    environment:
      LN_IMPLEMENTATION: CLT
      CONFIG_PATH: /root/.lightning/config
      LN_SERVER_URL: http://clightning_bitcoin_rest:3001/v1
      MACAROON_PATH: /etc/clightning_bitcoin_rest/certs
      RTL_CONFIG_PATH: /data/
      BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
      RTL_SSO: 1
      RTL_COOKIE_PATH: /data/.cookie
      LOGOUT_REDIRECT_LINK: /server/services
    volumes:
    - "bitcoin_datadir:/etc/bitcoin"
    - "clightning_bitcoin_rtl_datadir:/data"
    - "clightning_bitcoin_rest_datadir:/etc/clightning_bitcoin_rest"
    expose:
    - "3000"
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: btcpayserver/letsencrypt-nginx-proxy-companion:1.12.2
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-staging}
    links:
    - nginx-gen
  tor:
    restart: unless-stopped
    image: btcpayserver/tor:0.4.1.5
    container_name: tor
    environment:
      TOR_PASSWORD: btcpayserver
      TOR_ADDITIONAL_CONFIG: /usr/local/etc/tor/torrc-2
      TOR_EXTRA_ARGS: |
        CookieAuthentication 1
    expose:
    - "9050"
    - "9051"
    volumes:
    - "tor_datadir:/home/tor/.tor"
    - "tor_torrcdir:/usr/local/etc/tor"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
  tor-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.7
    container_name: tor-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./torrc.tmpl:/etc/docker-gen/templates/torrc.tmpl:ro"
    - "tor_torrcdir:/usr/local/etc/tor"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup tor -watch -wait 5s:30s /etc/docker-gen/templates/torrc.tmpl /usr/local/etc/tor/torrc-2
    links:
    - tor
volumes:
  nginx_conf: 
  nginx_vhost: 
  nginx_html: 
  nginx_certs: 
  btcpay_datadir: 
  bitcoin_datadir: 
  bitcoin_wallet_datadir: 
  clightning_bitcoin_datadir: 
  clightning_bitcoin_spark: 
  clightning_bitcoin_charge: 
  clightning_bitcoin_rtl_datadir: 
  clightning_bitcoin_rest_datadir: 
  postgres_datadir: 
  nbxplorer_datadir: 
  tor_datadir: 
  tor_torrcdir: 
  tor_servicesdir: 
networks: {}
`

**Comment by NicolasDorier** [comment]
hi `FreeSync` you mean FastSync?

I can see you bitcoind is restarting, you can see why by looking the logs `docker logs container_id` of the bitcoind contianer.

**Comment by digimbyte** [comment]
Thanks! yes it was FastSync
looks like its out of space?

> 2020-04-24T16:54:30Z Error: Error loading wallet . boost::filesystem::create_directory: No space left on device: "/walletdata/mainnet/database"
> 2020-04-24T16:54:30Z Shutdown: In progress...
> 2020-04-24T16:54:30Z scheduler thread start

But I remember setting the size to 25GB, ideas?

**Comment by NicolasDorier** [comment]
@digimbyte then get more space. Maybe bitcoin core can't even start to free up the blocks. I can't troubleshot that for you, you need to free up space.

**Comment by digimbyte** [comment]
Closing issue, couldn't keep BTC under the prune limit, which I setup before it maxed.
So this should have never been an issue. even when using -clean.sh which restored 1.6GB - it was filled again.
I believe something else maybe going on but I'm going to use a 3rd party provider since I need it working asap.

**Comment by NicolasDorier** [comment]
The fatest way is to just follow the one click deploy on https://www.youtube.com/watch?v=oce_fvRdLLY

**Comment by digimbyte** [comment]
Whats the point if setting the prune size doesn't work?
How does it work? do I need 120GB before I can downsize the cache to 25GB?

I cannot upgrade the HDD size without blowing the monthly budget by 3x and there are no documents for spreading the load over multiple hdd's or setting up a secondary hdd as the resource location.
The server is 55gb, btcpay has pruning for 50gb and 25gb
set config to prune at 25gb, but it didn't take to the size capacity, I did use the clean script to free up 2gb, of which is proceeded to download more rather than cleanup the cache.

If there were some way to make sure those prune settings are applied in the docker/btc cache manager or maybe a guide to manually delete the cache to redownload it so it stays at 25GB

**Comment by NicolasDorier** [comment]
@digimbyte I have no idea how you set things up.
If you want to delete your node data, 

```bash
btcpay-down.sh
rm -rf /var/lib/docker/volumes/generated_bitcoin_datadir/_data
mkdir /var/lib/docker/volumes/generated_bitcoin_datadir/_data
# Assuming opt-save-storage-xxs is the only fragment you want
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-xxs"
. btcpay-setup.sh -i
btcpay-up.sh
```
More info on https://github.com/btcpayserver/btcpayserver-docker if you want different `BTCPAYGEN_ADDITIONAL_FRAGMENTS`.
