### ISSUE TITLE
NBXplorer won't start

### ISSUE THREAD

**Issue by iamvinny** [btcpayserver/btcpayserver-docker#3]
When I run `docker-compose up` the BTCPay Server starts fine, but when I try to access the site, I get the error below.

![Image of the Error](https://i.imgur.com/SKzxBVK.png)

Here is the output I keep getting:

```
nbxplorer_1                          | info: Configuration:  Network: Main
nbxplorer_1                          | warn: Configuration:  RPC Cookie file not found at /btc/.cookie
nbxplorer_1                          | fail: Configuration:  RPC connection settings not configured
nbxplorer_1                          | Application is shutting down...
```

And here my env variables.

```
NBITCOIN_NETWORK="mainnet"
BTCPAY_HOST="payment.mywebsite.org"
LETSENCRYPT_EMAIL="admin@mywebsite.org"
BITCOIND_COOKIEFILE=".cookie"
BITCOIND_NETWORKPARAMETER="#mainnet=1"
ACME_CA_URI="https://acme-v01.api.letsencrypt.org/directory"
```

If I run `echo $NBITCOIN_NETWORK` it outputs the value of the variable, I don't think there's anything wrong with them. 

I guess it's the `.cookie` file that is not being generated or maybe a permission problem. I have also tried to run the docker as root, but the same error happened.

**Comment by iamvinny** [comment]
Ok, never mind, I haven't noticed that there was a typo in the "Production" ReadMe, I guess that hashtag shouldn't be there, **#**mainnet=1 , after removing it from my `BITCOIND_NETWORKPARAMETER` var everything is working fine, now the core is finally synching. :)

**Comment by NicolasDorier** [comment]
The hashtag should be here... but you are the second person reporting me this error.

The previous person problem was doing `sudo docker-compose`, it did not works because sudo does not pass env variables.

**Comment by iamvinny** [comment]
I wasn't running it with `sudo`, but I was running it with root user, should I create a non-root user for docker or is the problem only with the word `sudo`? Also, can the missing hashtag cause any problem?

**Comment by NicolasDorier** [comment]
the missing hashtag  does not cause problems, so I will probably remove it.

I only know the guy who got this problem did not had it by doing

```
sudo su -
docker-compose ... up
```
