### ISSUE TITLE
Integrate Lightning Loop Service as an additional fragement

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver-docker#308]
Once LND is upgraded to a compatible version, I think Lightning Loop from the LND team should be considered as an additional fragment. 

From my understanding, this service lets store owners who are running LND push liquidity to the other sides of the channels for a small fee. With the new MPP features, my understanding is you could also push all liquidity from multiple channels and "loop out" to onchain with only a single transaction.*

I really think this is a useful feature to stores who do a lot of volume inbound, but not much outbound. 

_*I could be wrong, lol_

**Comment by pavlenex** [comment]
The only thing wrong is this issue is you posting it to a wrong repo. 😄

**Comment by culiao** [comment]
Accepting lightning payments as a merchant will be much easier with loop out integration. I'm trying to add ln payment option for a few stores I operate and now I see that inbound liquidity is a tricky issue.

**Comment by NicolasDorier** [comment]
@rockstardev is working to have loop integrate in a future release.

**Comment by sendbitcoin** [comment]
I would also like loop in btcpayserver

**Comment by Nisaba** [comment]
Hi All,
What about this feature ?
When could we hope to have Loop service enabled with BTCPay docker installs ?

Thanks !

**Comment by rockstardev** [comment]
@Nisaba it's coming soon... we're looking into even doing support by directly using Docker image built by lightninglabs. Join https://chat.btcpayserver.org if you haven't already - that's where it'll be announced first.

**Comment by LukasRada** [comment]
Will be the branch [lnd-0.12.0-beta-withloop](https://github.com/btcpayserver/btcpayserver-docker/tree/feat/lnd-0.12.0-beta-withloop) merged eventually? Or any update/ETA? Can I help?

**Comment by rockstardev** [comment]
@LukasRada yes it's coming and you can help with PR review and testing. I'll open PR in next 24 hours and mention you.

**Comment by bitcoinheiro** [comment]
Is this happening? :)

**Comment by pavlenex** [comment]
@bitcoinheiro Yes see #450 in the next major version.
