### ISSUE TITLE
Monero btcpayserver/monero:0.15.0.1-amd64 keeps restarting

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver-docker#315]
I am new to docker and frankly I can not fix this myself, I know the cause, I know what I should do, but I am unable to do so, this issue is continuation from https://github.com/btcpayserver/btcpayserver-docker/issues/309

I am getting errors, because there was different wallet set up and I need to delete wallet dir.
logs:
```
Monero 'Carbon Chamaeleon' (v0.15.0.1-release)
Logging to monero-wallet-rpc.log
WARNING: You may not have a high enough lockable memory limit, see ulimit -l
2020-05-25 08:29:23.735 W Loading wallet...
2020-05-25 08:29:23.737 I Generating SSL certificate
2020-05-25 08:29:25.600 I Generating SSL certificate
2020-05-25 08:29:26.332 W Loaded wallet keys file, with public address: 45mG...
2020-05-25 08:29:26.380 W Failed to open portable binary, trying unportable
2020-05-25 08:29:26.404 W Failed to open portable binary, trying unportable
2020-05-25 08:29:26.405 E Wallet initialization failed: basic_string::_M_replace_aux
```

the fix is to rename wallet directory: https://github.com/monero-project/monero/issues/3087

problem is, I can not do it:
```
docker exec -it  646dfca331ba /bin/bash
Error response from daemon: Container 646dfca331ba8b55c14f5881bdd08d5ab857bdc2fa3a6d7bc52814887f0eda43 is restarting, wait until the container is running
```

I tried to remove (docker rm and so on) the volume/container and update...but problem persist.

please help.

**Comment by Kukks** [comment]
If you have no idea what you are doing, messing around with deleting containers and volumes was probably not a wise choice at all. 

You can typically find the docker volumes (which contain the wallet dir) on a default docker install under `var/lib/docker/volumes` there should be one called monero wallet dir or something. Inside it will be a `data` folder. **DELETE ITS CONTENTS NOT THE FOLDER ITSELF**
