### ISSUE TITLE
Monero wallet unavailable

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver-docker#316]
This is continuation from https://github.com/btcpayserver/btcpayserver-docker/issues/315

I fixed the problem, but no Wallet available: false

logs:

```
# ls /var/lib/docker/volumes/generated_xmr_wallet/_data
password  wallet  wallet.keys

#btcpayserver_monero_wallet is up and running - not restarting (docker ps)

#docker logs:
Monero 'Carbon Chamaeleon' (v0.15.0.1-release)
Logging to monero-wallet-rpc.log
WARNING: You may not have a high enough lockable memory limit, see ulimit -l
2020-05-25 08:59:23.984 W Loading wallet...
2020-05-25 08:59:23.985 I Generating SSL certificate
2020-05-25 08:59:26.835 I Generating SSL certificate
2020-05-25 08:59:28.313 W Loaded wallet keys file, with public address: 46D..
2020-05-25 08:59:28.382 E No message store file found: /wallet/wallet.mms

#from website
Node available: True
Wallet available: False (Wallet file present)
Last updated: 5/25/2020 9:02:57 AM
Synced: True (2105929 / 2105876)
```

not sure why wallet available is showing false.

Kukks thanks for support.

**Comment by 2ge** [comment]
issue was resolved by itself, now everything works. Perfect!

**Comment by d2ro** [comment]
I just had the same issue and resolved it by deleting and then re-uploading the Monero wallet.

Turned out that file permissions were wrong.

Before (not working):

```
# ls -la /var/lib/docker/volumes/generated_xmr_wallet/_data
-rw-rw-rw- 1 root root password
-rw------- 1  101  101 wallet
-rw-rw-rw- 1 root root wallet.keys
```

After (working):

```
# ls -la /var/lib/docker/volumes/generated_xmr_wallet/_data
-rw-rw-rw- 1 root root password
-rw-rw-rw- 1 root root wallet
-rw-rw-rw- 1 root root wallet.keys
```

So adjusting the permissions and restarting BTCPay should also fix it.

**Comment by Delitants** [comment]
> I just had the same issue and resolved it by deleting and then re-uploading the Monero wallet.
> 
> Turned out that file permissions were wrong.
> 
> Before (not working):
> 
> ```
> # ls -la /var/lib/docker/volumes/generated_xmr_wallet/_data
> -rw-rw-rw- 1 root root password
> -rw------- 1  101  101 wallet
> -rw-rw-rw- 1 root root wallet.keys
> ```
> 
> After (working):
> 
> ```
> # ls -la /var/lib/docker/volumes/generated_xmr_wallet/_data
> -rw-rw-rw- 1 root root password
> -rw-rw-rw- 1 root root wallet
> -rw-rw-rw- 1 root root wallet.keys
> ```
> 
> So adjusting the permissions and restarting BTCPay should also fix it.

Doesn't help, after restart it stays in state Wallet available: False (Wallet file present). If I re-upload, it activates, but server restart breaks it every time.

**Comment by d2ro** [comment]
Yeah, I had noticed that as well a few days later. Now I'm always checking it manually after every reboot.

**Comment by Delitants** [comment]
> Yeah, I had noticed that as well a few days later. Now I'm always checking it manually after every reboot.

Try add "vm.max_map_count = 4093064" to /etc/sysctl.conf
And reboot, see it still falls off.

**However, when XMR wallet is loaded, when I try create an invoice, I get error 500.**
