### ISSUE TITLE
`Status Code: 404; Not Found` with pay button

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/btcpayserver-docker#32]
I run my own server at [https://sosthenebtcpay.pw](https://sosthenebtcpay.pw), I did an update about 30 min ago.
I want to try the pay button, so I copied the following lines of code in a dummy page of my blog [https://www.sosthene.net/Dons/](https://www.sosthene.net/Dons/) : 
```
<form method="POST" action="https://sosthenebtcpay.pw/stores/2uZB4Ud6LQVhRCNxq1wAphjhMNPhokXRdVJ8dpADSrpy/pay">
    <input type="hidden" name="price" value="0.00000100" />
    <input type="hidden" name="currency" value="BTC" />
    <input type="hidden" name="checkoutDesc" value="Tip" />
    <input type="image" src="https://sosthenebtcpay.pw/img/paybutton/pay.png" name="submit" style="width:209px" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor">
</form>
```
When I click on the button, I open the page [https://sosthenebtcpay.pw/stores/2uZB4Ud6LQVhRCNxq1wAphjhMNPhokXRdVJ8dpADSrpy/pay](https://sosthenebtcpay.pw/stores/2uZB4Ud6LQVhRCNxq1wAphjhMNPhokXRdVJ8dpADSrpy/pay)
The page is blank with a `Status Code: 404; Not Found` error.

**Comment by Kukks** [comment]
Can you log in and go to: 
https://sosthenebtcpay.pw/stores/2uZB4Ud6LQVhRCNxq1wAphjhMNPhokXRdVJ8dpADSrpy/paybutton
and see  if you get this screen:
![image](https://user-images.githubusercontent.com/1818366/45692342-d7fe0600-bb5a-11e8-847e-972f51da57de.png)

**Comment by BobleChinois** [comment]
Yes I did that

**Comment by Kukks** [comment]
And you still get the 404 error?

**Comment by BobleChinois** [comment]
Yes, I made another dummy page and copied paste the code again just to be sure, I still get the same 404 error

**Comment by Kukks** [comment]
Seems like it was because the new version's generated html is different and the browser cached the generator 🤕

**Comment by BobleChinois** [comment]
I cleared my cache, and got the new html code.
Should I close the issue ?
Thanks !

**Comment by Kukks** [comment]
Yeah close it. Oh, and next time post this issue to the btcpayserver repo
not the docker one. ;)
ᐧ
