### ISSUE TITLE
[Noob question] How to edit/customize text on login page?

### ISSUE THREAD

**Issue by sTiKyt** [btcpayserver/btcpayserver-docker#324]
It's probably very lazy and noob question, but is there any simple way to edit this text?
![Screenshot_20200625_180932](https://user-images.githubusercontent.com/35602029/85746521-2f0d1380-b70f-11ea-907b-533a37581f68.png)

I'd like to replace "your Btcpay server" with my domain.

**Comment by pavlenex** [comment]
Please, before opening an issue you should check our documentation. We tend to keep issues only for feature requests and bug reports. For general questions, it's best to check docs or ask on our chat.btcpayserver.org.

That said, to do what you want you'd need to fork btcpay and maintain your fork https://docs.btcpayserver.org/Theme/

**Comment by sTiKyt** [comment]
> Please, before opening an issue you should check our documentation. We tend to keep issues only for feature requests and bug reports. For general questions, it's best to check docs or ask on our chat.btcpayserver.org.
> 
> That said, to do what you want you'd need to fork btcpay and maintain your fork https://docs.btcpayserver.org/Theme/

Sorry and thanks
