### ISSUE TITLE
Please upgrade LND to 0.10.x

### ISSUE THREAD

**Issue by knocte** [btcpayserver/btcpayserver-docker#332]

**Comment by knocte** [comment]
Thanks! @rockstardev how exactly one upgrades to this? gotta wait for next version of BtcPay?

**Comment by rockstardev** [comment]
@knocte yeah, when @NicolasDorier decides to bump btcpayserver tag in this repo.

You can update your own instance in the meantime - I think just running `btcpay-update.sh` should do the trick since it'll `git pull` latest master.

**Comment by knocte** [comment]
@rockstardev ok thanks! /cc @Liongrass
