### ISSUE TITLE
Running btcpayserver on a bitcoind+lnd node

### ISSUE THREAD

**Issue by grunch** [btcpayserver/btcpayserver-docker#339]
Hi I want to run btcpayserver on a node that is already running bitcoind+lnd.

I just started `. ./btcpay-setup.sh -i` but I saw that btcpayserver tried to run a clightning on docker container (port 9735) and of course it failed.

Is it possible to make it work with my node which is already working with lnd?

If is not, is it possible to make btcpayserver work on a digital ocean droplet and connect to the lightning node using macaroons?

I can't find documentation for this, if is already documented can you pointed me to it and I'm sorry for this issue.

**Comment by NicolasDorier** [comment]
yes you can. This is written in the doc somewhere.

If you don't want btcpay to host anything, just set `export BTCPAYGEN_LIGHTNING=""` and run setup

**Comment by grunch** [comment]
awesome thanks
