### ISSUE TITLE
 listen tcp 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by k0fi** [btcpayserver/btcpayserver-docker#347]
I'm trying to deploy `btcpayserver-docker` to an under-utilized server. But the server has nginx running on  port 80, and I can not stop it. So after running these:

```
export BTCPAY_HOST="btcpay.mysite.com"
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-s"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="clightning"
export BTCPAY_ENABLE_SSH=true
. ./btcpay-setup.sh -i
```

I get:

`ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (somegibberishef8919f414900): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use`

I'm wondering if there is a way to resolve this problem without turning off nginx on the server?
What I hope is to assign a specific IP to btcpayserver so that it does not need to run on `0.0.0.0:80` and interfer in the exsiting nginx running on a another IP:80.

**Comment by NicolasDorier** [comment]
README:

```
REVERSEPROXY_HTTP_PORT: The public port the reverse proxy binds to for HTTP traffic (default: 80)
REVERSEPROXY_HTTPS_PORT: The public port the reverse proxy binds to for HTTPS traffic (default: 443)
```

If you do this though BTCPayServer might have problem to get a certificate from let's encrypt, so you need to configure your other nginx to do proper redirection. (search in the docs, that's documented)
