### ISSUE TITLE
[question] Running bitcoind and lnd behind tor

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/btcpayserver-docker#35]
I'm not quite sure this is the right place, but anyway : I used to run my bitcoind node behind tor, and I was wondering if it was possible/easy to run the node in the bctpay docker compose behind tor as well.

**Comment by NicolasDorier** [comment]
that would be very interesting. I think it is theorically possible. Even using TOR instead of HTTPS should be quite easy.

**Comment by NicolasDorier** [comment]
Done, use the `opt-add-tor` fragment
