### ISSUE TITLE
How to change port of website when running with NoReverseProxy

### ISSUE THREAD

**Issue by ParmuSingh** [btcpayserver/btcpayserver-docker#352]
As I had problems with NginX reverse proxy (and ended up writing my own). I decided to go for NoReverseProxy setup instead. I want to run btcpay server website on a different port so I can run my own proxy on port ```80``` and ```443```.

I have followed these instructions: https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production-NoReverseProxy/README.md

I am able to host btcpay locally though I want to run it on a different port. Are there any environment variables for that? I have tried ```REVERSEPROXY_HTTP_PORT``` and ```REVERSEPROXY_HTTPS_PORT``` from before but they don't work.

**Comment by NicolasDorier** [comment]
hi @ParmuSingh please do not use this.

You should use the reverse proxy. If you want your own in front, you can still do it.

See https://docs.btcpayserver.org/Docker/#can-i-offload-https-termination

**Comment by ParmuSingh** [comment]
closing because original issue solved on another thread. https://github.com/btcpayserver/btcpayserver-docker/issues/341#issuecomment-674393748
