### ISSUE TITLE
BTCPay Docker Install - HTTPS not getting setup

### ISSUE THREAD

**Issue by mmccollum2** [btcpayserver/btcpayserver-docker#358]
Hi All,

Brand new Ubuntu 20.04, followed this guide https://docs.btcpayserver.org/Docker/ - setup my custom variables below

export BTCPAY_HOST="pay.mydomain.com"
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-s"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="clightning"
export BTCPAY_ENABLE_SSH=true
export LETSENCRYPT_EMAIL="email@mydomain.com"
export ACME_CA_URI="production"

Setup 80 and 443 which are forwarding properly externally
Running the . ./btcpay-setup.sh -i seemed to install just fine - 

then going to https://pay.mydomain.com I get an invalid cert popup and then a 500 Internal Server Error

If I go to http://pay.mydomain.com/Account/Register then it loads the welcome screen but  "You cannot login over an insecure connection. Please use HTTPS or Tor. "

Not sure where I should be setting up letsencrypt to do a dns validation or if I missed a step in the docker setup? Seems like after/during running btcpay-setup.sh that I would get a prompt for a dns/txt letsencrypt validation and then it would setup certs?

Let me know if you need any logs or where I should go from here!  thanks

**Comment by pavlenex** [comment]
As pointed out by @petzsch in our [community cha](https://chat.btcpayserver.org/btcpayserver/pl/smeo9wpa738k9rayq7a9dwqaie)t, this seems to be the [performance issue of Let's Encrypt.](https://community.letsencrypt.org/t/error-while-creating-certificate/131422)
Best is to give it a bit more time and re-try.

> Thanks for the report! I believe this is a symptom of heavy load. We’re looking at ways to improve performance.

**Comment by mmccollum2** [comment]
Letsencrypt problem has been resolved!

> As pointed out by @petzsch in our [community cha](https://chat.btcpayserver.org/btcpayserver/pl/smeo9wpa738k9rayq7a9dwqaie)t, this seems to be the [performance issue of Let's Encrypt.](https://community.letsencrypt.org/t/error-while-creating-certificate/131422)
> Best is to give it a bit more time and re-try.
> 
> > Thanks for the report! I believe this is a symptom of heavy load. We’re looking at ways to improve performance.
