### ISSUE TITLE
RTL (Ride the Lightning) link gets 404 Error (with lovely pic of Nicolas Dorier)

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#367]
I run my docker setup behind caddy reverse proxy.  Hence in BTCPay docker these env vars are set:

`BTCPAYGEN_EXCLUDE_FRAGMENTS:btcpayserver-nginx,nginx;nginx-https;btcpayserver-noreverseproxy`

I do not know if that is the cause, as everything else works perfectly.  But in `https://btcpay.mydomain.com/server/services/rtl/BTC` when I click the `You can go to Ride the Lightning server from your browser by clicking here` link, I get 404, and the URL remains like this:

https://btcpay.mydomain.com/rtl/api/authenticate/cookie?access-key=<LONG_KEY_HERE>

Do I need to open port 3000 or something?  Does anyone else running their own reverse proxy have RTL link working?  (Maybe it is not even my reverse proxy at all..)

**Comment by maltokyo** [comment]
Screenshot of error ;)  But seriously, can anyone share their thoughts with me?  Cant access lightning!

![image](https://user-images.githubusercontent.com/1388507/92321513-ecc75300-f02a-11ea-9d38-d8fc48897091.png)

**Comment by britttttk** [comment]
@maltokyo not sure about your reverse proxy setup but is your issue by chance related to this? https://github.com/btcpayserver/btcpayserver-docker/issues/346

**Comment by maltokyo** [comment]
Hi @britttttk I am using the latest and greatest version, so it cannot be https://github.com/btcpayserver/btcpayserver-docker/issues/346

I am not sure what else to try.

**Comment by maltokyo** [comment]
I was using caddy as a reverse proxy, as it is much more simple to set up and maintain.  But it just didn't work.  Switched back to the standard nginx built-in RP and now it all works.  

If anyone gets BTCPay Server running with Caddy as their RP on their home network, let me know!

**Comment by KonnikPahoni** [comment]
Having the same error on

http://192.168.11.164/rtl/api/authenticate/cookie?access-key=33cf60093a7ecf26769e055d1a87a0d117437c11f6bed23553b2540b67686989ef647621beb16637a73e44e622bbb37ac8bca10de17db2045d335cef233b9bd4

**Comment by sbounmy** [comment]
@maltokyo were you able to fix it with caddy ? we are using too and having the exact same issue

**Comment by sbounmy** [comment]
Update : it work now. it was missing reverse proxy to RTL

```
btcpay.hongbaob.tc {
    # RTL routing - MUST be before the catch-all
    reverse_proxy /rtl/* generated-bitcoin_rtl-1:3000

    # BTCPay Server web interface
    reverse_proxy btcpayserver:49392 {
....
    }
    
    # Lightning REST API
    reverse_proxy /clightning/* btcpayserver_clightning_bitcoin:3010 {
...
    }
    
    # Enable gRPC for Lightning
    reverse_proxy h2c://btcpayserver_clightning_bitcoin:9736 {
....
    }
}
```
