### ISSUE TITLE
Expose v2 LND REST API

### ISSUE THREAD

**Issue by danielalexiuc** [btcpayserver/btcpayserver-docker#368]
The "v2" LND REST API seems to be inaccessible - calls to any v2 endpoints return the response "Not Found".

For example:

GET /lnd-rest/btc/v1/getInfo
returns: 
{"version":"0.10.2-beta ... }

GET /lnd-rest/btc/v2/wallet/estimatefee/6
returns:
Not Found\n

See the LND v2 endpoints here:
https://api.lightning.community/#v2-wallet-estimatefee

**Comment by Kukks** [comment]
Transferred to the correct place

**Comment by Kukks** [comment]
From what I can tell, they should already be mapped correctly. 
https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L32

maybe you need to provide some additional build steps to LND when compiling a release

**Comment by danielalexiuc** [comment]
Ah yes I see - some of these endpoints are designated as 'experimental services' and need to be enabled with a compile time flag.

They are enabled in the official binaries, so it doesn't seem like much risk to enable them in btcpayserver too - can we do that?

https://api.lightning.community/#experimental-services

**Comment by danielalexiuc** [comment]
Actually no, there is another problem, /v2/router/send is also returning 'Not Found', but it is not an experimental service:

https://api.lightning.community/#v2-router-send

**Comment by danielalexiuc** [comment]
It looks like these REST endpoints were only exposed in LND v0.11.0-beta, so this may be resolved when LND is updated to that version:

https://github.com/lightningnetwork/lnd/pull/4251

**Comment by danielalexiuc** [comment]
All done. It's working. Thanks!
