### ISSUE TITLE
Cannot interact with c-lightning 

### ISSUE THREAD

**Issue by taxmeifyoucan** [btcpayserver/btcpayserver-docker#373]
I am running btcpay setup in Docker with default configuration following the docs. btcpay-update.sh says everything is up to date. c-lightning is running, it was successfully setup and working before. Now I have issues to interact with it. When I open RTL as usual, I can access it, see balances, channels etc but I am not able to do any action, buttons just don't react. Also, I wasn't able to connect to other services which are running - Spark, Charge server, REST, always got an error. When I execute correct command with ./bitcoin-lightning-cli.sh, nothing happens, I am waiting and then I have to kill it. 

Output of `docker logs --tail 100 btcpayserver_clightning_bitcoin` just repeats: 
```
UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 00000000000000000014ab944b2d4b209b9d81d16eed40882f08df93143e1224 0 exited with status 1
```
RTL logs are huge and mess, I can't copy it here but let me know if that would be helpful.

**Comment by NicolasDorier** [comment]
We run on pruned nodes, so this error is not really unexpected, but things should still work.
Can you wait a while? Does the error is always on the same block?

**Comment by taxmeifyoucan** [comment]
@NicolasDorier Yes, error is always with the same block and repeats every second in the logs. Now again:
```
2020-09-28T16:50:38.640Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 00000000000000000014ab944b2d4b209b9d81d16eed40882f08df93143e1224 0 exited with status 1
2020-09-28T16:50:39.658Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 00000000000000000014ab944b2d4b209b9d81d16eed40882f08df93143e1224 0 exited with status 1
2020-09-28T16:50:40.675Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 00000000000000000014ab944b2d4b209b9d81d16eed40882f08df93143e1224 0 exited with status 1

```

**Comment by NicolasDorier** [comment]
I need logs from RTL. This should work.

**Comment by taxmeifyoucan** [comment]
After updating to latest today, RTL started to work properly again. Sorry for not posting RTL logs but there wasn't anything technical/helpful, only sensitive information about funds etc.

**Comment by Alko89** [comment]
I have encountered this issue again. The error seems to be on a different block height as the one reported.

`UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000001afc2c9ef915b14d51f92938832734466a93d93f518bd7 0 exited with status 1`
