### ISSUE TITLE
Updating BTCPayserver with custom HTML & CSS in docker container

### ISSUE THREAD

**Issue by AMolosolof** [btcpayserver/btcpayserver-docker#376]
I have BTCPayServer running in docker container. I've made some changes to HTML/CSS in the Visual Studio and it runs smoothly on test environment (like described in this Video - https://www.youtube.com/watch?v=ZePbMPSIvHM).

What is the best way to update my server in the docker container with the latest changes?

I've tried to change BTCPayServer.Views.dll & BTCPayServer.Client.pdb with updated files directly in the Docker container, but after restarting (btcpay-restart.sh) I'm getting Error #502

**Comment by NicolasDorier** [comment]
Git clone your fork of btcpayserver, then use `docker build -f  amd64.Dockerfile -t "btcpayserver/btcpayserver:CURRENT_VERSION" .`

Then `btcpay-up.sh`. Replace CURRENT_VERSION by the btcpayserver version you are running (can get through `docker ps`)

During next update, it will remove your changes though.

**Comment by Kukks** [comment]
> Git clone your fork of btcpayserver, then use
> 
> ```
> docker build -f  amd64.Dockerfile -t "btcpayserver/btcpayserver:CURRENT_VERSION" .
> ```
> 
> Then `btcpay-up.sh`. Replace CURRENT_VERSION by the btcpayserver version you are running (can get through `docker ps`)
> 
> During next update, it will remove your changes though.

err, he most likely wants to build locally and then run on the docker instance:
* create a Docker hub account
* on your machine: run `docker login`
* go to root btcpayserver git folder 
* run `docker build -f  amd64.Dockerfile -t "YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION" . && docker push YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION`
* on your btcpay server machine, run `export BTCPAY_IMAGE="YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION"  `
*  run setup `. ./btcpay-setup.sh -i`

**Comment by AMolosolof** [comment]
Thanks for the quick reply!

After btcpay-up.sh I'm getting the error:
"ERROR: for btcpayserver  Cannot start service btcpayserver: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/app/docker-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project."

**Comment by AMolosolof** [comment]
> Git clone your fork of btcpayserver, then use
> 
> ```
> docker build -f  amd64.Dockerfile -t "btcpayserver/btcpayserver:CURRENT_VERSION" .
> ```
> 
> Then `btcpay-up.sh`. Replace CURRENT_VERSION by the btcpayserver version you are running (can get through `docker ps`)
> 
> During next update, it will remove your changes though.

Thanks for the quick reply!

After btcpay-up.sh I'm getting the error:
"ERROR: for btcpayserver  Cannot start service btcpayserver: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/app/docker-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project."

**Comment by AMolosolof** [comment]
It was a file permission issue for the cloned repo. Solved.

**Comment by winkcler** [comment]
Hello, I did the same process as mentioned above for our friend.

However I'm getting an error at build time.

![image](https://user-images.githubusercontent.com/4259380/126049579-7945a40a-ab31-4fde-9937-a817a4fd3c18.png)

**Comment by winkcler** [comment]
> > Git clone your fork of btcpayserver, then use
> > ```
> > docker build -f  amd64.Dockerfile -t "btcpayserver/btcpayserver:CURRENT_VERSION" .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then `btcpay-up.sh`. Replace CURRENT_VERSION by the btcpayserver version you are running (can get through `docker ps`)
> > During next update, it will remove your changes though.
> 
> err, he most likely wants to build locally and then run on the docker instance:
> 
> * create a Docker hub account
> * on your machine: run `docker login`
> * go to root btcpayserver git folder
> * run `docker build -f  amd64.Dockerfile -t "YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION" . && docker push YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION`
> * on your btcpay server machine, run `export BTCPAY_IMAGE="YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION"  `
> * run setup `. ./btcpay-setup.sh -i`

Hello, I did the same process as mentioned above for our friend.

However I'm getting an error at build time.

![image](https://user-images.githubusercontent.com/4259380/126049657-412ce3b4-02f2-4a97-9941-49b7cf5b7818.png)
