### ISSUE TITLE
Update PHP and WordPress in wooCommerce docker container

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver-docker#381]
Last update was over year and half ago, new versions of PHP and WordPress in the meantime. https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/opt-add-woocommerce.yml

**Comment by NicolasDorier** [comment]
which version is advised

**Comment by rockstardev** [comment]
@NicolasDorier 7.4 seems like current stable, so I would go with the latest within that branch.

Seems that's: 7.4.11 - https://www.php.net/downloads.php

**Comment by rockstardev** [comment]
@NicolasDorier bump

**Comment by rockstardev** [comment]
Needs tester on: https://github.com/btcpayserver/docker-woocommerce/pull/4
