### ISSUE TITLE
Bump Tor to 0.4.4.7

### ISSUE THREAD

**Issue by RiccardoMasutti** [btcpayserver/btcpayserver-docker#387]
https://blog.torproject.org/node/1921

**Comment by RiccardoMasutti** [comment]
New release: 4.4.6

https://blog.torproject.org/node/1952

**Comment by RiccardoMasutti** [comment]
New release: 0.4.4.7

https://blog.torproject.org/node/1990

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver-docker/commit/04c25883ef62a7877da7ce35fbecb4e6349d2c2f
