### ISSUE TITLE
Bump c-lightning to 0.9.1

### ISSUE THREAD

**Issue by jooray** [btcpayserver/btcpayserver-docker#388]
Some node operators told me that my node is spamming the network with payment attempts. It is probably because of AMP splitting payments to hundreds of small payments (I have seen this in spark, sending $26 in 20 payments - I don't even have 20 channels, so that's definitely a bug).

I am temporarily blacklisted because of spamming, just because I tried to send a few payments.

I see that btcpayserver-docker has 0.9.0 clightning, but there's 0.9.1 that includes:

"The sending of multi-part payments has seen a lot of work, covering more corner cases and generally becoming much more robust."

(from release notes).

I think it would be wise to bump c-lightning in btcpayserver-docker to 0.9.1

**Comment by Eskyee** [comment]
temporarily blacklisted because of spamming.... not a good look!!

**Comment by Eskyee** [comment]
https://github.com/ElementsProject/lightning/releases/tag/v0.9.1   seems to solve this

**Comment by jooray** [comment]
Yes.

https://github.com/ElementsProject/lightning/issues/3926

**Comment by Eskyee** [comment]
@rockstardev

**Comment by NicolasDorier** [comment]
chekcing

**Comment by NicolasDorier** [comment]
just did
