### ISSUE TITLE
Installation error with docker in Centos 7

### ISSUE THREAD

**Issue by jomagalo** [btcpayserver/btcpayserver-docker#400]
The installation works perfectly on Ubuntu 18 and 20 which has been the ones I have tried. But when trying to install it on a Centos 7 it doesn't let me execute the last instruction: `. ./btcpay-setup.sh -i`

When running:`. ./btcpay-setup.sh -i`

```
[root@axarquiainformatica btcpayserver-docker]# . ./btcpay-setup.sh -i
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
You must run this script inside the git repository of btcpayserver-docker
[root@axarquiainformatica btcpayserver-docker]#
```
The error seems to indicate that I am not in the indicated directory, when I am. It must be some nonsense of path. Any help would be appreciated.

**Comment by jomagalo** [comment]
I found the solution:
Edit the file: btcpay-setup.sh
Modify the lines: 41 and 46

`41 if ! git -C . rev-parse &> /dev/null || [ ! -d "Generated" ]; then`
`46 if ! git -C . rev-parse || [[ ! -d "Generated" ]]; then`

Replace uppercase "C" with lowercase "c" on both lines.

`41 if ! git -c . rev-parse &> /dev/null || [ ! -d "Generated" ]; then`
`46 if ! git -c . rev-parse || [[ ! -d "Generated" ]]; then`

**Comment by NicolasDorier** [comment]
thanks for that, can you make a PR?

**Comment by pavlenex** [comment]
Abandoned.
