### ISSUE TITLE
Bump Monero to 0.17.1.6

### ISSUE THREAD

**Issue by jooray** [btcpayserver/btcpayserver-docker#408]
0.17.1.6 mitigates an ongoing network attack on P2P.

[Fun read on the attack](https://sethsimmons.me/posts/moneros-ongoing-network-attack/
), someone is really pissed.

The main problem for btcpayserver users is that some malicious nodes report height two times farther than real block size and the wallet is waiting for sync to finish, but it never does. This update bans any node that reports higher height but refuses to respond with the block itself, should fix this and make Monero usable with btcpayserver again.

**Comment by astupidmoose** [comment]
https://github.com/btcpayserver/btcpayserver-docker/pull/407

This should fix. Just waiting for approval

**Comment by astupidmoose** [comment]
Monero has been bumped, unfortunately, the attack remains active and even the newest version doesn't help.

**Comment by sethsimmons** [comment]
The easiest solution for the attacks ATM is to use a ban-list of known-bad IP addresses, which he worked perfectly for me and others.

Is it possible to include the “—ban-list” flag and point to a file in the container?

The most up to date block file can be found here:

https://gui.xmr.pm/files/block.txt

**Comment by astupidmoose** [comment]
I came up with this hacky fix. It might be a good base for someone smarter than me to build off of in docker. 

1. Login to server, via SSH
2. nano $BTCPAY_DOCKER_COMPOSE
3. find "monerod_wallet:", under this line, there is a "entrypoint:" line, add the following to the end of this line: "--ban-list block.txt" (DO NOT add this to the wallet line, which is a few lines below)
4. change your directory to your BTCPay-docker directory (mine is ~/BTCPayServer/btcpayserver-docker)
5. run btcpay-up.sh to update the docker
6. "cd" into your root directory
7. type "wget https://gui.xmr.pm/files/block.txt"
8. type "docker cp block.txt btcpayserver_monerod:/block.txt"
9. Restart docker containers with "docker restart btcpayserver_monerod" and "docker restart btcpayserver_monero_wallet"
10. ??? profit!

**Comment by astupidmoose** [comment]
I made a hacky solution for this, but I don't know docker well enough to implement it permanently. If someone knows docker they might be able to jump off here. 

1. Login to server, via SSH
2. nano $BTCPAY_DOCKER_COMPOSE
3. find "monerod:", under this line, there is a "entrypoint:" line, add the following to the end of this line: "--ban-list block.txt" (DO NOT add this to the wallet line, which is a few lines below)
4. change your directory to your BTCPay-docker directory (mine is ~/BTCPayServer/btcpayserver-docker)
5. run btcpay-up.sh to update the docker
6. "cd" into your root directory
7. type "wget https://gui.xmr.pm/files/block.txt"
8. type "docker cp block.txt btcpayserver_monerod:/block.txt"
9. Restart docker containers with "docker restart btcpayserver_monerod" and "docker restart btcpayserver_monero_wallet"
10. ??? profit! 


I've done the above and my server is running issue free, BUT use at your own risk.

**Comment by jooray** [comment]
There's 0.17.1.7 that mitigates the ongoing network attack better. Could we bump?

**Comment by astupidmoose** [comment]
> There's 0.17.1.7 that mitigates the ongoing network attack better. Could we bump?

https://github.com/btcpayserver/btcpayserver-docker/pull/412

**Comment by astupidmoose** [comment]
> There's 0.17.1.7 that mitigates the ongoing network attack better. Could we bump?

I've been running 0.17.1.7 overnight and my node is still being attacked :(

**Comment by jooray** [comment]
What do you mean "still being attacked"? Height+2 and not synced?

**Comment by astupidmoose** [comment]
> What do you mean "still being attacked"? Height+2 and not synced?

Yes, unfortunately .7 doesnt seem to fix it

![image](https://user-images.githubusercontent.com/3916318/102239839-202c4000-3eac-11eb-8527-3fb956c2da90.png)

**Comment by sethsimmons** [comment]
That is without the ban-list, correct?

Are you able to run 'sync_info' against the node?

**Comment by astupidmoose** [comment]
> That is without the ban-list, correct?
Yes, I am currently running without a ban list

> Are you able to run 'sync_info' against the node?
Honestly, I have no clue how to do this within the docker install.
