### ISSUE TITLE
postgres image needs environment variables for auth

### ISSUE THREAD

**Issue by aggieben** [btcpayserver/btcpayserver-docker#409]
When I deployed to Azure directly from the templated linked in [the docs](https://docs.btcpayserver.org/AzureDeployment/), the postgres container did not start up successfully.  The error message in the logs was this:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

I was able to find that the generated docker-compose file (`~/Generated/docker-compose.generated.yml`) did not include either `POSTGRES_PASSWORD` or `POSTGRES_HOST_AUTH_METHOD`.  I'd suggest that the postgres docker fragment needs updating to include one of these, preferably `POSTGRES_PASSWORD`.

Workaround: update the generated docker-compose manually to set the auth method to trust.  I suspect btcpayserver would not work if a password were required.

**Comment by NicolasDorier** [comment]
Sorry for the inconvenience. If you run `btcpay-update.sh` it should work again.
I bumped recently postgres to from `postgres:9.6.6` to `postgres:9.6.20` not expecting breaking change for new installs...

**Comment by NicolasDorier** [comment]
Fixed by https://github.com/btcpayserver/btcpayserver-docker/commit/efec51f15956851c72dc5c6c58074b3f78429252
