### ISSUE TITLE
Monero broken after merging #419

### ISSUE THREAD

**Issue by sethsimmons** [btcpayserver/btcpayserver-docker#420]
Seems that v0.17.1.8 hasn't been pushed to Docker Hub since I pushed the version bump, which breaks Monero updates for all users:

Pulling monerod (btcpayserver/monero:0.17.1.8)...
ERROR: manifest for btcpayserver/monero:0.17.1.8 not found: manifest unknown: manifest unknown

Please let me know if something else is needed from my end to get it to build and push to DH.

**Comment by NicolasDorier** [comment]
Sorry about that, fixed it.

**Comment by NicolasDorier** [comment]
you need to run btcpay-update.sh
