### ISSUE TITLE
Unable to connect to host: Failed to connect before the deadline

### ISSUE THREAD

**Issue by vswee** [btcpayserver/btcpayserver-docker#43]
I've the BTCPay server up and running (fabulous bit of software by the way). It sits behind my apache server and as far as I can tell it works (https://btcpay.flat18.co.uk). SSL is a wildcard and appears to work just fine.

Following the instructions for linking the Zap client to BTCPay, I get the error in the title.

**Zap version 0.2.2-beta (0.2.2-beta.4225) (macOS)**

**BTCPay version  v1.0.2.103 Docker / Ubuntu 18.04LTS / Apache2**
![screenshot 2018-09-27 at 13 16 47](https://user-images.githubusercontent.com/2403100/46162905-a7ebec80-c257-11e8-8d05-059c9d3e0063.png)

![screenshot 2018-09-27 at 13 13 31](https://user-images.githubusercontent.com/2403100/46162789-462b8280-c257-11e8-8537-9e60e4e4d318.png)
![screenshot 2018-09-27 at 13 15 11](https://user-images.githubusercontent.com/2403100/46162870-85f26a00-c257-11e8-8c16-542ceabb833e.png)

**Comment by bitcoinshirt** [comment]
Can you do "test connection" for your Lightning Node in Store Settings > Lightning nodes (Experimental) > modify > test connection.

**Comment by vswee** [comment]
> Can you do "test connection" for your Lightning Node in Store Settings > Lightning nodes (Experimental) > modify > test connection.

![screen shot 2018-09-10 at 10 31 48](https://user-images.githubusercontent.com/2403100/46172829-7c2a3000-c272-11e8-85da-14af9a95344a.png)

**Comment by vswee** [comment]
> Can you do "test connection" for your Lightning Node in Store Settings > Lightning nodes (Experimental) > modify > test connection.

@bitcoinshirt Looks to be OK.
![screenshot 2018-09-27 at 16 28 00](https://user-images.githubusercontent.com/2403100/46172859-96640e00-c272-11e8-850e-deafa5849e5f.png)

**Comment by NicolasDorier** [comment]
I will soon update LND, maybe it is related.

**Comment by rockstardev** [comment]
I think it's apache, you have custom setup, right @vswee ?

Lots of interesting results if you Google:
https://www.google.com/search?q=failed+to+connect+before+deadline

**Comment by NicolasDorier** [comment]
> I've the BTCPay server up and running (fabulous bit of software by the way). It sits behind my apache server and as far as I can tell it works (https://btcpay.flat18.co.uk). SSL is a wildcard and appears to work just fin

Ok so you are using your own reverse proxy. In this case you need to configure it to route things to LND

**Comment by NicolasDorier** [comment]
Example in my config:
```
server {
        server_name btcpay.nicolas-dorier.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/btcpay.nicolas-dorier.com.crt;
        ssl_certificate_key /etc/nginx/certs/btcpay.nicolas-dorier.com.key;
        ssl_dhparam /etc/nginx/certs/btcpay.nicolas-dorier.com.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/btcpay.nicolas-dorier.com.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://btcpay.nicolas-dorier.com;
        }
        location /lnrpc.Lightning {
                 grpc_pass grpcs://lnd_bitcoin:10009;
        }
}
```

**Comment by vswee** [comment]
Thanks @rockstardev and @NicolasDorier.

Setting up the equivalent proxy entry in my virtual host in apache for graces://lnd... didn't produce any changes to my issue, unfortunately. 

I'm trying to work out how to debug this but just to clarify, the required ports are, I assume, already established/opened by btcserver even when setup with PROXY=none, and only require routing by apache?

There are probably considerations to make for the protocol. My research begins.

**Comment by vswee** [comment]
It appears that this and all my other issues posted on slack result from a bug where btcpay server installs nginx even when reverse proxy is set to none. 
The nginx installation is not obvious but some clues which I overlooked are:

1. output errors relating to ports 80, 443.
2. inability to reverse proxy to other docker containers, i.e. the lnd port etc. in a manner similar to that for the web interface.

This doesn't seem to be likely to be a widespread issue as few users seem to opt for installations without nginx.

**Comment by NicolasDorier** [comment]
anything I can do to make it a bit easier?

**Comment by vswee** [comment]
@NicolasDorier It's really a docker nuance that I'm not accustomed to. BTCPay is grand as it is.

It might not be worth your while to include instructions in the docs to ensure a user sets up their reverse proxy to the docker IP. 

Perhaps a single line mentioning that the docker exposed ports are bound to a discrete subnet and that this needs to be considered for custom reverse proxying.

This wasn't obvious to me even even after doing `docker ps`.

**Comment by NicolasDorier** [comment]
@vswee I think I already documented the external ports. The internal ports are not meant to be used for reverse proxy, as the docker-compose you use is the one without reverse proxy.

What I can do is exposing gRPC port to the outside though.

**Comment by vswee** [comment]
The ports are documented, yes. Perhaps my installation is terribly unusual but I struggled with the ports until I tried `docker inspect generated_btcpayserver`. I hadn't understood before that docker containers are networked via a docker subnet like 17x.xxx.xxx.xxx

It's not a BTCPay shortcoming just something that could do with clarification with regard to docker installs.

Great job on BTCPay server. You get an extra pat on the back for making it freely available too. 
Cheers @NicolasDorier

**Comment by guiguy2018** [comment]
Hi vswee, could you provide more information on how you got the zap wallet to connect?  I'm having a similar "unable to connect" problem where I have an nginx reverse proxy to BTCPay docker running on a separate Ubuntu VM.  I haven't touched the docker nginx settings and BTC payments work fine, but not lighning.   What other ports do I need exposed to the BTC Pay server?

**Comment by NicolasDorier** [comment]
@guiguy2018 here is the typical nginx config that btcpay use if nginx is same machine as btcpay.

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Prevent Nginx Information Disclosure
server_tokens off;
# Default dhparam
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 443 ssl http2;
        access_log /var/log/nginx/access.log vhost;
        return 503;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/default.crt;
        ssl_certificate_key /etc/nginx/certs/default.key;
}
# mainnet.demo.btcpayserver.org
upstream mainnet.demo.btcpayserver.org {
                                ## Can be connected with "generated_default" network
                        # generated_btcpayserver_1
                        server 172.18.0.8:49392;
}
server {
        server_name mainnet.demo.btcpayserver.org;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name mainnet.demo.btcpayserver.org;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/mainnet.demo.btcpayserver.org.crt;
        ssl_certificate_key /etc/nginx/certs/mainnet.demo.btcpayserver.org.key;
        ssl_dhparam /etc/nginx/certs/mainnet.demo.btcpayserver.org.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/mainnet.demo.btcpayserver.org.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://mainnet.demo.btcpayserver.org;
        }
                                location /lnrpc.Lightning {
                                        grpc_pass grpcs://lnd_bitcoin:10009;
                                }
                                location /lnd-rest/btc/ {
                                        rewrite ^/lnd-rest/btc/(.*) /$1 break;
                                        proxy_pass http://lnd_bitcoin:8080/;
                                }
}
```

**Comment by guiguy2018** [comment]
Thanks @NicolasDorier , the problem is my nginx reverse proxy server is on a different machine and I can't figure out how to get grpc_pass grps://lnd_bitcoin:10009 to work.

**Comment by NicolasDorier** [comment]
@guiguy2018 I can't really help you sorry. It took me a while to make it works correctly within the docker.

**Comment by guiguy2018** [comment]
@NicolasDorier ok, thanks anyway.  Can you tell me if  gRPC port is exposed to the outside?  Or can that be done?
