### ISSUE TITLE
RTL Loop Out Error 500

### ISSUE THREAD

**Issue by pardus79** [btcpayserver/btcpayserver-docker#468]
After update to v1.1.0.0 RTL gives the following error when I attempt to Loop Out:

ERROR
Error Code
500
Error Message
Unknown Error
API URL
./api/lnd/loop/out/termsAndQuotes

**Comment by NicolasDorier** [comment]
ping @rockstardev

**Comment by maltokyo** [comment]
I got this same error until I restarted a couple of times and after some lapsed time.  I think it takes some time to generate the loop macaroons etc.

**Comment by astupidmoose** [comment]
I get the same, but my LND is very old. Its possible this error is simply because our instances are not compatible due to age.

**Comment by maltokyo** [comment]
Mine is also very old ;)

**Comment by AryanJ-NYC** [comment]
I'm getting something similar. I wonder if it's at all related to https://github.com/btcpayserver/btcpayserver/issues/2502?

**Comment by rockstardev** [comment]
No, this is different type of error - has to do with old LND installations that need to regenerate certificates and macaroons. I'm working on making it happen; so people don't need to redeploy LND.

**Comment by rockstardev** [comment]
@maltokyo @pardus79 I'll have another PR as soon as #478 is merged and then will would appreciate you testing. Hopefully tonight if I organize with @NicolasDorier.

**Comment by rockstardev** [comment]
@maltokyo @pardus79 PR ready, please test on your instance if this resolves problems

**Comment by maltokyo** [comment]
Unfortunately (?) somehow it resolved itself for me after some time.

**Comment by rockstardev** [comment]
@maltokyo I know what's the problem on your server and you can expect intermittent problems until the next update. If you do manage to test out PR do let me know; would appreciate it.

**Comment by pardus79** [comment]
Not sure if I can test this fix out. I'm running Btcpay for my store checkout and I'm not comfortable enough with docker/git to update from the PR on my production setup. 

Is there a straightforward way to do so?

**Comment by NicolasDorier** [comment]
Same here,

```
ERROR: Loop(327) => List Swaps Error: {"name":"RequestError","message":"Error: connect ECONNREFUSED 172.18.0.9:8081","cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.18.0.9","port":8081},"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.18.0.9","port":8081},"options":{"url":"https://lnd_bitcoin:8081/v1/loop/swaps","rejectUnauthorized":false,"json":true,"headers":{"Grpc-Metadata-macaroon":""},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
Loop macaroon Error: {"errno":-2,"syscall":"open","code":"ENOENT","path":"/etc/lndloop/loop.macaroon"}

ERROR: Loop(146) => Loop Out Terms Error: {"name":"RequestError","message":"Error: connect ECONNREFUSED 172.18.0.9:8081","cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.18.0.9","port":8081},"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.18.0.9","port":8081},"options":{"url":"https://lnd_bitcoin:8081/v1/loop/out/terms","rejectUnauthorized":false,"json":true,"headers":{"Grpc-Metadata-macaroon":""},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
```
