### ISSUE TITLE
Replace container links with networks

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-docker#47]
Containers links are a legacy docker feature and are discouraged from being used. The substitute are networks.
I've done a test on btcpay.nbitstack.com and am running btc on am modified compose with networks

Ideally, we have 2 networks: `internal` and `web` with only the front facing services in `web`.

**Comment by NicolasDorier** [comment]
I don't understand.  `links` is used to setup the containers dependency and make sure as if a container get updated, containers depending on it get restarted.

**Comment by Kukks** [comment]
https://stackoverflow.com/questions/39173670/are-docker-links-deprecated

We can also use `depends_on` for that dependency afaik
