### ISSUE TITLE
Wrong Repo's on Debian

### ISSUE THREAD

**Issue by seccho** [btcpayserver/btcpayserver-docker#48]
May you can check the distro and add the correct repo's?

` add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"
    else
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"`

Thank's 4 the great work!

**Comment by NicolasDorier** [comment]
Can you make a PR doing this? I am a linux noob.

**Comment by Kukks** [comment]
I think we should be using the official linux quick installer @NicolasDorier 

```
apt-get install curl
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh
```

**Comment by NicolasDorier** [comment]
@Kukks ACK
