### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS after 1.1.1 upgrade

### ISSUE THREAD

**Issue by lucidddreams** [btcpayserver/btcpayserver-docker#482]
This page isn’t workingpayments.vcashpay.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by chaycee** [comment]
i also have this issue, every time after install. just after a while it stops working

**Comment by dennisreimann** [comment]
This is most likely an error on the reverse proxy level, please reopen with more details (server type and configuration as well as logs) if this is still a problem.
