### ISSUE TITLE
BTCPay Server with Feathercoin on a Raspberry Pi 4

### ISSUE THREAD

**Issue by tefica** [btcpayserver/btcpayserver-docker#493]
Hi, I did try to deploy BTCPay Server with only the FTC option on a Raspberry Pi 4 (Raspbian 10).
Following your instruction I have configured my Rpi (ufw, ssl,...), and setup the environment variables for Feathercoin :

```
sudo su -
cd
git clone https://github.com/btcpayserver/btcpayserver-docker
cd btcpayserver-docker

export BTCPAY_HOST="raspberrypi.local"
export REVERSEPROXY_DEFAULT_HOST="$BTCPAY_HOST"
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="ftc"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-more-memory;opt-add-configurator"
export BTCPAY_ENABLE_SSH=true
export BTCPAY_ADDITIONAL_HOSTS="btcpay.mydomain.fr,btcpay.local"

. ./btcpay-setup.sh -i
```

After the setup I had the BTCPay Server working but Syncing Stuck at :
```
NBXplorer headers height: 0
The node is starting...
```

After that in parallel on the same machine I have built and run omnifeather-qt.
Then now independently I have a Feathercoin blockchain fully synched with an omnifeather-qt node running.

I have contacted the Feathercoin Dev team and they told me that I will have to install the feathercoind for Raspbian 10 but their repository have some problem at the moment with the Raspbian_10 version (may be soon fixed...)

Then my goal would be to connect the BTCPay Server to my existing Feathercoin blockchain...

I have read your doc "How to deploy BTCPay Server alongside existing Bitcoin node" and also how to create a symbolic link for the existing data. I would like to do it for the Feathercoin, I suppose I will have to create a feathercoin.custom.yml but I have no documentation (only for the bitcoin.custom.yml)...

I'm writing here to have your opinion and if you can give me some advices to have it working.

Thanks for your support
Best Regards

**Comment by tefica** [comment]
Hi :), 
Reminder : FTC syncing got stuck on BTCPay Server. 
Then : I tried to independently install the Feathercoin Core…

 I bring about some change I did in my situation :

- I have independently installed the last Feathercoin Core 0.19.1 (with feathercoind) for raspbian_10 
- …Well Synced
- Stopped the feathercoin node
- Stopped BTCPay Server (btcpay-down.sh)
- Created a symlink between the generated_feathercoin_datadir/_data and my feathercoin data directory (checked the symlink is well redirecting to my .feathercoin folder)
- Start the feathercoind -server...
- Then start BTCPay Server (btcpay-up.sh)
- BTCPay Server is always reporting : 
```
NBXplorer headers height: 0 
The node is starting…
```

Then now I have :

- The BTCPay Server installed
- The Feathercoin (0.19.1) full node installed and well synced
- A symlink redirecting the generated_feathercoin_datadir/_data to my .feathercoin folder

BTCPay Server still can’t link to the Feathercoin…

I have tried :

```
 cd btcpayserver-docker
~/btcpayserver-docker# feathercoin-cli.sh getblockcount
```
but returns :

`Error response from daemon: Container 09d9d22eed4a35c2a329df53f9fa1b4807a30ccdf98bf52e8a20a718455e21ea is restarting, wait until the container is running`

Thank you for your support
Best Regards

**Comment by slakov** [comment]
ping

**Comment by tefica** [comment]
Hi :)
After investigation and a Feathercoin Dev Team connection it seems that we need a Feathercoin docker for arm platforms (I suppose arm32v7 and arm64v8)...

Thank you for your support
Best Regards
