### ISSUE TITLE
Backup script is not working and restoration process is not documented

### ISSUE THREAD

**Issue by franciscopaniskaseker** [btcpayserver/btcpayserver-docker#496]
**Describe the bug**
- backup.sh is not fully working
- restoration process is not document

**To Reproduce the bug**
1. execute backup.sh
2. postgresql dump will fail
3. no procedure or script to do restoration

**Expected behavior**

1. create backup
2. intall a new server
3. restore the backup

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.1.2.0
- Deployment Method: docker
- Browser: chrome and safari, but they are not related with the problem

**Logs (if applicable)**
no

**Setup Parameters**
default parameters with just the domain changed

**Additional context**
Is clear for me that backup script stop the btcpayserver service, but not the docker, compress some directories with some exceptions, do postgresql dump and compress together with the backup. Based on that, I suppose that restorarion process will be the same: stop btcpayserver, extract the files inside volumes directory and start the service. I have some questions that I think will help a lot the btcpay community:

1.  backup.sh is failing to dumo the postgresql database. (bug)
2. if there is a backup.sh, why do not offer restore.sh?
3. supposing that backup.sh can dump the postgresql database; if I extract the files and recover the postgresql, is it enough?
4. as it is using docker, why I can not just stop btcpayserver service and docker service and move entire /var/lib/docker to the new server? Here I am more concerned about migration best practices. I understad 
5. is really necessary to dump posgresql database if in the new server i have the same postgresql version? because docker volumes will contain all postgresql data.
6. Can someone enumerate safe steps to dump the data and recover in the new server? For me is clear when we are using docker volumes, you just have to be concerned about the volumes. But I tested this and did not work.
7. Do I need to wait the btc sync to do the migration (export and import the backup)? I read some users saying that in btcpayserver git and i do not see a reason to do that.
8. Can someone the safe way to dump and import postgresql? I understand this is just a docker/postgresql, but at the same time the official backup.sh is not working.
9. Which is the correct way to change the btcpayserver image? i am doing systemctl stop btcpayserver, ./btcpay-update.sh and then systemctl start btcpayserver. I tried to use ./btcpay-restart.sh, but I started to see nginx 502 errors.  This procedure must be clear to backups be realiable.

I read a lot of issues and related sites with btcpayserver gits and I do not think backup, migration and restoration process are clear for everyone. I am here to test everything and give good feedbacks. I did not have success yet with migrations, but I am sure the most of people are not just relying in cloud snapshots.

**Comment by franciscopaniskaseker** [comment]
one comment:
```bash
docker exec $(docker ps -a -q -f "name=postgres_1") pg_dumpall -c -U postgres >
```

I manually executed this line (from btcpay_dump_db() of helpers.sh) and it worked. so probably there is some problem with the scripts and not with the command that do the dump).

**Comment by franciscopaniskaseker** [comment]
I realized other thing: you need to copy the ssh public key from old server (/root/.ssh/authorized_keys) to the new server (same file) or you will get ssh internal error, because the data that you migrate will use old ssh key pair.

**Comment by Goro2030** [comment]
I have the exact same question ... how do I restore the server into a new box?
