### ISSUE TITLE
 BTC Lightning Node Unavailable

### ISSUE THREAD

**Issue by mass34** [btcpayserver/btcpayserver-docker#497]
Hello. 
    If you do not have a store, create one.
    Store > Settings > Lightning > Modify
    Select "Use internal node"
    Click "Save"
    See "BTC Lightning node updated" message
    Make sure it is enabled
when you press "Public Node Info " I got  ` BTC Lightning Node
Unavailable`
install btcpayserver-docker
BTC wallet on/Fully synchronized 
What am I doing wrong?

**Comment by pavlenex** [comment]
Restart, or check logs of your LN node.

**Comment by mass34** [comment]
Old. :)
**btcpay**.my_domane.com

Thank you check logs
