### ISSUE TITLE
> > Git clone your fork of btcpayserver, then use

### ISSUE THREAD

**Issue by winkcler** [btcpayserver/btcpayserver-docker#498]
> > Git clone your fork of btcpayserver, then use
> > ```
> > docker build -f  amd64.Dockerfile -t "btcpayserver/btcpayserver:CURRENT_VERSION" .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then `btcpay-up.sh`. Replace CURRENT_VERSION by the btcpayserver version you are running (can get through `docker ps`)
> > During next update, it will remove your changes though.
> 
> err, he most likely wants to build locally and then run on the docker instance:
> 
> * create a Docker hub account
> * on your machine: run `docker login`
> * go to root btcpayserver git folder
> * run `docker build -f  amd64.Dockerfile -t "YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION" . && docker push YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION`
> * on your btcpay server machine, run `export BTCPAY_IMAGE="YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION"  `
> * run setup `. ./btcpay-setup.sh -i`

Hello, I did the same process as mentioned above for our friend.

However I'm getting an error at build time.

![image](https://user-images.githubusercontent.com/4259380/126049657-412ce3b4-02f2-4a97-9941-49b7cf5b7818.png)

_Originally posted by @winkcler in https://github.com/btcpayserver/btcpayserver-docker/issues/376#issuecomment-881961646_

**Comment by Kukks** [comment]
If you are using altcoins (anything other than BTC currency code,), you need to build the docker image with an argument:
```
docker build -f amd64.Dockerfile --build-arg CONFIGURATION_NAME=Altcoins-Release -t "YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION"
```

**Comment by winkcler** [comment]
> If you are using altcoins (anything other than BTC currency code,), you need to build the docker image with an argument:
> 
> ```
> docker build -f amd64.Dockerfile --build-arg CONFIGURATION_NAME=Altcoins-Release -t "YOURDOCKERUSERNAME/btcpayserver:CUSTOMVERSION"
> ```

Hello Kukks, thanks for the efficient reply, I managed to do it. But now I have another problem, when I use my image created from the docker, when I send Cryptocurrencies, the button "Sign transaction" is modified, preventing me from signing as Hot Wallet, simply add the options to my image.

Below are the photos.

With the original BTCpayServer image:

![image](https://user-images.githubusercontent.com/4259380/126165504-35309821-ee81-497e-9f84-bb59245ec692.png)

With my modified docker image:

![image](https://user-images.githubusercontent.com/4259380/126165579-7b0797e8-438c-476f-b47c-9acfa9802beb.png)
