### ISSUE TITLE
BTCPayServer IPN

### ISSUE THREAD

**Issue by Azocki** [btcpayserver/btcpayserver-docker#501]
Hey, I really want to get started with making my own Payment Gateway with BTCPayServer, but I can't seem to find any explanations on the IPN (I am working with Python). I figured out that the IPN sends a POST Request and I made a simple Python Flask Application to post the data too, but every time there is no data posted when making a purchase just comes in as a "None". Also, how would I create invoices via python? Should it just be basic requests post? Would appreciate a response! Thanks.

**Comment by pavlenex** [comment]
Question like this should be asked on chat.btcpayserver.org
