### ISSUE TITLE
everything was good until yesterday on my server now i got this?? what's wrong 

### ISSUE THREAD

**Issue by mccolister1017** [btcpayserver/btcpayserver-docker#502]
![btc error](https://user-images.githubusercontent.com/36525169/127743967-a792cfce-1a0e-4528-a4c0-36a1c75807d8.png)

any fix ???

**Comment by mccolister1017** [comment]
it's locked like this for hours

**Comment by pavlenex** [comment]
Restart your server and please don't open issues for tech support, use chat.btcpayserver.org
