### ISSUE TITLE
Server not accessible on https

### ISSUE THREAD

**Issue by ccdle12** [btcpayserver/btcpayserver-docker#51]
## Background
I've deployed the server using docker-compose and the front-end is accessible via http. The issues are the links for the css are expecting https, resulting in the front-end is displaying correctly and nginx returns 500 errors when trying to access `https://<domain>`

## Your environment
* Ubuntu 18.04 x64

## Steps to recreate
```
apt-get update && apt-get install -y git

git clone https://github.com/btcpayserver/btcpayserver-docker
cd btcpayserver-docker

export BTCPAY_HOST="8.9.5.37"
export NBITCOIN_NETWORK="testnet"
export LIGHTNING_ALIAS="myalias"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="lnd"

export ACME_CA_URI="https://acme-staging.api.letsencrypt.org/directory"
ssh-keygen -t rsa -f /root/.ssh/id_rsa_btcpay -q -P ""
echo "# Key used by BTCPay Server" >> /root/.ssh/authorized_keys
cat /root/.ssh/id_rsa_btcpay.pub >> /root/.ssh/authorized_keys
export BTCPAY_HOST_SSHKEYFILE=/root/.ssh/id_rsa_btcpay

export BTCPAY_PROTOCOL=https
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-s"

. ./btcpay-setup.sh -i
```
## Expected behaviour
Access the front-end on https.

## Actual behaviour
Unable to access the front-end on https and only http which results in broken css links.

**Comment by NicolasDorier** [comment]
`BTCPAY_HOST` should be a domain that you control, else it will not work.

**Comment by ccdle12** [comment]
@NicolasDorier Thanks for the help.

**Comment by NicolasDorier** [comment]
You can update it that way:

```
export BTCPAY_HOST="btcpay.example.com"
. ./btcpay-setup.sh -i
```

Or you can use `. changedomain.sh btcpay.example.com`

**Comment by urza** [comment]
Hello,
I have exactly the same problem as described in this issue by @ccdle12 
I used the same docker installation, but did these steps differently compared to @ccdle12:

1. I used domain in `BTCPAY_HOST` instead of IP address, so that is correct
2. During installation, I forgot to do the letsencrypt commands:

```
export ACME_CA_URI="https://acme-staging.api.letsencrypt.org/directory"
ssh-keygen -t rsa -f /root/.ssh/id_rsa_btcpay -q -P ""
echo "# Key used by BTCPay Server" >> /root/.ssh/authorized_keys
cat /root/.ssh/id_rsa_btcpay.pub >> /root/.ssh/authorized_keys
export BTCPAY_HOST_SSHKEYFILE=/root/.ssh/id_rsa_btcpay
```
(because this part is not explicitly mentioned in https://github.com/btcpayserver/btcpayserver-docker/Readme.md so I missed it).

After reading this issue I did the commands above and run 
`. ./btcpay-setup.sh -i` hoping it would fix my https issue, however no effect. When I try to access btcpayserver over https it responds with ngix 500 server error. If I access it on http, it results in broken css links.

**Comment by NicolasDorier** [comment]
`export ACME_CA_URI="https://acme-staging.api.letsencrypt.org/directory"` is incorrect, should be
`export ACME_CA_URI="https://acme-v01.api.letsencrypt.org/directory"` or just keeping it empty or unset.

**Comment by NicolasDorier** [comment]
You need both port 80 and 443 open.

**Comment by urza** [comment]
I changed the export for ACME_CA_URI and rerun the setup -i again. The script seems happy, no erros, ending with ptcpayserver running, however the results are the same.

We have port forwarding for this VM like this: 8088 to 80 and 40443 to 443.

When I go to https://btcpay.ourdomain:40443/ I get the ngix 500 internal server error, when I go to https://btcpay.ourdomain:8088/ I see btcpayserver homepage without css styles.

Are there any logs I could provide you so you know more?

Could the issue be related to the fact that we run btcpayserver on subdomain and not the main domain?

**Comment by NicolasDorier** [comment]
you need to use 80 and 443, there is no other way.

**Comment by borcherta** [comment]
Tried everything and still getting the 500 error. I am using a dyndns.org account for not having a fixed IP. Could this be the problem, I am stuck.
Thanks

**Comment by borcherta** [comment]
Hmm, I am not getting any error during the entire installation procedure, all went pretty smooth.
Inside my home network …. shouldn’t I be able to get any webpage from the PI on port 442 or 80? Its always either “cant connect” or the “500 gnix error”.
I also saw that my netgear home router does not allow any port forwarding on port 80, so I was trying to map 88 to 80. Same outcome.
Anything else I can try before I have to give up?
Thanks

**Comment by NicolasDorier** [comment]
You NEED pour 80. Your problem is that your server is trying to get a certificate but don't manage for some reasons.

This will give you some insight:
```bash
docker logs letsencrypt-nginx-proxy-companion
```
