### ISSUE TITLE
Can't pay with my local lightning node. (RouteHints)

### ISSUE THREAD

**Issue by Knaackee** [btcpayserver/btcpayserver-docker#529]
After scanning the QR-Code (lightning mode), I receive the following message: 

“This invoice was created by a private node that can't be reacted. To reach it, the invoice must include extra data (RouteHints). This issue can only be fixed by the invoice creator”.

How can I enable it?

I am fairly new to lightning: 
Should I enable it? What is the recommended way?

Thanks in advance!

**Comment by pavlenex** [comment]
Please ask in chat.btcpayserver.org this isn't a place to ask LN questions.
