### ISSUE TITLE
Connect a hardware wallet :  Error of the websocket while connecting to the backend.

### ISSUE THREAD

**Issue by LoulouCrypto** [btcpayserver/btcpayserver-docker#530]
Hello i have a issue with the hardware wallet connect 
When i try to add a wallet it say me this : 
Error of the websocket while connecting to the backend. 

I have the BTCPAY vault install 

I use cloudflare DNS is it a problem ? 

Thx

**Comment by pavlenex** [comment]
Please post here with relevant info https://github.com/btcpayserver/BTCPayServer.Vault/issues/new?assignees=&labels=&template=----bug-report-.md&title=
