### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by LoulouCrypto** [btcpayserver/btcpayserver-docker#531]
Hello 
I try to add opt-add-btctransmuter
After install it it put me a error when i whant to connect : ERR_TOO_MANY_REDIRECTS

I try to fully uninstall but nothing

any help ?

**Comment by LoulouCrypto** [comment]
Maybe a fix using full encryption in cloudflare

**Comment by LoulouCrypto** [comment]
No new ? i have to use flexible encryption but still ERR_TOO_MANY_REDIRECTS

**Comment by pavlenex** [comment]
This should be asked in transmuter repo.
