### ISSUE TITLE
error 504 in RTL or thunderhub

### ISSUE THREAD

**Issue by sendbitcoin** [btcpayserver/btcpayserver-docker#543]
various actions give 504 errors. doing update channel fees i can reproduce the error

i've updated, restarted and rebooted

BTCPayServer v1.2.4.0

![2021-10-23 18_36_53-RTL](https://user-images.githubusercontent.com/60074674/138564608-12e5729f-acb2-4674-ae55-1a046e5e2041.png)

`
..."response":{},"statusCode":504,"bodyText":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"},"message":"JSON.parse: unexpected character at line 1 column 1 of the JSON data"}`

**Comment by NicolasDorier** [comment]
did you try to restart all `btcpay-restart.sh` ? That's weird it says `nginx` but there is no nginx. In the middle.

**Comment by sendbitcoin** [comment]
i tried both restart btcpay (from maintenance page) and complete reboot

**Comment by sendbitcoin** [comment]
this is what i see in nginx log when i try to update a channel fee policy:


2021/11/19 13:53:11 [error] 8#8: *208 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XXX.XXX.XXX.XXX server: btcpay.sendbitcoin.lol, request: "POST /rtl/api/lnd/channels/chanPolicy HTTP/2.0", upstream: "http://XXX.XXX.XXX.XXX:3000/rtl/api/lnd/channels/chanPolicy", host: "btcpay.sendbitcoin.lol", referrer: "https://btcpay.sendbitcoin.lol/rtl/lnd/connections/channels/open"
btcpay.sendbitcoin.lol XXX.XXX.XXX.XXX - - [19/Nov/2021:13:53:11 +0000] "POST /rtl/api/lnd/channels/chanPolicy HTTP/2.0" 504 160 "https://btcpay.sendbitcoin.lol/rtl/lnd/connections/channels/open" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0"

**Comment by sendbitcoin** [comment]
after updating btcpayserver to 1.4.5 this issue seems to be fixed. I will reopen or create a new issue should i have it again.
