### ISSUE TITLE
feerate increased by a million times after update

### ISSUE THREAD

**Issue by sendbitcoin** [btcpayserver/btcpayserver-docker#546]
feerate before update of btcpayserver was 69 (0.0069%)

after update it's 69000000 (6900%)

updated from 1.2.4 to 1.3.1

![2021-10-30 14_18_14-RTL](https://user-images.githubusercontent.com/60074674/139532651-35d31ac1-6306-4923-8f95-56d8d49a76de.png)

**Comment by NicolasDorier** [comment]
The version of btcpay isn't related to RTL.
I will try to update RTL to latest version see if it solves

**Comment by NicolasDorier** [comment]
We are actually already in the latest version of RTL.

**Comment by NicolasDorier** [comment]
Can you open an issue on https://github.com/Ride-The-Lightning/RTL ?
This may also be a bug from LND, but they might be able to suggest ways to find out.
