### ISSUE TITLE
Feature Request - Add Monero to opt-save-storage to run pruned node

### ISSUE THREAD

**Issue by CryptoGrampy** [btcpayserver/btcpayserver-docker#557]
https://github.com/btcpayserver/btcpayserver-docker/blob/ee2c3f2fcd358bbd8118206098741b4a47aea37f/docker-compose-generator/docker-fragments/opt-save-storage.yml#L5

Monero (monerod) can be run in pruned node, which drops the node size down by about 2/3 with the --prune-blockchain flag.  There aren't really variable sizes that can be used for a pruned node in Monero, so I think opt-save-storage.yml is probably the best place (not 100% sure though). As part of this feature request, Monero should be added to opt-save-storage and BITCOIN_EXTRA_ARGS should be added to the Monerod environment image fragment as it exists in most if not all of the other 'altcoin' fragments.  This will also make Monero env overrides much more in line with the rest of BTCPayServer.

**Comment by CryptoGrampy** [comment]
Tagging @astupidmoose and @sethforprivacy :smile:

**Comment by astupidmoose** [comment]
Won't be something I'm doing. I prefer a full node on each currency, but you guys are welcome to add something like this for your own purposes :)

**Comment by CryptoGrampy** [comment]
> Won't be something I'm doing. I prefer a full node on each currency, but you guys are welcome to add something like this for your own purposes :)

Well then you might be interested to know that it's actually currently hard-coded to prune the blockchain in the Monero fragment... and you're probably running a pruned XMR node :eyes:

**Comment by astupidmoose** [comment]
Wow, I did not know that! Lol

**Comment by CryptoGrampy** [comment]
@astupidmoose Just opened a PR.  Feel free to review/edit!  :pray:

**Comment by sethforprivacy** [comment]
Thanks for taking this initiative, @CryptoGrampy! Will be good to provide the easy option for pruned -- I defaulted the fragment to pruned as there is no real reason besides altruism a merchant *needs* to run a full node, and wanted to lessen the burden on those who just run the defaults and accept Monero.

Will be glad to have it this way instead, especially using the native setting in BTCPayServer. Great work!

**Comment by Alumniminium** [comment]
how do I enable pruning? I just deployed BTCPay and its been syncing for a day...

**Comment by sethforprivacy** [comment]
Pruning is still the default, no need to change anything -- just give it time and you can watch the status by running this command on the CLI:

```
docker exec -ti btcpayserver_monerod monerod status
```
