### ISSUE TITLE
Instructions without btcpay-setup.sh

### ISSUE THREAD

**Issue by ammmir** [btcpayserver/btcpayserver-docker#588]
Can we get instructions without `btcpay-setup.sh` - I don't want to run a script that installs random things. Ideally, a pure docker-compose only solution would be nice.

**Comment by NicolasDorier** [comment]
`btcpay-setup.sh -i` does 2 things:
* Generate a docker-compose based on your options
* Put settings in a env file for docker to use
* Run the docker-compose

So if you want just a docker-compose, just run btcpay-setup.sh -i, and extract `cat $BTCPAY_DOCKER_COMPOSE` and `cat $BTCPAY_ENV_FILE`.
