### ISSUE TITLE
[feature request] - Configuration option to specify volume mount for Bitcoin datadir

### ISSUE THREAD

**Issue by ccdle12** [btcpayserver/btcpayserver-docker#61]
This is a feature I've hardcoded into the generated docker-compose file, to volume mount the Bitcoin datadir to a persistent disk.

It would be great if there was a fragment or configuration that could let users persist the chaindata to another directory instead of the default path of the docker volume mounts.

**Comment by NicolasDorier** [comment]
Why not just using symlinks?

**Comment by ccdle12** [comment]
To be fair, I havn't tried symlinking with this project. 

In the past I've found docker and symlinks not to play nice together, I can try it out in a test environment and comment here if it was un/successful.

**Comment by ccdle12** [comment]
Thanks for the LunaNode link, it looks really interesting, unfortunately I'm working with a company that already has a tech stack that needs to be used.

**Comment by NicolasDorier** [comment]
They are using the same stack as yours.

**Comment by ccdle12** [comment]
I meant, the company has its own servers and is behind cloudflare etc...

**Comment by emkman** [comment]
@NicolasDorier I extracted the commands from the LunaNode python script: https://github.com/LunaNode/launchbtcpay/blob/master/run.sh#L79 and ran the commands manually:
```
mount /dev/sda /var/lib/docker/volumes/generated_bitcoin_datadir/_data/blocks
blkid /dev/sda #get UUID
vim /etc/fstab #insert new entry with format "UUID=*UUID from above* /var/lib/..your_blocks_dir ext4 defaults 0 2"
```
and then ran `btcpay-setup.sh -i` and it worked great. Thanks!

This was on Digital Ocean using 250GB of added block storage. I think others could benefit from these instructions being surfaced more prominently.

**Comment by NicolasDorier** [comment]
Thanks for reporting. I think this can be good to document somewhere. Keeping this open until I do it.

**Comment by NicolasDorier** [comment]
Reporting here a way to do. Assuming `sda1` is your volume
```bash
sudo mkfs.ext4 /dev/sda1
# Create folder for mount.
sudo mkdir /mnt/usb
# Look up UUID of flash drive.
UUID="$(sudo blkid -s UUID -o value /dev/sda1)"
# Add mount to fstab.
echo "UUID=$UUID /mnt/usb ext4 defaults,nofail 0" | sudo tee -a /etc/fstab
```

**Comment by NicolasDorier** [comment]
Now [documented](https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#with-the-docker-deployment-how-to-use-a-different-volume-for-the-data).
