### ISSUE TITLE
backups dump postgresql database then fail to include it

### ISSUE THREAD

**Issue by anarcat** [btcpayserver/btcpayserver-docker#628]
I looked at `backup.sh` and it's pretty bizarre. First it does this:

```
# dump database
echo "Dumping database …"
btcpay_dump_db $dumpname
```

which is really just

```
docker exec $(docker ps -a -q -f "name=postgres_1") pg_dumpall -c -U postgres >/var/lib/docker/volumes/backup_datadir/_data/postgres.sql
```

Then it stops the server (which means the backup could miss transactions in the database after the dump), then:

```
    tar --exclude="$backup_dir/*" --exclude="$volumes_dir/generated_bitcoin_datadir/*" --exclude="$volumes_dir/generated_litecoin_datadir/*" --exclude="$volumes_dir/**/logs/*" -cvzf $backup_path $dbdump_path $volumes_dir
```

If you look closely, you'll notice it excludes backups from the tar file (`--exclude="$backup_dir/*"`). The `$dbdump_path` path is passed in there, presumably as an attempt to override that, but it doesn't work: there's no SQL dump in the backup file.

**Comment by dennisreimann** [comment]
I started #634 to fix this.
