### ISSUE TITLE
Server slows to a crawl and becomes non-responsive

### ISSUE THREAD

**Issue by ksdhans** [btcpayserver/btcpayserver-docker#642]
I have BTCPay set up on an 8GB Raspberry Pi 4, using an ssh reverse proxy. Everything was working fine. 

Today, I checked in on the server, and it's essentially non-responsive. Pinging it responds quickly, but HTTP(S) requests timeout. It took a few minutes to log in, and any shell command takes minutes or longer to respond. The htop command shows that CPU usage is moderate, but the server's 8GB of memory is almost exhausted. There is no swap space.

It's too early to say if there's a memory leak, but it has slowly run out of memory and become non-responsive. I'm still waiting for it to stop BTCPay, over ten minutes after executing btcpay-down.sh...

For reference: my server is set up for bitcoin (+ lightning), litecoin (+lightning), and monero. It's running clightning for the lightning network.

**Comment by ksdhans** [comment]
Is there anything that I can do immediately to lower memory usage? I'm thinking of disabling lightning for litecoin...

**Comment by pavlenex** [comment]
> disabling lightning for litecoin...

Yes remove it, who uses that anyway? Also withour proper logs and troubleshooting we can't really help you but probably good idea to remove shitcoins as they are unstable.

**Comment by ksdhans** [comment]
@pavlenex 
What logs should I be looking at? 

When I looked at htop, I didn't see anything obvious stick out in terms of memory usage. Mind you, processes jump around, so I may have missed something.

**Comment by ksdhans** [comment]
@pavlenex 
Also, is there a way to disable the litecoin lightning network without disabling it for bitcoin as well (and leaving litecoin itself enabled)? The webadmin allows me to disable the litecoin lightning network, but the docker containers are still running.

I could manually disable them, but I expect that they'll restart next time I update or restart the server.

**Comment by NicolasDorier** [comment]
@ksdhans yes you can disable only litecoin, one moment

**Comment by NicolasDorier** [comment]
```bash
BTCPAYGEN_EXCLUDE_FRAGMENTS="$BTCPAYGEN_EXCLUDE_FRAGMENTS;litecoin-clightning;litecoin-lnd;"
. btcpay-setup.sh -it
```

**Comment by ksdhans** [comment]
@NicolasDorier 
Thanks. Unfortunately, I left it one day too long, so I had to pull the plug and restart again. No chance to track down what's eating all the RAM. 

Also, "docker stats" isn't showing the memory stats for me. It lists everything as using 0% RAM.

**Comment by ksdhans** [comment]
The culprit appears to be the generated_postgres_1 container:
generated_postgres_1                    4.59%     206.2MiB / 7.63GiB   2.64%     24.2MB / 2.56MB   160MB / 1.39GB    11
generated_postgres_1                    0.05%     1.568GiB / 7.63GiB   20.55%    614MB / 67.5MB    763MB / 31.5GB    11

Over about 16-18 hours, it's grown from 206 MiB to 1.57 GiB. I've checked in at various times, and the memory usage has been slowly but steadily growing. All other containers are pretty stable in memory usage. They may go up for a while, but then drop back down.

Any suggestions on how to diagnose further?

**Comment by ksdhans** [comment]
I'm pretty sure it's the postgres container. Here's two snapshots from htop:
Uptime: 22:37:28
    PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%▽  TIME+  Command
   4222 999        20   0 1423M 1286M 78704 S  7.7 16.5  1h55:38 postgres: postgres nbxplorermainnet 172.18.0.8(59502) idle
   3498 999        20   0  725M  583M 72604 R  3.2  7.5 49:00.11 postgres: postgres nbxplorermainnet 172.18.0.8(59486) idle
   2070 999        20   0  208M 75804 73896 S  0.6  0.9  1:31.97 postgres: checkpointer
   1499 999        20   0  208M 20712 18912 S  0.0  0.3  0:06.96 postgres -c random_page_cost=1.0
 762164 999        20   0  210M 16024 12920 S  0.6  0.2  0:00.07 postgres: postgres btcpayservermainnet 172.18.0.17(38594) idle
 762925 999        20   0  209M 15168 12320 S  0.6  0.2  0:00.05 postgres: postgres nbxplorermainnet 172.18.0.8(60920) idle
   2071 999        20   0  208M 11620  9796 S  0.0  0.1  0:06.16 postgres: background writer
   2072 999        20   0  208M  9424  7608 S  0.6  0.1  1:20.07 postgres: walwriter
   2073 999        20   0  208M  8108  5956 S  0.0  0.1  0:30.73 postgres: autovacuum launcher
   2074 999        20   0 71952  8008  3296 S  0.0  0.1  1:53.71 postgres: stats collector
   2078 999        20   0  208M  7048  5012 S  0.0  0.1  0:29.53 postgres: logical replication launcher

Uptime: 1 day, 00:14:14
    PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%▽  TIME+  Command
   4222 999        20   0 1517M 1379M 78764 S 22.2 17.7  2h03:59 postgres: postgres nbxplorermainnet 172.18.0.8(59502) idle
   3498 999        20   0  758M  613M 72636 S  2.5  7.9 52:09.53 postgres: postgres nbxplorermainnet 172.18.0.8(59486) idle
   2070 999        20   0  208M 75820 73912 S  0.0  0.9  1:38.70 postgres: checkpointer
   1499 999        20   0  208M 20712 18912 S  0.0  0.3  0:07.42 postgres -c random_page_cost=1.0
 814564 999        20   0  210M 16056 12964 S  0.6  0.2  0:00.09 postgres: postgres btcpayservermainnet 172.18.0.17(48554) idle
 815278 999        20   0  209M 13732 10984 S  0.0  0.2  0:00.09 postgres: postgres nbxplorermainnet 172.18.0.8(42618) idle
   2071 999        20   0  208M 11632  9808 S  0.6  0.1  0:06.54 postgres: background writer
   2072 999        20   0  208M  9436  7620 S  0.0  0.1  1:25.75 postgres: walwriter
   2073 999        20   0  208M  8108  5956 S  0.0  0.1  0:32.88 postgres: autovacuum launcher
   2074 999        20   0 71952  8008  3296 S  0.0  0.1  2:01.62 postgres: stats collector
   2078 999        20   0  208M  7048  5012 S  0.0  0.1  0:31.57 postgres: logical replication launcher

The top two items keep using up more and more memory. 

Any idea what could cause this? I do have some old expired test invoices, but I'd expect it to cope with that gracefully.

**Comment by ksdhans** [comment]
This problem has gone away after I updated to the latest version of BTCPay. 

What's weird, is that the update didn't change the postgres container, nor did it restart. So, the ballooning memory usage must be triggered from outside. It's a bit concerning that a external database connections could cause cause memory consumption to continually expand like that. 

Anyway, the problem is gone, so I'm closing this.
