### ISSUE TITLE
Failed to create symbolic link on Amazon Linux AMI

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver-docker#65]
Prevents starting BTCPayServer

```
 Amazon ECS-Optimized Amazon Linux AMI 2018.03.h
```

```
BTCPay Server started
Creating network "generated_default" with the default driver
Creating generated_postgres_1 ... 
Creating btcpayserver_bitcoind ... 
Creating generated_postgres_1
Creating btcpayserver_bitcoind ... done
Creating generated_nbxplorer_1 ... 
Creating generated_nbxplorer_1 ... done
Creating generated_btcpayserver_1 ... 
Creating generated_btcpayserver_1 ... done
Creating nginx ... 
Creating nginx ... done
Creating nginx-gen ... 
Creating nginx-gen ... done
Creating letsencrypt-nginx-proxy-companion ... 
Creating letsencrypt-nginx-proxy-companion ... done
Adding symlink of bgold-cli.sh to /usr/bin

ln: failed to create symbolic link ‘/usr/bin/bgold-cli.sh’: File exists
```

**Comment by NicolasDorier** [comment]
Can you try `/usr/bin/bgold-cli.sh` and tell me what happen

**Comment by sigHash** [comment]
it simply returned. I guess removed it.

On a side note: I have modified some of the payserver's routes to return JSON instead of view so I can consume them in my react webap. Obviously calls being blocked due to  No 'Access-Control-Allow-Origin' header. How can  modify nginx conf without braking your automated scripts?

**Comment by NicolasDorier** [comment]
@sigHash why don't you make a PR so that we returns JSON view without hack at nginx level?

**Comment by NicolasDorier** [comment]
That said, if you find a way to customize nginx it would be great as well.

**Comment by sigHash** [comment]
> @sigHash why don't you make a PR so that we returns JSON view without hack at nginx level?

I am actually returning JSON data, not JSON views from my own custom routes. Already got a frontend app and am trying to convert payserver to an api endpoint so I can use it with any UI.
