### ISSUE TITLE
cp: cannot stat 'utxo-sets': No such file or directory

### ISSUE THREAD

**Issue by githubber** [btcpayserver/btcpayserver-docker#650]
I'm trying to run load-utxo-set.sh from within the btcpayserver-docker directory, and I get this error message. I thought the script did the heavy lifting... how, and where, do I make this directory? Thank you!

**Comment by pavlenex** [comment]
You tried `./load-utxo-set.sh`?

**Comment by githubber** [comment]
Yes, I've tried `./load-utxo-set.sh`, and the error is `cannot stat 'utxo-sets': No such file or directory`.

**Comment by githubber** [comment]
I mentioned in which directory I was running this, thinking that might be a factor (from within the btcpayserver-docker directory, which is itself in /root). Does it have to run within Docker, or should it have been installed in a different director/User directory?

I should say, thank you! Other than this, it installed smooth as silk, and it running well! Awesome!

**Comment by dennisreimann** [comment]
@githubber As stated in the [FastSync docs](https://docs.btcpayserver.org/Docker/fastsync/#how-to-verify-that-the-utxo-set-snapshot-follows-the-consensus), the command needs to be run in the `contrib/FastSync` subdirectory.

So you have to `cd $BTCPAY_BASE_DIRECTORY/btcpayserver-docker/contrib/FastSync` first.

I hope this helps ­— if not, feel free to reopen this issue with more details.
