### ISSUE TITLE
Hi. How to send

### ISSUE THREAD

**Issue by mass34** [btcpayserver/btcpayserver-docker#653]
I guess I don't understand.
1.Bitcoin
2.Send.
3.Destination Address and  Amount
4.Sign transaction.
5."Confirm broadcasting this transaction" Broadcast transaction
6."Decode PSBT"? Why am I being sent away?
pressure Decode PSBT
.....on the previous page "Confirm broadcasting this transaction"
and so on.

**Comment by pavlenex** [comment]
Please this is a support quesiton ask on our mattermost chat https://chat.btcpayserver.org or our telegram, we only use this to keep a track of bugs.
