### ISSUE TITLE
LND's grpc api not entirely available through nginx reverse proxy

### ISSUE THREAD

**Issue by maxwedwards** [btcpayserver/btcpayserver-docker#659]
We are using an API under the path `/routerrpc.Router` but this just 404s.

Changing the nginx template to look for both routerrpc and lnrpc fixes this for us but does miss other apis for LND.

```
location ~ ^/(lnrpc|routerrpc) {
    grpc_pass grpcs://lnd_bitcoin:10009;
}
```

Should I submit a PR with the above or one with all the routes I can see in LNDs documentation?

**Comment by Kukks** [comment]
Please submit a pr, but also make sure that the location is namespaced like the other subpaths
