### ISSUE TITLE
Suggest updating Spark to v0.3.1

### ISSUE THREAD

**Issue by ksdhans** [btcpayserver/btcpayserver-docker#664]
BTCPayServer (docker) is currently using Spark v0.2.9, which is over 2 years old now, and multiple releases behind. I tried using it with the latest mobile app (v0.3.1), and it was basically unusable. It spat out "unrecognized command" errors. 

It would be great to have it updated to the latest version.

**Comment by achow101** [comment]
It would also be nice to have c-lightning itself updated to the most recent release.

**Comment by NicolasDorier** [comment]
we are updating both now

**Comment by achow101** [comment]
> we are updating both now

Any update on this?

**Comment by dennisreimann** [comment]
@achow101 We're still waiting for ElementsProject/lightning#5657 to be resolved — once that's done we can deliver the update.

**Comment by NicolasDorier** [comment]
@achow101 I believe I will just remove the announce-addr, they are unresponsive.

**Comment by NicolasDorier** [comment]
Shit we can't remove `announce-addr` as our unit tests depends on it too much, and BTCPay Server also depends on it to fetch the node information to our users.

We are stuck until they somehow fix it.

**Comment by ksdhans** [comment]
That's annoying. It looks like it's part of their next milestone, whose target date was 19 days ago. So, there's a chance they'll get round to it soonish...

**Comment by NicolasDorier** [comment]
If I have even just a patch I can put it on our fork

**Comment by NicolasDorier** [comment]
Spark updated as well!
