### ISSUE TITLE
Cloudflare and ssl

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver-docker#67]
Hi guys pls check the error whit cloudflare because i try point cnam ----> domain and a ---> ip but not work always error 503 nginx

**Comment by NicolasDorier** [comment]
I don't know how to use cloudfare. I know NBX need port 80 and 443 open to get the certificate.

**Comment by NicolasDorier** [comment]
Closed for inactivity: what seems to solve it is removing cloudfare, having 443 and 80 accessible, get the certificate then put cloudfare again. Normally certs renewal don't use HTTP at all then. But I am not 100% sure.
