### ISSUE TITLE
LTC Lightning Node won't sync

### ISSUE THREAD

**Issue by bigbryan98** [btcpayserver/btcpayserver-docker#7]
My LTC Lightning Node will not sync.  For some reason it is downloading the entire LTC LN chain >1M blocks (with BTC LN it starts WhenLightningBecameCool chopping off most of the chain) and once it reaches the end of the chain, it dumps and starts over.  It usually takes 2ish days for it to fully sync, so seeing it start over is pretty heartbreaking.  I am unsure if this is a problem with LTC CLightning or with BTC Payserver.  I can post over there if you want me too.

![image](https://user-images.githubusercontent.com/36655751/39103710-05fa26d2-4672-11e8-84a0-34f49421d74c.png)

**Comment by NicolasDorier** [comment]
yeah you need through putty!

**Comment by NicolasDorier** [comment]
```
sudo su -
btcpay-update.sh
```

**Comment by bigbryan98** [comment]
ok, Ill wait to see if the update fixes it and then post if not.  Thanks man!

**Comment by NicolasDorier** [comment]
Closing this as we solved it in the clightning repo
