### ISSUE TITLE
 BTCPay docker behind a nginx proxy -  problems with the Lightning Address being validated 

### ISSUE THREAD

**Issue by tradenet** [btcpayserver/btcpayserver-docker#711]
I have BTCPay docker behind a nginx proxy. But I have problems with the Lightning Address being validated because it's looking for "pay.example.com/.well-known/lnurlp/me" and I am not sure where to redirect this or where it exists in the docker build. Any suggestions or solutions?
Thanks,
G.

**Comment by dennisreimann** [comment]
Does this help? https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-to-redirect-a-lightning-address

**Comment by tradenet** [comment]
Well yes so what. However, where does the
~ /.well-known/lnurlp/me reside in the docker container?
I have to access it via nginx proxy outside of container.

**Comment by dennisreimann** [comment]
It's not a file inside a docker volume, but an [endpoint](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UILNURLController.cs#L314) provided by the BTCPay Server app.
