### ISSUE TITLE
 illegal character: " - setup

### ISSUE THREAD

**Issue by redimongo** [btcpayserver/btcpayserver-docker#726]
Not sure what I have done wrong, or if there is something wrong with this install script.

I followed the set up of https://molthoff.medium.com/running-btcpay-on-digital-ocean-for-10-month-how-to-add-other-coins-7a497339fb2f

```
. ./btcpay-setup.sh -i
./btcpay-setup.sh:119: bad math expression: illegal character: "
Usage:
------
```

**Comment by dennisreimann** [comment]
It looks like this script is run with a shell other than `bash` — might that be the case? 

Googling the error message it looks like its exectued in a `zsh` environment.

**Comment by redimongo** [comment]
I ended up reformatting the server and it was fine.
I am not sure what happened. Thankfully I was only testing it.
