### ISSUE TITLE
Feature Request: Ability to see all Wallets in a single view again

### ISSUE THREAD

**Issue by hb2uk** [btcpayserver/btcpayserver-docker#732]
Since the lates version, it is taking us along time to go into each shop and see total wallet values. As we have an ever-increasing number of shops, is there a way to get the old wallets page back?

**Comment by dennisreimann** [comment]
We don't link there anymore, but you can still go to /wallets and get the overview.

**Comment by hb2uk** [comment]
Thank you for the fast reply, this is so helpful.
