### ISSUE TITLE
how do i uninstall btcpayserver-docker

### ISSUE THREAD

**Issue by ericsupreme** [btcpayserver/btcpayserver-docker#733]
i am having an issue with the install on my raspi and can't seem to find any solutions anywhere. i followed the install 
instructions here https://docs.btcpayserver.org/Deployment/RaspberryPi4/  my pi already had a full btc node and lightning running /w a few apps blockexplorer, electrum etc.  using nginx as reverse proxy. after following the install doc i am just unable to reach myhostname.local via http/https per instructions. not sure what i'm missing and i'm getting frustrated. i would just like to uninstall. thanks in advance

**Comment by dennisreimann** [comment]
Hey, would you be willing to test the script I just wrote in #734?

You could add it as `btcpay-teardown.sh` next to `btcpay-setup.sh` and then run:

```bash
chmod +x btcpay-teardown.sh
. ./btcpay-teardown.sh
```

**Comment by ericsupreme** [comment]
sure i'll give it try and let you know!

**Comment by ericsupreme** [comment]
> Hey, would you be willing to test the script I just wrote in #734?
> 
> You could add it as `btcpay-teardown.sh` next to `btcpay-setup.sh` and then run:
> 
> ```shell
> chmod +x btcpay-teardown.sh
> . ./btcpay-teardown.sh
> ```

![Screenshot_2022-12-02_10-47-51](https://user-images.githubusercontent.com/38678012/205331941-80c5a5c1-0907-471c-8e04-de5cd0bfaaff.png)

seems to have worked!! i assume it unlinked the syslink's btcpay-setup created?  thank you for your hard work!!

**Comment by dennisreimann** [comment]
Nice, thanks for testing it and providing feedback so quickly!

Yes, this script should have erased all the BTCPay Server related files etc. on your server.
