### ISSUE TITLE
Running BTCPAY Server behind an SSH Reverse Proxy tunnel.

### ISSUE THREAD

**Issue by guymass** [btcpayserver/btcpayserver-docker#757]
I have setup the docker version of btcpay server and it was installing just fine and was also loading fine in my browser. I was able to play with it fora while creating a store and a wallet, however suddenly with no apparent reason I started to get Error 301 and the site just went down. I used the basic installation instruction from the online guide. I setup my SSH tunnel using autossh to keep the connection always on. I have this same method used for several sites I am using in such manner to connect them to the internet through a proxy server I own. 

I would like to know how I can set the nginx configuration to work with my ssh tunnel which is proxying the domain requests to my local VM BTCPAY server.

Thank you for your help.

**Comment by guymass** [comment]
I currently ran a new installation, setting my ssh tunnel to run normally, meaning without autossh. I created the first admin user and waiting to see how long until it looses the proxy connection.

![Screen Shot 5783-06-04 at 16 57 34](https://user-images.githubusercontent.com/58882903/221363930-545fa807-63e9-47cf-8207-1281051eeb38.jpg)


I still have some issues connecting to the WSS:// notification don't know how to solve that one, would appreciate any help.

**Comment by dennisreimann** [comment]
Have you checked the [webserver setup part](https://docs.btcpayserver.org/Deployment/ReverseProxyToTor/#webserver-setup) of the Tor guide? It's very similar to that.

**Comment by guymass** [comment]
No I didn't, was thinking too but I wanted to use what im already familiar with. Well site crashed and lost its connection when I was trying to create API keys to connect the server to my OpenCart site. Now I get again error 301:
![Screen Shot 5783-06-04 at 17 55 04](https://user-images.githubusercontent.com/58882903/221366757-ed7d2a65-1768-40f0-8c48-703e1f849373.jpg)

Well next option like you suggested is to look into tor, however I am not sure if it can use my own domain name or does it create its own onion domain name? because I would like to use my own domain.

**Comment by guymass** [comment]
What's strange is that is actually works quite well after the installation is done, but than something happens during one of my configuration saves or while creating something and it gets broken.

**Comment by dennisreimann** [comment]
I meant just the basics of the webserver config part from that guide. 

Also: Are you editing the nginx template file from the Production folder or something else?

**Comment by guymass** [comment]
No I wasn't editing anything currently am just trying to learn where I need to make those edits. I am simply running an ssh tunnel to my remote proxy server, that server is running a simple apache2 server that is redirecting requests to different domains and sites I have. Simply this tunnel connection would look like this:

sudo ssh -R 23001:localhost:80 -N -f  root@proxy-server-ip -i /root/.ssh/id_rsa &

after I was installing the docker everything was connecting just fine for a while. I just don't really  know what is causing this behaviour.

**Comment by dennisreimann** [comment]
I'm doing SSL termination on the VPS that is running nginx. In your case that's Apache, but it might be easy to adapt. I'll update the docs to include the webserver setup part. Give me a bit …

**Comment by dennisreimann** [comment]
Ok, I looked more closely at the guide and the reason it doesn't even contain a webserver setup part is that it simply forwards the ports 80/443 — hence there is no need for a webserver on the VPS.

Your case is a bit different though, as you seem to be using the VPS as a proxy for multiple services and hence need a webserver to map different domains to different ports.

For the BTCPay Server Reverse Proxy settings it depends where you want to do the SSL termination: If you want to keep it on the BTCPay Server nginx (default), then you don't need to change any of the environment variables and autossh forward ports 80/433 as described in the guide — but you'll most likely want to map them to different port numbers on the VPS, e.g. 8080/8443:

```
ExecStart=/usr/bin/autossh -C -M 0 -v -N -o "ServerAliveInterval=60" -R 9735:localhost:9735 -R 8443:localhost:443 -R 8080:localhost:80 root@VPS_IP_ADDRESS
```

A shortened nginx version of the webserver config would look like this:

```
server {
  listen 80;
  server_name my.btcpay.com;

  location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}

server {
  listen 443 ssl http2;
  server_name my.btcpay.com;

  location / {
    proxy_pass http://127.0.0.1:8443;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}
```

Not 100% sure though, because I'm doing SSL termination on the VPS very similar to what's described in the Tor Reverse Proxy guide. 

Hope this gives you some more guidance.

**Comment by guymass** [comment]
First of all much thanks for time taken to help me sort this out. I currently reinstalled everything again but this time I excluded this part export BTCPAYGEN_REVERSEPROXY="nginx" from the installation and currently it seems to be running after I created a new store and wallet and connected them to my opencart site. The node is almost done synchronizing, so I will keep testing to see if that did the trick and solved it for me or not. Other wise I will try your solution as well.

In general, in my case I think there is no need for using port 443 as my proxy server is the one validating the certbot SSL certificates and I am able to run in such way all my local websites including some of the most know opensource scripts such as NextCloud, AVIDEO, OpenCart and others, so having my own private btc node was a project I wanted to see if I can also setup in such manner and for most part it works very well.

**Comment by dennisreimann** [comment]
If your proxy is doing the SSL termination, also check this guide: https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

**Comment by guymass** [comment]
OK thank you, I will although my proxy is currently seta s apache, I am planning on moving to nginx in time. Current status of my installation is it survived a restart and network disconnection. Once I ran the tunnel command again and the docker was back up, the site came up very well. I will still be testing, but for now it seems removing nginx as a proxy did the trick for me. I will be closing this in 1-2 days just to make sure and in case anyone wishes to add more pointers.

Again thanks for the help and quick response, god bless.

**Comment by dennisreimann** [comment]
btw if you are mostly interested in the proxy capabilities, check out [Caddy](https://caddyserver.com/). I love the functionality and simplicity of this webserver.

**Comment by guymass** [comment]
Needed to add on more thing to the solution I found, I lost the site again to the too many redirects 301 error but than I found you can add this line to the installation export parameters and it solved my issue and brought the site back on.

I shutdown the docker with btcpay-down.sh and then

export BTCPAYGEN_EXCLUDE_FRAGMENTS="$BTCPAYGEN_EXCLUDE_FRAGMENTS;nginx-https"

then ran again
. ./btcpay-setup.sh -i

and site came back.

**Comment by guymass** [comment]
I think now it can be closed.
