### ISSUE TITLE
BTCPayServer Migration

### ISSUE THREAD

**Issue by hiroashikawa** [btcpayserver/btcpayserver-docker#758]
I recently migrated BTCPayServer to another Server of mine, and now I cannot open my panel, and it is giving me a ERR_TOO_MANY_REDIRECTS error.

My Attempt to Migrate BTCPayServer is as following:
-Install BTCPayServer Docker with the exact same configuration I used on my previous Server
- Run ./btcpay-backup.sh on Old Server, Drag Backup File to new Server
- After BTCPayServer is installed on new Server, I would run ./btcpay-restore.sh /root/mybackupfile.tar.gz
- Restart BTCPayServer, and It is broken. (ERR_TOO_MANY_REDIRECTS, Panel won't open at all)

**Comment by dennisreimann** [comment]
Can you check the nginx logs and see where it is trying to redirect to? Just a guess, maybe the DNS recods aren't correct?

**Comment by hiroashikawa** [comment]
Where can I find the NGiNX Logs? as they are not located in /var/log/nginx for me.

**Comment by hiroashikawa** [comment]
docker logs, got it.

After visiting my BTCPayServer Panel following logs appeared:
![image](https://user-images.githubusercontent.com/91470165/222527927-4a84427b-0d86-4e26-9854-1cbf6910f4a2.png)

**Comment by hiroashikawa** [comment]
I am also behind Cloudflare.

**Comment by hiroashikawa** [comment]
I also just tested without restoring the backup, the same thing happens, But it happens after I create a User. After I press register, I instantly see the ERR_TOO_MANY_REDIRECTS screen.

**Comment by dennisreimann** [comment]
I assume the redirect is coming from this [part of the nginx.conf](https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L482). Can you check this file that gets generated off of this template and see if it looks as expected?

```bash
cat /var/lib/docker/volumes/generated_nginx_conf/_data/default.conf
```

It's supposed to redirect the http requests to https. The [part right below](https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L494) is supposed to then handle the redirected requests, but it seems like the `server_name` directive in both parts might not match.

**Comment by hiroashikawa** [comment]
Everything seems fine in the NGiNX Config, server_name is the same and I do not see any conflicts tbf

**Comment by dennisreimann** [comment]
@NicolasDorier Any idea why this might happen?

**Comment by hiroashikawa** [comment]
What is also confusing me why I could access it for the first time after it was installed, without any backup I could register an account but right after I registered an account it gave me the redirection issue.

**Comment by hiroashikawa** [comment]
Any fix for this? Even on other servers, I am getting the same issue.

**Comment by NicolasDorier** [comment]
@hiroashikawa when you say you use Cloudflare, do you mean you use [cloudflare tunnel](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docs/cloudflare-tunnel.md)?

Or do you mean you use cloudflare as a reverse proxy?
If you use cloudflare as a reverse proxy, the problem might be your config of cloudflare try to access the website in HTTP, and btcpay's nginx see that and try to redirect to HTTPS, which redirect to cloudflare etc... endless loop.

**Comment by NicolasDorier** [comment]
The only reason I see for a redirect on the favicon is if the nginx proxy is expecting a https request but receive a http request.

**Comment by hiroashikawa** [comment]
Well, how is it getting an HTTP request? I am enforcing HTTPS. I will try fixing this in the following days, and I will let you know if I found a solution.

**Comment by NicolasDorier** [comment]
I mean between the nginx and the cloudflare

**Comment by hiroashikawa** [comment]
Seems like older versions of BTCPayServer work, no idea, and when I update it, it seems to work also.....
