### ISSUE TITLE
hybrid environment?

### ISSUE THREAD

**Issue by Waldorf3** [btcpayserver/btcpayserver-docker#768]
I notice that although this is supposed to be a docker implementation it still seems to hack the host OS for things like the nginx frontent proxy - why is that?  

Why not integrate with one of the exising docker proxy managers such as [jlesage/docker-nginx-proxy-manager](https://github.com/jlesage/docker-nginx-proxy-manager)? This would allow for a much easier integration with an existing docker setup and portability in general.

**Comment by dennisreimann** [comment]
Can you elaborate and be more specific about what you mean with "hack the host OS"?

**Comment by dennisreimann** [comment]
Where are we installing nginx on the host?

**Comment by Waldorf3** [comment]
I read it somewhere on my first read through of the documentation. Are you saying you're not making any system level changes on the server, other than possibly installing docker?   Maybe it's just me, but I find the documentation very hard to read, and it's not because I'm not used to read documentation. Normally a docker apps do what they need to do with in docker, without adding scripts or adding startup scripts. There are some systemctl additions supposedly in order to start btcpay after reboots, but if properly setup, docker automatically starts whatever needs to run after a reboot.  Confusing.

**Comment by Waldorf3** [comment]
Well rather than reusing one of my existing docker servers, I spun up a new host and ran the authorized install script. This installed the btcpayserver correct, and it works. It is however a bit restrictive, in that it requires a new isolated server for this purpose, that is not really the idea with docker.   It's a containerized system that should be able to coexist and integrate with other containrs.

**Comment by dennisreimann** [comment]
I'm running other docker and docker-compose setups alongside the BTCPay Server docker deployment without problems. Can you elaborate on why this is problematic or how it could be improved?
