### ISSUE TITLE
[BUG] Lightning Terminal fragment wrong datadir (RISK OF USER LOSING FUNDS!)

### ISSUE THREAD

**Issue by belmeopmenieuwesim** [btcpayserver/btcpayserver-docker#787]
https://github.com/btcpayserver/btcpayserver-docker/blob/f0e0b2cf1171e8db319610c3e486fdeb38d40dc1/docker-compose-generator/docker-fragments/opt-add-lightning-terminal.yml#LL16C28-L16C28

It should use the `/root/.lit` directory instead of `/root/.lnd` directory, since the account information is stored in `.lit`.

If this is not fixed, it risks users losing all their funds inside their Pool account!

**Comment by dennisreimann** [comment]
In #781 I've upgraded LiT to v0.9.2 — I just tested this in production and pushed the update. Can you verify this solves the problem?
