### ISSUE TITLE
LNDHub Error when importing to BlueWallet

### ISSUE THREAD

**Issue by me639276639936** [btcpayserver/btcpayserver-docker#795]
Hey there,

I get this error now when importing the node's LNDHub wallet to BlueWallet. This is from BlueWallet: "API error: Method not found: 'System.String BTCPayServer.Data.StoreData.get_Role()'. (code 6)"

Curiously, if I import an LNDBank wallet, I do not get this error.

A couple of things to note: 1) I recently started using my btcpayserver as a public webserver 2) my btcpayserver is up to date on updates

**Comment by dennisreimann** [comment]
Is this in the context of the [LNDhub API plugin](https://docs.btcpayserver.org/LNDhubAPI/) or what kind of LNDhub wallet are you importing? Do you mean one provided by the `opt-add-bluewallet-lndhub` fragment?

**Comment by dennisreimann** [comment]
Thanks for reporting, this is now fixed with [LNDhub API v1.0.2](https://github.com/dennisreimann/btcpayserver-plugin-lndhub-api/releases/tag/v1.0.2).

**Comment by me639276639936** [comment]
Works. Thanks
