### ISSUE TITLE
[question] I've finished setting up with Docker, but get a 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#80]
Just finished the installation with docker, followed all the steps to the letter, but get a 503 Service Temporarily Unavailable error when browsing to the server's IP.

Could this be because I am browsing to the servers IP and not the domain name I configured?
My DNS change is not fully propagated yet (may take up to 1 day) and I dont wanna wait :-)

Can I save time by using changedomain.sh?

I can't seam to find any troubleshooting steps on this.

What can I expect when browsing to the IP under normal conditions?

When running docker ps, I can see lots of containers running and at 100% CPU...

**Comment by bitcoinshirt** [comment]
You need to use a proper domain name, not the IP address as btcpay host.

**Comment by woutersamaey** [comment]
OK, just figured out that I can use changedomain.sh x.x.x.x (change to your IP) to get quick access to it, but when browsing to it, it does alert you to use a proper domain. At least for now, I know it's working and have seen a UI :-)

Thanks!
