### ISSUE TITLE
monerod crashes after update to Monero v0.18.2.2

### ISSUE THREAD

**Issue by d2ro** [btcpayserver/btcpayserver-docker#805]
Todays commits caused monerod to crash on our server:

```
# docker logs --tail 10 "btcpayserver_monerod" 
2023-06-26 09:49:59.427	I Stopping cryptonote protocol...
2023-06-26 09:49:59.427	I Cryptonote protocol stopped successfully
2023-06-26 09:49:59.428	E Exception in main! boost::filesystem::create_directories: Permission denied: "/nonexistent"
2023-06-26 09:51:01.007	I Monero 'Fluorine Fermi' (v0.18.2.2-release)
2023-06-26 09:51:01.007	I Initializing cryptonote protocol...
2023-06-26 09:51:01.007	I Cryptonote protocol initialized OK
2023-06-26 09:51:01.008	I Initializing core...
2023-06-26 09:51:01.008	I Stopping cryptonote protocol...
2023-06-26 09:51:01.008	I Cryptonote protocol stopped successfully
2023-06-26 09:51:01.008	E Exception in main! boost::filesystem::create_directories: Permission denied: "/nonexistent"
```

We temporarily fixed it by going back to commit `cd0a734`:

```
# cd btcpayserver-docker/
# git checkout cd0a73435c2bc8a8bd7c815611ef34c634ca3628
# btcpay-update.sh --skip-git-pull
```

**Comment by NicolasDorier** [comment]
Ping @sethforprivacy

**Comment by sethforprivacy** [comment]
Thanks, looking now.

I wonder if the mounts are messed up for this specific install? @NicolasDorier do you know what would cause a container in btcpay to try and mount `/nonexistent`?

**Comment by sethforprivacy** [comment]
Reproduced the issue on 1.10.2 w/ the new 0.18.2.2 Monero image.

**Comment by sethforprivacy** [comment]
I think I have a fix identified, testing now, then will PR.

**Comment by sethforprivacy** [comment]
https://github.com/btcpayserver/dockerfile-deps/pull/67 resolves this, it appears to be a permissions issue as the containers default UID for the new Monero user defaults to 100 now instead of 101 after switching the base image to `stable-slim`.

**Comment by NicolasDorier** [comment]
@sethforprivacy  `adduser: The --group, --ingroup, and --gid options are mutually exclusive.`

**Comment by sethforprivacy** [comment]
> @sethforprivacy  `adduser: The --group, --ingroup, and --gid options are mutually exclusive.`

So sorry, I'm AFK until at least tomorrow due to personal things.

You can test simply removing the --group flag and rely only on gid, don't actually need it named in reality and more important to have the ID static.

Or you can revert the v0.18.2.2 PRs entirely and I'll re-PR after more testing later this week?

**Comment by NicolasDorier** [comment]
trying https://github.com/btcpayserver/dockerfile-deps/commit/d26adaceb54f7ecd4c93b5dc91d71bfe8fa3f2ac

**Comment by NicolasDorier** [comment]
doesn't work. Please fix it, don't have time to find out what is going on

**Comment by jahway603** [comment]
I'm having the same issue too.

**Comment by Kukks** [comment]
Try the latest now

**Comment by astupidmoose** [comment]
Just updated, still broken.

**Comment by astupidmoose** [comment]
Deleted my original comment cause I thought maybe my hard drive was full, but after making room I'm still having this issue:

Monerod gives: 

> 2023-07-07 18:54:50.004 I Monero 'Fluorine Fermi' (v0.18.2.2-release)
> 2023-07-07 18:54:50.004 I Initializing cryptonote protocol...
> 2023-07-07 18:54:50.004 I Cryptonote protocol initialized OK
> 2023-07-07 18:54:50.005 I Initializing core...
> 2023-07-07 18:54:50.005 I Loading blockchain from folder /home/monero/.bitmonero/lmdb ...
> 2023-07-07 18:54:50.044 I Stopping cryptonote protocol...
> 2023-07-07 18:54:50.044 I Cryptonote protocol stopped successfully
> 2023-07-07 18:54:50.045 E Exception in main! boost::thread_resource_error: Resource temporarily unavailable
> 
Monero Wallet: 

> 2023-07-07 18:50:21.741 W Loading wallet...
> 2023-07-07 18:50:21.935 E dbr. THROW EXCEPTION: tools::error::wallet_internal_error
> 2023-07-07 18:50:21.935 E Failed to initialize ringdb: Failed to open rings database file '/home/monero': Permission denied
> 2023-07-07 18:50:23.969 W Loaded wallet keys file, with public address: 4AsYt5GTLHNFEWd6h1ZMnAFRfvBha1i7iGdcsFCCnZ6f2t3VZ9oTjhZ6SqR9gD9vQ3PPaVNc1M941Pu3YBYn5scYALETVsc
> 2023-07-07 18:50:24.333 E Initial refresh failed: boost::thread_resource_error: Resource temporarily unavailable
> 2023-07-07 18:50:24.335 E Failed to query mining status: No connection to daemon
> 2023-07-07 18:50:24.335 I Binding on 0.0.0.0 (IPv4):18082
> 2023-07-07 18:50:24.759 W Starting wallet RPC server
> 2023-07-07 18:50:24.759 W Stopped wallet RPC server
> 2023-07-07 18:50:24.759 W Saving wallet...
> 2023-07-07 18:50:25.093 W Successfully saved
>

**Comment by sethforprivacy** [comment]
Apologies again to everyone here, I got very sick after a big life event and I haven't touched a computer for 2wks.

I'm focusing on this this afternoon, will test fully and aim to PR a fix by the EOD.

**Comment by sethforprivacy** [comment]
@Kukks @NicolasDorier it looks to me like you resolved the issue and just missed the image tag:

https://github.com/btcpayserver/btcpayserver-docker/pull/815

My BTCPay host I usually test on is down for maintenance unfortunately right now, but once the compose fragment uses the correct tagged image it should resolve all existing issues thanks to your efforts!

**Comment by sethforprivacy** [comment]
Investigating more as we speak, as the above was not a fix and was a misunderstanding with how the tagging system works.
