### ISSUE TITLE
[Bug] Documentation is missing to upgrade btcpayserver-docker

### ISSUE THREAD

**Issue by jahway603** [btcpayserver/btcpayserver-docker#809]
Documentation is missing to upgrade btcpayserver-docker

**Comment by maltokyo** [comment]
Just run this..  
https://github.com/btcpayserver/btcpayserver-docker/blob/master/btcpay-update.sh

**Comment by jahway603** [comment]
Thanks, it's now broken after running that update script.

**Comment by jahway603** [comment]
PR https://github.com/btcpayserver/btcpayserver-docker/pull/811 resolves this issue
