### ISSUE TITLE
Unable to connect zap, joule etc to BTCPayServer

### ISSUE THREAD

**Issue by btnet** [btcpayserver/btcpayserver-docker#81]
I am unable to connect zap, joule etc to LND through BTCPayServer

I am not using the internal nginx reverse proxy because I am using a single IP which already has a server hosted with various other services behind a nginx reverse proxy.

Everything else works just fine just can't connect to a wallet LND 

Is this supposed to be null "certificateThumbprint": null,

I have also tried clightning and spark and just get a 404 error from btcpay 
Basically everything is working just fine except I am unable to connect any lightning wallets to manage the channels 

{
    "configurations": [
        {
            "host": "btcpay.xxxxxxxxxxxxxxxxxxxxxx",
            "port": 443,
            "ssl": true,
            "chainType": "Mainnet",
            "type": "grpc",
            "cryptoCode": "BTC",
            "certificateThumbprint": null,
            "macaroon": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "adminMacaroon": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "readonlyMacaroon": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "invoiceMacaroon": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
    ]
}

I installed BTCPaySever with the variables 

export BTCPAY_HOST="btcpay.xxxxxxxxxxxxxxxxxxxxxxxx"
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_CRYPTO2="ltc"
export BTCPAYGEN_REVERSEPROXY="none"
export BTCPAYGEN_LIGHTNING="lnd"
export LIGHTNING_ALIAS="xxxxxxxxxxxxxxxxxxxxxx"
export BTCPAY_PROTOCOL="https"
. ./btcpay-setup.sh -i

I have removed various fields with xxxxxxxxxxxxx for security and privacy

**Comment by NicolasDorier** [comment]
@btnet this is strange, can we start fixing LND? what error do you get?

**Comment by btnet** [comment]
I am not seeing any errors any tips as where I should be looking for debugging information

**Comment by NicolasDorier** [comment]
> Everything else works just fine just can't connect to a wallet LND

What do you mean by "can't connect to a wallet LND"

**Comment by btnet** [comment]
Zap, joule etc show no errors they just go back to the connection sreen

I also tried clightning but just get a 404 error generated from btcpay but I don't think lightning charge is running 

It's weird because apart from that everything else is working I can generate lightning invoices etc using the built in pos app just can't connect any external wallets 

I could give you admin access to btcpay because I will be moving it to a odroid hc1 in about a week once it turns up so everything on the current server will be wiped

**Comment by NicolasDorier** [comment]
sure, please give me access.

**Comment by btnet** [comment]
I will send you a DM on twitter

**Comment by NicolasDorier** [comment]
Closing, probably solved, if not reopening
