### ISSUE TITLE
[Feature Request] Custom url for exchange rate provider

### ISSUE THREAD

**Issue by vswee** [btcpayserver/btcpayserver-docker#82]

**Comment by NicolasDorier** [comment]
this is not enough, each exchange rate provider have different json data shape

**Comment by vswee** [comment]
What about having a custom URL + an input field for a user to give the exact JSON path for each currency pair they need?

**Comment by NicolasDorier** [comment]
too many differences. Some API name their currency pair differently from btcpay and thus need a conversion.

Some API use scientific notation, other don't.

Some use arrays, some json properties.

It is too hard to be flexible enough to convert everything and not screw up.

So either we impose a standard format for BTCPay that everybody can implement and point their own URL. Or we just code it in C# as we do now.
