### ISSUE TITLE
Can't enable watchtower support on LND

### ISSUE THREAD

**Issue by Turtlecute33** [btcpayserver/btcpayserver-docker#826]
Hi,
I'm trying to enable watchtower support for LND using the configuration overlay as described in the FAQ (https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-to-edit-lndconf). This is my `docker-compose-generator/docker-fragments/opt-lnd-config.custom.yml`:
```
version: '3'
services:
  lnd_bitcoin:
    environment:
      LND_EXTRA_ARGS: |
        minchansize=1000000
        watchtower.active=true
        color=#33cc99
```
The `color` and `minchansize` settings are correctly applied, but when I try to add a watchtower I get an error:

```
root@btcpay913576:~/btcpayserver-docker# ./bitcoin-lncli.sh wtclient add 0202e7727ee46d943a44c7bf0dce14220a839630dee67d03446bf935178b55a0df@167.86.102.174:9735
[lncli] rpc error: code = Unknown desc = watchtower client not active
```

**Comment by dennisreimann** [comment]
I assume it needs the `[watchtower]` prelude too, see the [sample lnd.conf](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L1135).

**Comment by dennisreimann** [comment]
Just took a look at [the LND fragment](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/bitcoin-lnd.yml) which looks like the prelude isn't necessary. 

Can you check the generated confog file whether or not it contains the updated settings after running `. ./btcpay-setup.sh -i`?

@rockstardev any idea why the setting might not be working?

**Comment by dennisreimann** [comment]
TIL that we also have an [opt-lnd-wtclient.yml](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/opt-lnd-wtclient.yml) fragment, which includes the directives to set the client part (`wtclient.active=1`). This should solve the problem.

**Comment by dennisreimann** [comment]
Please note that you also need the latest version of our Docker LND container (v0.16.4-1) for this to work. 

`./btcpay-update.sh` will upgrade to the latest version.

**Comment by Turtlecute33** [comment]
ok, my bad. i hadn't exported the right fragment. fixed!
