### ISSUE TITLE
Mine is asking me to  pay for my winnings with my Bitcoin. And I can’t at in advance this is my 4th attempt to get you to change my services to  take it out of my winnings

### ISSUE THREAD

**Issue by tight-sketch** [btcpayserver/btcpayserver-docker#830]
Mine is asking me to  pay for my winnings with my Bitcoin. And I can’t at in advance this is my 4th attempt to get you to change my services to  take it out of my winnings

_Originally posted by @tight-sketch in https://github.com/btcpayserver/btcpayserver/issues/5207#issuecomment-1704602008_

**Comment by NicolasDorier** [comment]
You got scammed by somebody impersonating us, please read https://blog.btcpayserver.org/bitcoin-bonus-scam/
