### ISSUE TITLE
Monero 0.18.2.2 is broken, revert back to 0.18.1.1 until fixed

### ISSUE THREAD

**Issue by michnovka** [btcpayserver/btcpayserver-docker#837]
As [discussed on Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/rt84edy5mtd1mjmwy7kbtofmny), the upgrade to Monero 0.18.2.2 from 0.18.1.1 breaks it completely, even on fresh install. Until this is fixed, every time there is an update, I have to manually edit `nano $BTCPAY_DOCKER_COMPOSE` and replace `0.18.2.2-4` with `0.18.1.1` then restart docker.

Of course Id prefer latest version to be fixed, but until then, please downgrade the required monero version as currently it is unusable and requires a useless extra step when updating / setting up Monero.

**Comment by Kukks** [comment]
Please update https://github.com/btcpayserver/dockerfile-deps/tree/master/Monero/0.18.2.2 so that it goes back to the previous style.

**Comment by ndeet** [comment]
I think this was fixed in https://github.com/btcpayserver/btcpayserver-docker/pull/838 @michnovka can you confirm?
