### ISSUE TITLE
docker-compose fails on raspberry pi

### ISSUE THREAD

**Issue by pseudozach** [btcpayserver/btcpayserver-docker#85]
I've been trying to get btcpayserver-docker to work on raspberry pi 1 b (armv6) but it keeps failing with:
`BTCPay Server starting... this can take 5 to 10 minutes...
Job for btcpayserver.service failed because the control process exited with error code.
See "systemctl status btcpayserver.service" and "journalctl -xe" for details.
BTCPay Server started
**ERROR: .IOError: [Errno 2] No such file or directory: '/root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml'**`

I tried raspbian, kali-linux and now hypriot which has docker working but no luck. It seems the docker-compose-generator doesn't create any files at that directory. Is it possible the image is not built for armv6/armel ? Or is there something else I'm missing?

docker ps gives below. It seems like everything except postgres is restarting with cause 139:
`HypriotOS/armv6: pirate@black-pearl in ~
$ docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                            PORTS                                                                                    NAMES
f430ef6dbba2        btcpayserver/btcpayserver:1.0.3.45   "dotnet BTCPayServer…"   2 minutes ago       Restarting (139) 5 seconds ago                                                                                             generated_btcpayserver_1
e5264ba13ea1        btcpayserver/lnd:v0.5.1-beta-2       "/docker-entrypoint.…"   11 minutes ago      Restarting (139) 16 seconds ago                                                                                            btcpayserver_lnd_bitcoin
228f9372aa0d        btcpayserver/bitcoin:0.17.0          "/entrypoint.sh bitc…"   2 hours ago         Restarting (139) 3 minutes ago    8332-8333/tcp, 18332-18333/tcp, 18443-18444/tcp, 28332-28333/tcp, 39388/tcp, 43782/tcp   btcpayserver_bitcoind
2a4ea19d55ab        postgres:9.6.5                       "docker-entrypoint.s…"   2 hours ago         Up 2 hours                        5432/tcp                                                                                 generated_postgres_1
25af99673077        nicolasdorier/nbxplorer:2.0.0.11     "dotnet NBXplorer.dll"   2 hours ago         Restarting (139) 27 seconds ago                                                            `

**Comment by NicolasDorier** [comment]
please format your message I cna't read it

**Comment by NicolasDorier** [comment]
Your problem is probably that you are not using the mode for saving RAM.

```
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-xs;opt-save-memory"
```

**Comment by pseudozach** [comment]
yes I've been following the guide on https://docs.btcpayserver.org/deployment/raspberrypideployment including the saving RAM option. I built the .yaml on another machine and tried deploying it on the rpi but always got errors. 

The guide refers to a raspberry pi 3 which is armv8. I've been using the original raspberry pi which is armv6 and I always get segmentation fault on docker (139).
I wouldn't want you to waste your time on this, just wanted to check if it has been tested with the old pi and if possible can images can be built for this architecture?

**Comment by pseudozach** [comment]
> Ah btcpay only support armv7 and arm64!

I thought so :) I guess not many people left with the old pi. Thanks!

**Comment by NicolasDorier** [comment]
Nothing I can really do, arm6 is not supported by .NET :(
