### ISSUE TITLE
nginx container won't start: "real_ip_header" directive is duplicate in /etc/nginx/conf.d/default.conf:142

### ISSUE THREAD

**Issue by orfeas0** [btcpayserver/btcpayserver-docker#852]
nginx container will not start because of multiple real_ip_header directives. 
Logs:
```
2023/11/30 09:33:53 [emerg] 1#1: "real_ip_header" directive is duplicate in /etc/nginx/conf.d/default.conf:142
nginx: [emerg] "real_ip_header" directive is duplicate in /etc/nginx/conf.d/default.conf:142
```

Indeed, looking into the container's default.conf, I see near the end:
```
		set_real_ip_from 172.16.0.11;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.10;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.6;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.8;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.5;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.2;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.7;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.9;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.0.3;
        real_ip_header X-Real-IP;
		set_real_ip_from 172.16.255.254;
        real_ip_header X-Real-IP;
```

In `nginx.tmpl` there is
```
{{ if $container.Env.REAL_IP_HEADER }}
{{ range $containerNetwork := $container.Networks }}
set_real_ip_from {{ $containerNetwork.IP }};
{{ end }}
```

Which from my understanding, adds real_ip_header directive for each btcpayserver container, and this is wrong for nginx.

**Comment by orfeas0** [comment]
I don't use Cloudflare at all.

**Comment by dennisreimann** [comment]
Can you check that `BTCPAYGEN_ADDITIONAL_FRAGMENTS` doesn't contain the Cloudflare fragment?

```bash
echo $BTCPAYGEN_ADDITIONAL_FRAGMENTS
```

**Comment by orfeas0** [comment]
It doesn't contain cloudflare.

I think it's related to lnd-rest
https://github.com/btcpayserver/btcpayserver-docker/blob/6b5841efdc995d9f6187eb3495eb0354096d01db/Production/nginx.tmpl#L40-L43

This snippet generates multiple real_ip_header directives and it breaks nginx.
I removed it and it works fine.
I haven't made a PR because I don't know the implications of removing this.

**Comment by dennisreimann** [comment]
@NicolasDorier can you shina a light on what might be going on here? The search across all our repos only yields the Cloudflare fragment as defining `REAL_IP_HEADER` -> https://github.com/search?q=org%3Abtcpayserver+REAL_IP_HEADER&type=code

**Comment by NicolasDorier** [comment]
sorry about this, I have clightning, and not experiencign the issue. This is weird..

**Comment by NicolasDorier** [comment]
@orfeas0 can you share all your nginx?

**Comment by NicolasDorier** [comment]
@orfeas0 I couldn't find the root cause of your issue, nothing we did have `REAL_IP_HEADER` set to `X-Real-IP`. That said, The PR #862 will fix your specific issue.

**Comment by golyalpha** [comment]
@NicolasDorier
I have the same issue on an install from a few days back. afaik `REAL_IP_HEADER` is not explicitly set anywhere as far as I can see, but the config generator is treating it as set to `X-Forwarded-For`.

Here's my fragments configuration:
```
declare -x BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-lnd-autocompact;opt-lnd-autopilot;opt-lnd-keysend;opt-lnd-watchtower;opt-more-memory;opt-add-nolimits;opt-save-storage-xs;opt-add-btctransmuter;opt-add-configurator;opt-add-thunderhub;opt-add-bluewallet-lndhub;opt-add-lightning-terminal"
declare -x BTCPAYGEN_EXCLUDE_FRAGMENTS="nginx-https"
```

What might be "specific" about my deployment is that there are a bunch of other deployments of unrelated apps running and so there are multiple docker networks.

Worked around this for now by editing the nginx config template locally to avoid this, but it's not really a fix.
