### ISSUE TITLE
This script must be run as root after running "sudo su -"

### ISSUE THREAD

**Issue by ArbenKarb** [btcpayserver/btcpayserver-docker#854]
![image](https://github.com/btcpayserver/btcpayserver-docker/assets/31412198/c2a45275-2929-4895-8489-60bd2b54e461)

Trying to set up the domain. Returns error that the script must be run as root after running "sudo su -" although I already am root.

Lunanode deployment

**Comment by dennisreimann** [comment]
Try running it like this: `. ./btcpay-setup.sh -i`

**Comment by ArbenKarb** [comment]
same error

**Comment by ArbenKarb** [comment]
I believe there was a resouce issue when I last ran the update script. I since increased the resource on the virtual machine an ran the clean script. However, it appears there are major issues with it now. Can't access via the web anymore and the only thing that still works is ssh.

**Comment by petzsch** [comment]
couldn't reproduce on my RPI4 with Ubuntu 22.04 on it.
I usually switch to root with ```sudo -i```
which should have the same effect as the afore mentioned ```sudo su -``` (tried both and btcpay-setup.sh didn't complain)

@ArbenKarb could you check the output of the 2 commands @dennisreimann posted to see if they in fact return 0?

**Comment by ArbenKarb** [comment]
I reimaged the VM with an old snapshot, hence I can no longer reproduce. Apologies for wasting anyone's time.

**Comment by golyalpha** [comment]
I'm having the same issue now on my RPi4. Wanted to change some things after setting up, the initial install worked fine but now it's failing with the same error message.

```
root@pi:/home/pi/btcpayserver-docker# id -u
0
root@pi:/home/pi/btcpayserver-docker# echo $EUID
0
root@pi:/home/pi/btcpayserver-docker# . ./btcpay-setup.sh -i
This script must be run as root after running "sudo su -"
```

Apparently being in the shell through `sudo -s` doesn't work now (but it worked historically, idk what changed. I didn't update anything afaik)
