### ISSUE TITLE
FastSync snapshot old?

### ISSUE THREAD

**Issue by AnotherDroog** [btcpayserver/btcpayserver-docker#89]
Are the FastSync snapshots still being published regularly?

The listing shows one snapshot per chain from November:
http://utxosets.blob.core.windows.net/public?restype=container&comp=list&include=metadata

**Comment by NicolasDorier** [comment]
Yes, I think I will update one every 6 moth or so.
Reason is that for lightning it is better than you get old blocks so you can see old channels when you send.

**Comment by NicolasDorier** [comment]
Closed, last one Mon, 04 Mar 2019 06:27:36 GMT
