### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by premghinde** [btcpayserver/btcpayserver-docker#910]
I have a uptime checker that I use that is failing with error 405 Method not allowed.

It uses the HEAD method to make the call. I've tried externally using Postman and verified the result. None of the other sites I run have this issue and return a 200 code.

Steps to reproduce: Make a HEAD request to the root of a btcpay instance.

**Comment by dennisreimann** [comment]
This doesn't directly address your concern, but for uptime checks you could also use this endpoint: https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Health

And for more detailed information of the individual nodes, see https://docs.btcpayserver.org/API/Greenfield/v1/#tag/ServerInfo

**Comment by premghinde** [comment]
Thanks for the pointer @dennisreimann but the healthcheck endpoint also doesn't allow the HEAD method.

**Comment by premghinde** [comment]
Took some digging but found that the uptime monitor allows me to choose the method. :facepalm:
