### ISSUE TITLE
Can't connect Zap Desktop to BTCPay Server

### ISSUE THREAD

**Issue by synchroniz3** [btcpayserver/btcpayserver-docker#92]
Getting the following error when submitting the gRPC configuration file from BTCPay server in ZapDesktop:

**Unable to connect to host: Failed to connect before the deadline**

Setup: Ubuntu 18.04, latest BTCPay Server Docker, using ZapDesktop v0.3.3

I can create lightning invoices and when I test the connection in the store settings I get "Connection to the lightning node succeeded" and when I open the public node info page it shows online.

I've tried Zap Desktop on the same server the docker instance of BTCPay server is installed with no luck as well as a few other machines.

Please let me know if there are more details that I can provide that can help find a resolution here.

Thanks!

**Comment by NicolasDorier** [comment]
@synchroniz3 , does your SSL is correctly setup? (you can browse to your website without alerts)

If yes, what instructions did you followed when deploying BTCPAY?

**Comment by synchroniz3** [comment]
@pavlenex yes I purchased the SSL certificate however I've been unable to figure out how to install it. 

@NicolasDorier I deployed BTCPAY using docker following this guide: https://medium.com/@wordpressdelta/my-first-experience-with-btcpay-server-installation-on-ubuntu-18-04-ab9a58797430

Thanks

**Comment by NicolasDorier** [comment]
1. @synchroniz3 you don't need to buy a certificate, those are free
2. The link you provided is quite outdated and the most complicated way to install BTCPay.

Instead follow https://medium.com/@BtcpayServer/launch-btcpay-server-via-web-interface-and-deploy-full-bitcoin-node-lnd-in-less-than-a-minute-dc8bc6f06a3

**Comment by synchroniz3** [comment]
Brilliant. Thanks @NicolasDorier will do that now. :-)

**Comment by adiadore** [comment]
Sorry to hijack this, but i have a similar issue where i can't connect through ZapDesktop. 

So most of the time/days i got no problem, everything works. Then on another day i open ZapDesktop and i get **Unable to connect to host: Failed to connect before the deadline**.

**First** i always try server settings/services copy a fresh lnd config into ZapDesktop; (this never works).

_I used this deployment method: https://medium.com/@BtcpayServer/btcpay-woocommerce-cheap-ab6fcdd97075_

**Second** Then i try log into the VM via ssh and just ". ./btcpay-setup.sh -i" in the docker folder, so most of the time this solved the problem, but i did not know why.

So today both options did not work and i did some investigation, found out public lnd node IP **changed** to a IP address of my domain name service provider (namecheap). So i think this could be issue that host my.btcpayserver.hostname(=redirect to external IP from Luna VM Dashboard) can't be connected through ZapDesktop?

so my question is, why does it change the IP overnight?

**Comment by pavlenex** [comment]
@adiadore you can't just input the command without troubleshooting. I think that in your case sort of a restart worked. No, the IP does not change overnight.

I recommend that you try `btcpay-restart.sh` when you face connection problems. And if you still face issues, it's the best to look through your LND logs, [check this guide out.](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-lightning-network-logs)

**Comment by adiadore** [comment]
@pavlenex so I tried to connect with ZapDesktop again today after 3 days, and i couldn't, checked the IP of the lightning node (stores/settings/lnd modify/test connection) and it was the one it should be. here are the last 40 lines of the log **before** i did a restart [last 40](https://pastebin.com/2Hv7V2Sw)

So i did btcpay-restart.sh as you recommended now the IP has **changed** again to the one in previous post (stores/settings/lnd modify/test connection) [last 500 lines of log](https://pastebin.com/wyUqJTff) where the restart starts at line 65

so the only line which catches my eye before and after restart is probably 

> [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.100

 with differenct ports, this could be me connecting with ZapDesktop? (although this is not my home IP)

but the question why the ip changes remains unclear to me

**Comment by pavlenex** [comment]
Your logs look okay at the first glance. I don't know why you can't connect to zap. If you get a green mark when testing a connection, Zap should connect, unless you're using a complex DIY environment, cloudflare, etc.

So how do you host your btcpay/LND?

Make sure you're running latest version of BTCPay and Zap.

**Comment by adiadore** [comment]
as mentioned i used this method [Running BTCPay..](https://medium.com/@BtcpayServer/btcpay-woocommerce-cheap-ab6fcdd97075)
here are the versions, zap is newest too (tried on windows 10 and osx) 
<img width="1280" alt="bildschirmfoto 2019-02-18 um 16 17 57" src="https://user-images.githubusercontent.com/36714025/52960351-e914a280-3398-11e9-98b4-2b0cac752e91.png">
funny thing is i am still connected with my phone since day one where i used the QR Code

**Comment by NicolasDorier** [comment]
What is your domain name? Change of IP seems strange to me.

**Comment by adiadore** [comment]
pay.novummonetae.com, i found this https://github.com/btcpayserver/btcpayserver/issues/291 so i removed the lightning_alias and now its back to the 51.68.5.199 ip, but still cant connect with ZapDesktop, in iOS with Zap App i can disconnect and connect without problems

**Comment by NicolasDorier** [comment]
Your IP keep changing...

![image](https://user-images.githubusercontent.com/3020646/53008197-3584de80-347c-11e9-9dc5-f0d84607d521.png)

Your DNS is setup to use two different IP. This should not be the case.
Please only use `51.68.5.199`

**Comment by adiadore** [comment]
So i wrote to my domain name hoster, 10 minutes later the 2nd IP from dns lookup disappeared and another 30 minutes later i could connect via ZapDesktop. Seems like the problem is solved, thank you guys!

**Comment by NicolasDorier** [comment]
cool!
