### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by kehiy** [btcpayserver/btcpayserver-docker#921]
We are trying to run a BTC pay server for our Bitcoin-only business right now since we are limited to using third-party services. But we had an issue which is it's too complex to run the docker image from the docker hub and as we understand it's impossible to run it without bash scripts in this repo(?). If I got it right, any other ways to do it using docker more simply???

**Comment by dennisreimann** [comment]
See our [Docker deployment documentation](https://docs.btcpayserver.org/Docker/#full-installation-for-technical-users).
