### ISSUE TITLE
how do I point to the latest release?

### ISSUE THREAD

**Issue by Frankenmint** [btcpayserver/btcpayserver-docker#945]
I tried ./btcpay-update.sh and it sort of works but it's not pulling from the latest new 2.0 version of btcpay-server, how do i use that to load my docker instance and update?

**Comment by webiumsk** [comment]
Read the blog post here https://blog.btcpayserver.org/btcpay-server-2-0/

**Comment by rockstardev** [comment]
@Frankenmint as @webiumsk is saying, there is section in blog post that explains you need to switch to `2.0` branch and run `btcpay-update.sh`:

```
cd $BTCPAY_BASE_DIRECTORY/btcpayserver-docker
git fetch -a
git checkout 2.0
./btcpay-update.sh
```

We made it opt-in like that because there is a lot of data migration involved and it's one-way (no support for rollback).

**Comment by Frankenmint** [comment]
thanks y'all.... I still encounter an issue trying to update after manually setting a branch, my guess is that I need to disable these plugins. I set this up once like six months ago, I can't find the yaml file that was generated that I need to remove the plugin lines from so this successfully updates, also once I roll forward to 2.0 can i use btcpay-update.sh to update to 2.0.1? 
![image](https://github.com/user-attachments/assets/1150ce82-4f27-4b48-9e5f-766e17c0d1d0)
