### ISSUE TITLE
Unexpected Container Running After Installation

### ISSUE THREAD

**Issue by devcedme** [btcpayserver/btcpayserver-docker#959]
I noticed that after installing BTCPay Server, a Tor container is running. During the installation process, I did not select the option to install a Tor node. Additionally, the BTCPay Server user interface does not show any indication of a Tor node being active. However, when I check with docker stats, it clearly shows a Tor container running:

![Screenshot 24 11 2024 um 23 39 43 PM](https://github.com/user-attachments/assets/3723d7ff-6483-4775-96eb-74bf362dfff5)

Here is my configuration:

export BTCPAY_HOST="btcpay.mydomain.com"
export BTCPAY_ADDITIONAL_HOSTS="192.168.100.102"
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage"
export BTCPAYGEN_REVERSEPROXY="none"
export BTCPAY_ENABLE_SSH=true

Steps to reproduce:
	1.	Install BTCPay Server without selecting the Tor option.
	2.	Check running containers using docker stats.

**Comment by dennisreimann** [comment]
Tor is activated by default on the docker deployment ([reasoning](https://docs.btcpayserver.org/FAQ/Deployment/#why-activate-tor-does-it-mean-that-nobody-knows-who-i-am)). If you want to disable it, see [this](https://docs.btcpayserver.org/FAQ/Deployment/#how-do-i-disable-tor-on-my-btcpay-server).
