### ISSUE TITLE
[Feature Request] Database Backups

### ISSUE THREAD

**Issue by JeffVandrewJr** [btcpayserver/btcpayserver-docker#98]
It would be nice to be able to easily backup and restore a BTCPay instance.

The backup could be just a shell script that executes this command that @lightbo_lt uses: https://chat.btcpayserver.org/btcpayserver/pl/bi15ze9iipgrueaw7zcj4pmd4r Maybe that could even run as like a cron job.

I'm not a PostgreSQL expert so I'm not sure exactly how the restore side of that would work, but if you've got the dump from the command above there must be a way straightforward way to restore it.

**Comment by pavlenex** [comment]
This is sort of a duplicate of [this](https://github.com/btcpayserver/btcpayserver/issues/431) and [this](https://github.com/btcpayserver/btcpayserver/issues/289) also [this](https://github.com/btcpayserver/btcpayserver-doc).

I think it would be much better to consolidate all these requests into a single issue  and post in the main repository.

**Comment by JeffVandrewJr** [comment]
@pavlenex My bad on the duplicate. I'm closing this issue and posting my comment on your referenced issue as part of the main repo.
